### ISSUE TITLE
Add more questions related to strings linked list

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1]
Solve more hackerank Linked list strings questions(unsolved in this repo) related to Linked list strings and send a PR

**Comment by Aiswarika** [comment]
Hey can you please assign me this issue? @Ayush7614

**Comment by mitali-1703** [comment]
Hey @Ayush7614 can I add some basic to intermediate level Linked List problems of GFG under LGM-SOC'21?
