### ISSUE TITLE
Added question of Gfg for interview

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Daily-Coding-DS-ALGO-Practice#10]

**Comment by shvmsh20** [comment]
@Ayush7614 can you provide description for this issue.

**Comment by anirudhsuresh522001** [comment]
Hi @Ayush7614 , I am interested in this issue,
Is it an issue in which I should create a folder and add the gfg interview problems in it, if yes Can I be assigned with this ?

**Comment by Ayush7614** [comment]
> Hi @Ayush7614 , I am interested in this issue,
> Is it an issue in which I should add the gfg interview problems in the existing gfg folder, Can I be assigned with this ?

Sure @anirudhsuresh522001 but you can tell me you are contribute in competition or without competition

**Comment by Aiswarika** [comment]
Hi @Ayush7614, is this issue assigned, or can I work on it?

**Comment by anirudhsuresh522001** [comment]
@Ayush7614 , Either way it is fine, I will work on it.

**Comment by anirudhsuresh522001** [comment]
> Hi @Ayush7614, is this issue assigned, or can I work on it?

@Ayush7614 , Either way it is fine, I will work on it.

**Comment by anirudhsuresh522001** [comment]
> > Hi @Ayush7614 , I am interested in this issue,
> > Is it an issue in which I should add the gfg interview problems in the existing gfg folder, Can I be assigned with this ?
> 
> Sure @anirudhsuresh522001 but you can tell me you are contribute in competition or without competition

@Ayush7614 , Either way it is fine, I will work on it.
