### ISSUE TITLE
Anagram in Python

### ISSUE THREAD

**Issue by pranita736** [Ayush7614/Daily-Coding-DS-ALGO-Practice#100]
# Aim

- To contribute to LGM-SoC'21.

# Details

- Code for finding Anagram.

**Comment by pranita736** [comment]
Assign this to me.

**Comment by Sumanth2905** [comment]
Assign this to me in C programming.

**Comment by Ayush7614** [comment]
> Assign this to me.

@pranita736 you are participant in LGM SOC 21

**Comment by Ayush7614** [comment]
> Assign this to me in C programming.

@Sumanth2905 and you are also participant In LGM-SOC 21

**Comment by Ayush7614** [comment]
I can't assign me this under LGM-SOC 21 Because current the program was not start when program was started then I assigned to you under LGM-SOC'21

**Comment by pranita736** [comment]
@Ayush7614 yes, I'm participant in LGM SOC 21

**Comment by Sumanth2905** [comment]
@Ayush7614 Yes, I'm a participant in LGM-SoC'21.

**Comment by Ayush7614** [comment]
> @Ayush7614 yes, I'm participant in LGM SOC 21

When program was started then I assign to you thus under LGM-SOC 21

**Comment by pranita736** [comment]
Okay, I'll wait.

**Comment by Sumanth2905** [comment]
> > @Ayush7614 yes, I'm participant in LGM SOC 21
> 
> When program was started then I assign to you thus under LGM-SOC 21

Okay, I'll wait.

**Comment by Jagannath8** [comment]
@Ayush7614  Assign this to me.  I'm participant in LGM SOC 21.

**Comment by Ayush7614** [comment]
> @Ayush7614 Assign this to me. I'm participant in LGM SOC 21.

First you can check the timeline of LGM-SOC 21 program was start from 10 June so from 10 june i will assigned you this will not count towards your contribution in program if you work without program then i will assign you and if you work under program then i will assign from 10 June

**Comment by Ayush7614** [comment]
Go Ahead @pranita736 @Sumanth2905

**Comment by Ayush7614** [comment]
> @Ayush7614 Assign this to me. I'm participant in LGM SOC 21.

@Jagannath8 bro you can work on different issues because firstly pranita and Sumanth was asked to me if you working in any other language then i will assign you

**Comment by Jagannath8** [comment]
I can use python for solving

**Comment by Ayush7614** [comment]
> I can use python for solving

@Jagannath8 sorry brother i can`t assign you because in python @pranita736 was solved so you can work on diffenret issue and if you wish you can also opened issues from your sides then i will assign you

**Comment by Jagannath8** [comment]
okay
