### ISSUE TITLE
All Stack Operation

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1000]
# Aim

- I would Like to add Stack operations in Data Structure Folder.

# Details

- I would like to add Linked List Implementation and Array Implementation of Stack in a single code which involve all the operations like Push, Pop, Display .
- LGM-SOC'21
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 @Amit366 @Saurabh4626 @ravikr126 Please Assign me this issue. I would like to solve this in C++.
**LGM_SOC'21**

Thank You

**Comment by tirth5828** [comment]
@Ayush7614   @Amit366   @Saurabh4626  @ravikr126 , I would love to do this issue in JAVA , Please assign me this issue under LGM_SOC'21

**Comment by Raghav-Bhandari** [comment]
@Ayush7614 @Amit366 Please Assign me this issue. I will solve this issue in C language
LGM_SOC'21

**Comment by Aditya1113** [comment]
@ShivanshuVishnoi can you please assign me this issue under LGMSOC'21. will solve it in c++

**Comment by ravikr126** [comment]
See many stack operation related questions are available so please specify the question @ShivanshuVishnoi

**Comment by ShivanshuVishnoi** [comment]
@ravikr126 Sir I have specified all the operation like push elements into stack ,pop elements from stack and display all the elements from stack by using both array and linked list implementation in a single code.
