### ISSUE TITLE
Preorder traversal of a binary tree (Iterative approach)

### ISSUE THREAD

**Issue by saloni32** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1002]
I want to provide a C++ code for printing preorder traversal of a binary tree without recursion (i.e.  by using iterative approach)
I am LGM SOC'21  participant and want to provide this code with proper comments and explanation.

@Ayush7614  @Amit366  @Saurabh4626  @ravikr126  Please assign me this issue.

**Comment by saloni32** [comment]
I want to add this code in Gfg folder . please assign me this issue. @Ayush7614  @Amit366 @Saurabh4626 @ravikr126

**Comment by ravikr126** [comment]
It already in repository.@saloni32
