### ISSUE TITLE
Postorder traversal of a Binary Tree (Iterative approach)

### ISSUE THREAD

**Issue by saloni32** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1005]
I want to provide a C++ code for printing postorder traversal of a binary tree without recursion (i.e.  by using iterative approach)
I am LGM SOC'21  participant and want to provide this code with proper comments and explanation.

@Ayush7614  @Amit366  @Saurabh4626  @ravikr126  Please assign me this issue.

**Comment by saloni32** [comment]
I have added the code for postorder traversal of binary tree using iterative approach and created a pull request .
Please review it.
@Saurabh4626  @Ayush7614

**Comment by siddhi-244** [comment]
Can I try in python ?
