### ISSUE TITLE
Bottom View of a Binary Tree

### ISSUE THREAD

**Issue by somuy24** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1006]
I want to provide a C++ code for printing "Bottom View of a Binary Tree".
I am LGM SOC '21 participant and want to provide this code with proper comments and explanations.

@Ayush7614 @ravikr126 @Amit366 @Saurabh4626 
Please assign me this issue

**Comment by Saurabh4626** [comment]
from next time mention folder in which u will push

**Comment by somuy24** [comment]
ok @Saurabh4626 sir 
I would like to add my code in Data Structures folder.

**Comment by somuy24** [comment]
@Saurabh4626 
Will you please add label to this question.

**Comment by somuy24** [comment]
@Saurabh4626 
I will add  my code in GFG folder.
Please assign label to this problem.

**Comment by somuy24** [comment]
@Saurabh4626 @Ayush7614 
I have added the code of Bottom view of the Binary Tree.
Please review the changes.
