### ISSUE TITLE
Sieve of Eratosthenes

### ISSUE THREAD

**Issue by Sumanth2905** [Ayush7614/Daily-Coding-DS-ALGO-Practice#101]
# Aim

- Implementation of the algorithm in C.

 
# Details

- Algorithm for finding all the prime numbers in a segment [1;n].

**Comment by Sumanth2905** [comment]
@Ayush7614 Assign this issue to me.

**Comment by Rajdeep-99** [comment]
Is this issue assigned? If not I will like to work on it.

**Comment by Ayush7614** [comment]
> Is this issue assigned? If not I will like to work on it.

@Rajdeep-99 First you can tell me you can contribute in competition or as without competition

**Comment by Rajdeep-99** [comment]
Without competition

**Comment by Ayush7614** [comment]
> Without competition

go Ahead

**Comment by Ayush7614** [comment]
> @Ayush7614 Assign this issue to me.

@Sumanth2905 go Ahead but you can do this in C language

**Comment by mitali-1703** [comment]
Hey @Ayush7614 can I add a solution to this problem in Java language under LGM-SOC'21?

**Comment by anshyyy** [comment]
hey @Ayush7614 i would like to work on this issue.
