### ISSUE TITLE
Valid Mountain Array

### ISSUE THREAD

**Issue by Nikhita28** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1011]
I would like to add a solution to this question.

![Screenshot 2021-06-15 233944](https://user-images.githubusercontent.com/73106734/122102412-035ccf00-ce33-11eb-96ae-e74fba23f476.png)

### Language:
C++

**Comment by apran-vs** [comment]
I would like to do this issue in python

**Comment by Jagannath8** [comment]
Can I do in Java? I'm a participant of LGM Soc21.

**Comment by viki4545** [comment]
i would like to work on this issue in java
