### ISSUE TITLE
 Minimum distance between two numbers

### ISSUE THREAD

**Issue by 19bce502** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1019]
**AIM **
 Given an array A, of N elements. Find minimum index based distance between two elements of the array, x and y

**Detail**
This is a gfg problem which was asked in amazon interview. 
Please Assign me this problem under LGM SOC . I will be doing in c++.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ravikr126** [comment]
THIS QUESTION ALREADY AVAILABLE @19bce502
