### ISSUE TITLE
Binary Search in c

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#102]
Hey @Ayush7614,
I wanted to add binary search in c
Please assign me to do it...
Thanks

**Comment by Ayush7614** [comment]
> Hey @Ayush7614,
> I wanted to add binary search in c++
> Please assign me to do it...
> Thanks

Hy @UG-SEP thanks for your intrset but plss tell you are working on this issue under competition or without competition

**Comment by UG-SEP** [comment]
under competition

**Comment by Ayush7614** [comment]
> under competition

LGM-SOC'21

**Comment by Ayush7614** [comment]
Actually @UG-SEP competition was starting from 10 of June so your contribution for competition was counting from 10 of June

**Comment by Ayush7614** [comment]
But if you work without competition then you can work then I will assign you but under competition you work from 10 of June

**Comment by UG-SEP** [comment]
> Actually @UG-SEP competition was starting from 10 of June so your contribution for the competition was counting from 10 of June

It's doesn't matter to me. I not working here as a competitor. I am working here as a learner and the LGM-SOC'21 is also organized to contribute and learn

**Comment by Ayush7614** [comment]
> > Actually @UG-SEP competition was starting from 10 of June so your contribution for the competition was counting from 10 of June
> 
> It's doesn't matter to me. I not working here as a competitor. I am working here as a learner and the LGM-SOC'21 is also organized to contribute and learn

So brother I will say na you have to work without competition so I will assign you but your Contribution for LGM SOC count by 10 june

**Comment by Ayush7614** [comment]
@UG-SEP for your learning purposes I will assign you go Ahead @UG-SEP

**Comment by Rajdeep-99** [comment]
I would like to add the binary search

**Comment by Ayush7614** [comment]
> I would like to add the binary search

Sorry @Rajdeep-99 but this issue i alreday assigned to @UG-SEP you can work on other issues

**Comment by oneamanish** [comment]
see my pull req.
