### ISSUE TITLE
Dominant Piranha problem of contest 1433/Q.C on codeforces

### ISSUE THREAD

**Issue by Saup21** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1021]
# Aim

- A problem that requires greedy method and constructive algo to be solved

# Details

- I have solved the code in C++ and it will add value to the project

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ravikr126** [comment]
no need for competitive programming questions only ds algo questions @Saup21
