### ISSUE TITLE
Even-Odd Game problem of contest 1472/Q.D on codeforces

### ISSUE THREAD

**Issue by Saup21** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1022]
# Aim

- A game problem that requires sorting, greedy method and optimal steps to be solved

# Details

- I have solved the code in C++ and it will add value to the project

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by kamleshjoshi8102** [comment]
I would love to provide my python code for this Interesting Problem under LGMSOC'21 @Amit366 @Ayush7614

**Comment by ravikr126** [comment]
no need for competitive programming questions only ds algo questions @Saup21
