### ISSUE TITLE
Shortest Common Supersequence(DP) - C++

### ISSUE THREAD

**Issue by Anshika-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1025]
**Question:**
Given two strings s1 and s2 and we have to find the length of shortest supersequence consisting of both s1 and and s2.
Shortest Common Supersequence finds the shortest supersequence which consist of all the characters of both the string in the order specified.  Supersequence have the same relative order but may or may not be continuous.

**I would like to contribute my code under LGMSOC'21**

**Comment by kumarshobhit** [comment]
Would like to contribute in java language

**Comment by rakesh419s** [comment]
I'd like to solve it in python assign it to me!

**Comment by Pratik57** [comment]
I'd like to solve in c under LGMSOC21
