### ISSUE TITLE
Different readme files for contributor and how to contribute section

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#103]
**Is your feature request related to a problem? Please describe.**
<code>Adding how to contribute and contributor in the same readme.md not look too good it creates the user to scroll much</code>
**Describe the solution you'd like**
<code>I think we should add the contributor name and how to contribute in a different readme file so that makes the work easy and looks good</code>

**Additional context**
NA

**Comment by Ritikkumar992** [comment]
Assign me
