### ISSUE TITLE
Spell checker

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#104]
# Aim

Create a spell checker to check whether the comment in the code has the right spelling or not...

# Details

Suppose Someone creates a program to check whether the string is a pangram or not and in the comment, by mistake he/she write the spelling of pangram wrong i.e. `pangam` so the spell check will notify in check that the spelling is wrong i.e.` pangam->pangram`

Can I work on this

**Comment by Ayush7614** [comment]
No I have not assign this sorry but I have to close this one because I think we don't have need of this you can working on either open issues
