### ISSUE TITLE
Josephus problem

### ISSUE THREAD

**Issue by 19bce502** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1042]
**AIM**
Given the total number of persons n and a number k which indicates that k-1 persons are skipped and kth person is killed in circle in a fixed direction.

The task is to choose the safe place in the circle so that when you perform these operations starting from 1st place in the circle, you are the last one remaining and survive.

Please Assign me this problem under LGM SOC  I will be doing in c++ .

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ravikr126** [comment]
In which language you will make pr??@19bce502

**Comment by 19bce502** [comment]
in c++

**Comment by 19bce502** [comment]
As I have already done and pulled request for this problem

**Comment by 19bce502** [comment]
This problem was already assigned to me and done also .

**Comment by ravikr126** [comment]
copy issue #674 @19bce502
