### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by rahulsrivastava1** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1045]
# Aim

- To implement merge sort

# Details

- A C code of merge sort

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by KishkinJ10** [comment]
Can I work on this i am LGM-SOC 2021 participant??

**Comment by Jagannath8** [comment]
Can I do in Java? I'm a participant of LGM Soc21.

**Comment by abhisheks008** [comment]
Hey I can contribute the solution of this code using 4 languages such as, Python, C, C++ and Java. Please assign me in any of these languages.

**Comment by ravikr126** [comment]
already in repository @rahulsrivastava1

**Comment by rahulsrivastava1** [comment]
ok @ravikr126 my bad.
