### ISSUE TITLE
Prims Algorithm

### ISSUE THREAD

**Issue by rahulsrivastava1** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1049]
### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by KishkinJ10** [comment]
Can  I give the solution I am a LGM-SOC 21 participant?

**Comment by rahulsrivastava1** [comment]
@KishkinJ10 why are you pulling request to this , while its assigned to me.
hey @Saurabh4626 i uploaded my both codes kindly check it.

**Comment by KishkinJ10** [comment]
@rahulsrivastava1  the issues were still open ?

**Comment by rahulsrivastava1** [comment]
@KishkinJ10 i think if you were assigned after that you will work on it...

**Comment by Pratik57** [comment]
@Saurabh4626  Assign me this in cpp under LGMSOC21 please

**Comment by rahulsrivastava1** [comment]
hey @Saurabh4626 review it please

**Comment by joshi-kaushal** [comment]
I can resolve this in C
