### ISSUE TITLE
Tokenization of String

### ISSUE THREAD

**Issue by Rutikab12** [Ayush7614/Daily-Coding-DS-ALGO-Practice#105]
Hey, @Ayush7614 I want to contribute the following program in the Data Structure folder as a SOC'21 Participant.

**Tokenization of string**
Tokenizing a string denotes splitting a string with respect to some delimiter. Using strtok().

Assign me if possible. Thank You.

**Comment by Ayush7614** [comment]
> Hey, @Ayush7614 I want to contribute the following program in the Data Structure folder as a SOC'21 Participant.
> 
> **Tokenization of string**
> Tokenizing a string denotes splitting a string with respect to some delimiter. Using strtok().
> 
> Assign me if possible. Thank You.

Actually @Rutikab12  competition was starting from 10 of June so your contribution for competition was counting from 10 of June But if you work without competition then you can work then I will assign you but under competition you work from 10 of June

**Comment by Rutikab12** [comment]
> > Hey, @Ayush7614 I want to contribute the following program in the Data Structure folder as a SOC'21 Participant.
> > **Tokenization of string**
> > Tokenizing a string denotes splitting a string with respect to some delimiter. Using strtok().
> > Assign me if possible. Thank You.
> 
> Actually @Rutikab12 competition was starting from 10 of June so your contribution for competition was counting from 10 of June But if you work without competition then you can work then I will assign you but under competition you work from 10 of June

Okay, I will be working on this issue from 10 June as part of the competition.

**Comment by Ayush7614** [comment]
> > > Hey, @Ayush7614 I want to contribute the following program in the Data Structure folder as a SOC'21 Participant.
> > > **Tokenization of string**
> > > Tokenizing a string denotes splitting a string with respect to some delimiter. Using strtok().
> > > Assign me if possible. Thank You.
> > 
> > 
> > Actually @Rutikab12 competition was starting from 10 of June so your contribution for competition was counting from 10 of June But if you work without competition then you can work then I will assign you but under competition you work from 10 of June
> 
> Okay, I will be working on this issue from 10 June as part of the competition.

yess bro then you will read the guidelines and all things

**Comment by Rutikab12** [comment]
> > > > Hey, @Ayush7614 I want to contribute the following program in the Data Structure folder as a SOC'21 Participant.
> > > > **Tokenization of string**
> > > > Tokenizing a string denotes splitting a string with respect to some delimiter. Using strtok().
> > > > Assign me if possible. Thank You.
> > > 
> > > 
> > > Actually @Rutikab12 competition was starting from 10 of June so your contribution for competition was counting from 10 of June But if you work without competition then you can work then I will assign you but under competition you work from 10 of June
> > 
> > 
> > Okay, I will be working on this issue from 10 June as part of the competition.
> 
> yess bro then you will read the guidelines and all things

Sure.

**Comment by puneetkaur2929** [comment]
Hey @Ayush7614 , 
Please assign this issue to me as I want to get some idea of open source contributions . So, i am earnestly looking for opportunities.
I ll be solving this using C++ stringstream class.

**Comment by Ayush7614** [comment]
@Rutikab12 Go Ahead

**Comment by Ayush7614** [comment]
> Hey @Ayush7614 ,
> Please assign this issue to me as I want to get some idea of open source contributions . So, i am earnestly looking for opportunities.
> I ll be solving this using C++ stringstream class.

first you can tell me you are participant in LGM SOC or not

**Comment by Rutikab12** [comment]
> @Rutikab12 Go Ahead

Okay. Thank you.

**Comment by puneetkaur2929** [comment]
Yes @Ayush7614  I am participant of LGM SOC 21 & I  know actual contribution will start from 10th June . but being a newcomer to Open source ,through this issue I just wanted to get acquainted with Open source development .
