### ISSUE TITLE
Attention❗ Typo Mistake 

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1054]
Hey @Ayush7614,
Please fix the typo mistake highlighted in the image
![typo](https://user-images.githubusercontent.com/75884061/122224519-d0b5e380-ced1-11eb-8213-0ac10c6341af.jpg)

**Comment by Ritikkumar992** [comment]
Let me resolve this issue.

**Comment by UG-SEP** [comment]
> Let me resolve this issue.

Why not ??
