### ISSUE TITLE
Error: Invalid file path

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#106]
Hey @Ayush7614,
Please rename the [sudoku | backtracking-7.cpp](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/blob/main/Algorithms/Backtracking/Sudoku%20%7C%20Backtracking-7.cpp)
Because window doesn't accept `|` symbol in filename [know more about it](https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3)
![error](https://user-images.githubusercontent.com/75884061/120517378-0648d000-c3ee-11eb-9c6d-b2faefc2a27d.jpg)
Hope you understand and fix it soon...
Thanks

**Comment by Ayush7614** [comment]
> Hey @Ayush7614,
> Please rename the [sudoku | backtracking-7.cpp](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/blob/main/Algorithms/Backtracking/Sudoku%20%7C%20Backtracking-7.cpp)
> Because window doesn't accept `|` symbol in filename [know more about it](https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3)
> ![error](https://user-images.githubusercontent.com/75884061/120517378-0648d000-c3ee-11eb-9c6d-b2faefc2a27d.jpg)
> Hope you understand and fix it soon...
> Thanks

Goood @UG-SEP Thanks for informing me

**Comment by Ayush7614** [comment]
Now you can work i can fix this

**Comment by UG-SEP** [comment]
same problem in Hackerrank folder in [Arrays: Left Rotation.cpp](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/blob/main/Hackerank/Arrays:%20Left%20Rotation.cpp)
![error](https://user-images.githubusercontent.com/75884061/120599453-29fb2d00-c465-11eb-8d92-fea908fb9c60.jpg)
in the file, you use `:` which is restricted in window OS.
so please rename the file

**Comment by Ayush7614** [comment]
![Uploading Screenshot_2021-06-03-12-24-59-62.jpg…]()
Actually @UG-SEP many type of contributers are there so many problems was there this was done by any other contributed

**Comment by Ayush7614** [comment]
Now I can fix that you can check it now

**Comment by Ayush7614** [comment]
And any other problem like this then you can inform me @UG-SEP
