### ISSUE TITLE
Topological Sort - Graph (Python)

### ISSUE THREAD

**Issue by kamleshjoshi8102** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1061]
# Aim
Topological sorting for Directed Acyclic Graph (DAG) is a linear ordering of vertices such that for every directed edge uv, vertex u comes before v in the ordering. Topological Sorting for a graph is not possible if the graph is not a DAG.
I would like to provide my python code for this.
Please assign me this under LGMSOC'21

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Saurabh4626** [comment]
this  problem is already assigned
