### ISSUE TITLE
Soduku Solver in C++

### ISSUE THREAD

**Issue by Shaishav0507** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1065]
# Aim

Hey @Ayush7614 
I would like to add Soduku solver code in C++.
Please assign it to me.
Thanks

# Details

- What the features will your script have

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by KishkinJ10** [comment]
Can I give this solution??
I am a LGM-SOC participant

**Comment by kumarshobhit** [comment]
Would like to contribute in java language

**Comment by Amit366** [comment]
@Shaishav0507 sorry but cpp is already done.If u want please try with java
