### ISSUE TITLE
Sorting Algorithm - Topological Sort

### ISSUE THREAD

**Issue by Ayush12062000** [Ayush7614/Daily-Coding-DS-ALGO-Practice#107]
Hey, I'm Ayush, a participant in LGM-SOC. Want to add the Topological sort in the algorithm section. Please assign me this issue.

@Ayush7614

**Comment by Ayush7614** [comment]
go Ahead @Ayush7614

**Comment by SahityaRoy** [comment]
Hey @Ayush7614  i want to contribute in sorting algorithm problem  tell me in details what to do for this 
my mail id- sahitya.roy@uem.edu.in
 [Linkedin](https://www.linkedin.com/in/sahitya-roy/)

**Comment by Ayush12062000** [comment]
> Hey @Ayush7614 i want to contribute in sorting algorithm problem tell me in details what to do for this
> my mail id- [sahitya.roy@uem.edu.in](mailto:sahitya.roy@uem.edu.in)
> [Linkedin](https://www.linkedin.com/in/sahitya-roy/)



@SahityaRoy Buddy start by selecting an algorithm and make an issue explaining what and which algorithm you want to contribute and wait until that issue is assigned to you. Then follow the instructions mentioned in the repo.

**Comment by SahityaRoy** [comment]
> > Hey @Ayush7614 i want to contribute in sorting algorithm problem tell me in details what to do for this
> > my mail id- [sahitya.roy@uem.edu.in](mailto:sahitya.roy@uem.edu.in)
> > [Linkedin](https://www.linkedin.com/in/sahitya-roy/)
> 
> @SahityaRoy Buddy start by selecting an algorithm and make an issue explaining what and which algorithm you want to contribute and wait until that issue is assigned to you. Then follow the instructions mentioned in the repo.

@Ayush12062000 i wanna work upon Bubble sort, selection sort, insertion sort etc
