### ISSUE TITLE
Adding some linked list related problems

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1087]
# Aim

- Will be adding some linked list related problems in GFG folder.

# Details

- Problems to be added, such as  :-
- [Delete alternate nodes.](https://practice.geeksforgeeks.org/problems/delete-alternate-nodes/1/?category[]=Linked%20List&category[]=Linked%20List&problemStatus=solved&page=1&query=category[]Linked%20ListproblemStatussolvedpage1category[]Linked%20List)
- [Finding middle of the linked list.](https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1/?category[]=Linked%20List&category[]=Linked%20List&problemStatus=solved&page=1&query=category[]Linked%20ListproblemStatussolvedpage1category[]Linked%20List)
- [Delete without head pointer.](https://practice.geeksforgeeks.org/problems/delete-without-head-pointer/1/?category[]=Linked%20List&category[]=Linked%20List&problemStatus=solved&page=1&query=category[]Linked%20ListproblemStatussolvedpage1category[]Linked%20List)
- [occurrence of an integer in a linked list.](https://practice.geeksforgeeks.org/problems/occurence-of-an-integer-in-a-linked-list/1/?category[]=Linked%20List&category[]=Linked%20List&problemStatus=solved&page=1&query=category[]Linked%20ListproblemStatussolvedpage1category[]Linked%20List)
- [Delete Middle of the linked list.](https://practice.geeksforgeeks.org/problems/delete-middle-of-linked-list/1/?category[]=Linked%20List&category[]=Linked%20List&problemStatus=unsolved&page=1&query=category[]Linked%20ListproblemStatusunsolvedpage1category[]Linked%20List)
- [Check if the Linked List is Circular.](https://practice.geeksforgeeks.org/problems/circular-linked-list/1/?category[]=Linked%20List&category[]=Linked%20List&problemStatus=unsolved&page=1&query=category[]Linked%20ListproblemStatusunsolvedpage1category[]Linked%20List#)
- [Nth Node from end of the linked list.](https://practice.geeksforgeeks.org/problems/circular-linked-list/1/?category[]=Linked%20List&category[]=Linked%20List&problemStatus=unsolved&page=1&query=category[]Linked%20ListproblemStatusunsolvedpage1category[]Linked%20List#)

>  Please assign me this issue,@Ayush7614 @Amit366 @ravikr126  @Saurabh4626 _**LGM SoC'21 participant**_

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

**Comment by ravikr126** [comment]
some of your question already raised
