### ISSUE TITLE
Minimum Element in a Stack - Medium

### ISSUE THREAD

**Issue by Hanesh-Jogani** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1097]
**Is your feature request related to a problem? Please describe.**
Addition of a new problem named **Minimum Element in a Stack**

**Name of the File** - Minimum_Element_Stack.java
**Destination Folder** - Daily-Coding-DS-ALGO-Practice/Data Structures/

### Programming language
- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

I want to do this under **LGM-SOC'21**.

**Comment by Hanesh-Jogani** [comment]
@ravikr126 
@Ayush7614 
@Amit366 
@Saurabh4626 

Sir, please assign this to me.

**Comment by ravikr126** [comment]
You can work on it @Hanesh-Jogani
