### ISSUE TITLE
Added question of codechef for interview

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Daily-Coding-DS-ALGO-Practice#11]

**Comment by tech-rounak** [comment]
hey sir could I contibute

**Comment by Ayush7614** [comment]
> hey sir could I contibute

Hy @tech-rounak thanks for your intrset but first tell me you are part of any open source program or you can contribute without program

**Comment by tech-rounak** [comment]
sir i have registered for LGM SOC

**Comment by Ayush7614** [comment]
> sir i have registered for LGM SOC

Okk @tech-rounak but LGM SOC start from 10 June so you can contribute from 10 june for LGM SOC so that you contribution count in score

**Comment by Ayush7614** [comment]
@tech-rounak go Ahead

**Comment by tech-rounak** [comment]
sir I have created a pull request you please check it and merge

**Comment by tech-rounak** [comment]
@Ayush7614 Sir , please response

**Comment by tech-rounak** [comment]
Sorry to ask but Why the pull request not merged
