### ISSUE TITLE
ADDIING 3 QUESTIONS TO HACKERRANK FOLDER

### ISSUE THREAD

**Issue by kalash-kala** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1103]
# Aim

- I would like to add 3 questions to the hackerrank folder with solution in c++

# Details

- Q1. Height of a binary tree
- Q2. Tree  postorder traversal
- Q3. Tree inorder traversal

Please assign me this issue, LGM SoC'21 participant

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ravikr126** [comment]
copy issue

**Comment by kalash-kala** [comment]
Sir I am new to open source , does copy issue mean someone else has done this before?
