### ISSUE TITLE
Solved : HackerRank 

### ISSUE THREAD

**Issue by simarjeet30** [Ayush7614/Daily-Coding-DS-ALGO-Practice#111]
# Aim To present the solution of all the problem solving questions in c++

# Details: I m having 4 stars in HackerRank  and I would love to share my solutions which will be very easy to understand .
- What the features will your script have
I will make a single folder and will update it regularly with new commits .

**Comment by Ritikkumar992** [comment]
@simarjeet30  I am a 3 star at codechef and a newbie at coderforce . I wish to add questions regarding the same.
Allow me to do so..

**Comment by hv65616** [comment]
**Hello Ayush, This is Himanshu Verma and I am a B.tech from CSE student .**

**I would to love contribute to this particular issue if you provide me the opportunity and assign me the task to do so. I am having 
 5 Star in C++ on Hackerrank and also currently having 3 Star in Problem Solving. So if you consider me then please provide me the opportunity.**

**If you wish you can check out my LinkedIn as well as Hackerrank profile**

- LinkedIn:- [https://www.linkedin.com/in/himanshu-verma-94a1a41b8/](url)
- HackerRank:- https://www.hackerrank.com/hv65616

**Comment by vajpayeemrudul** [comment]
Hello @Ayush7614 , I have solved some good level of questions on hackerrank and I want to contribute in this issue. Can you pls assign this to me.
