### ISSUE TITLE
Priority queue in python

### ISSUE THREAD

**Issue by Khushi-agarwal** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It's an algorithm in queue data structure which I want to implement in python language.
Please assign it to me under lgm-soc.
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

**Comment by ravikr126** [comment]
please specify the questions @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
Implementing priority queue data structure @ravikr126

**Comment by Khushi-agarwal** [comment]
@Amit366 kindly assign me this issue.

**Comment by Khushi-agarwal** [comment]
@Saurabh4626 @Ayush7614 please assign me this issue.
