### ISSUE TITLE
Merge Sort in Python

### ISSUE THREAD

**Issue by Shaishav0507** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1111]
# Aim

Hey @Ayush7614 
I would like to add Merge Sort in Python.
Please assign me this.
Thanks

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

**Comment by abhisheks008** [comment]
I can add the code using Java and Python language. Can you assign me this?

**Comment by Shaishav0507** [comment]
@Ayush7614 @abhisheks008 
Can I go ahead ?

**Comment by ravikr126** [comment]
already in repository @Shaishav0507

**Comment by Shaishav0507** [comment]
@ravikr126 It's not there in Python
Please check

**Comment by Shaishav0507** [comment]
@

> already in repository @Shaishav0507

Not in python
