### ISSUE TITLE
Taxi program from codeforces

### ISSUE THREAD

**Issue by Khushi-agarwal** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want to add the solution of taxi problem from code forces.
Problem link-https://codeforces.com/problemset/problem/158/B

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python
Please assign it to me under lgmsoc @Ayush7614 @Amit366

**Comment by ravikr126** [comment]
you can work on it @Khushi-agarwal
