### ISSUE TITLE
Bitwise Tuples | CodeChef

### ISSUE THREAD

**Issue by Debargha-arch** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1122]
# Aim

- Chef has two numbers N and M. Help Chef to find number of integer N-tuples (A1,A2,…,AN) such that 0≤A1,A2,…,AN≤2^M−1 and A1&A2&…&AN=0, where & denotes the bitwise AND operator.
Since the number of tuples can be large, output it modulo (10^9)+7.

# Details
*NOTE* - The question appeared in the contest June Challenge 2021(Div. 3) which is over now .

Problem Link : https://www.codechef.com/JUNE21C/problems/BITTUP

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Debargha-arch** [comment]
Please assign this issue to me. I will be giving the solution in C++ .

**Comment by ravikr126** [comment]
You can work on it @Debargha-arch
