### ISSUE TITLE
I Hate 1111 (Problem 1526B)

### ISSUE THREAD

**Issue by tirth5828** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1129]
# Aim

- Solve Problem 1526B of Codeforces

# Details

- This is a problem Under Number theory, I would love to solve this, Please assign me this under LGMSOC21 for C++ and JAVA

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by tirth5828** [comment]
@ravikr126   @Ayush7614   @Saurabh4626

**Comment by ravikr126** [comment]
you can work on it @tirth5828  and add some testcases in comment also
