### ISSUE TITLE
Pythagorean Triples (Problem 1487D)

### ISSUE THREAD

**Issue by tirth5828** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1132]
# Aim

- Solve Problem 1487D of Codeforces

# Details

- This is a problem based on Number theory and Brute force
-  @ravikr126   @Ayush7614  @Saurabh4626 please assign me this under LGMSOC21 for C++ and JAVA

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ravikr126** [comment]
you can work n it @tirth5828
