### ISSUE TITLE
Find the Duplicate Number 

### ISSUE THREAD

**Issue by Shreya-Sharma8** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1142]
**Problem Statement**
Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive.
There is only one repeated number in nums, return this repeated number.
You must solve the problem without modifying the array nums and uses only constant extra space.

**Details**
This question is often asked in coding interviews. It is based on Arrays, Two Pointer and Binary Search.

@ravikr126 @Ayush7614 @Saurabh4626 please assign me this under LGMSOC'21 for C++

Problem link - https://leetcode.com/problems/find-the-duplicate-number/

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ambivert-sam** [comment]
@Saurabh4626 I can do this in python please assign it to me I'm a participant of LGMSOC'21

**Comment by Saurabh4626** [comment]
@ambivert-sam  already assigned

**Comment by ambivert-sam** [comment]
@Saurabh4626 For python also?
