### ISSUE TITLE
 Symmetric Tree (Breadth-first Search)

### ISSUE THREAD

**Issue by ambivert-sam** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1144]
**Is your feature request related to a problem? Please describe.**
Want to add  Symmetric Tree in Python Data structures Folder

**Describe the solution you'd like**

 Problem Statement :
 Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).

Example 1:

![image](https://user-images.githubusercontent.com/74984661/122458613-a3e6f680-cfcd-11eb-9620-07303eeeb9c9.png)

Input: root = [1,2,2,3,4,4,3]
Output: true

Example 2:

 
![image](https://user-images.githubusercontent.com/74984661/122458708-bcefa780-cfcd-11eb-8534-e46de54497be.png)

Input: root = [1,2,2,null,3,null,3]
Output: false

**Describe alternatives you've considered**
Leet Code question no. 101

**Additional context**
I would like to contribute and work on this issue as a participant of LGM SOC'21 will you please assign it to me

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

**Comment by JahnaviKashyap19** [comment]
Please assign me this issue .I am a participant of LGMSoc'21. I will provide the code in C++

**Comment by ravikr126** [comment]
already raise issue
