### ISSUE TITLE
Kuriyama Mirai's Stones of codeforces

### ISSUE THREAD

**Issue by akash435** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1149]
want to add the solution for this ques of codeforces.
the ques code is 433 B.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by akash435** [comment]
@Ayush7614 , this assign me this under LGM SOC, i can add solution of this codeforces ques.

**Comment by kamleshjoshi8102** [comment]
@Ayush7614 Can I contribute in Python under LGMSOC 21
