### ISSUE TITLE
Variable Sized Arrays (C++)

### ISSUE THREAD

**Issue by singhmansi25** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1159]
**Is your feature request related to a problem? Please describe.**
The problem is a part of C++, HackerRank . It showcases how variable size arrays can be implemented using loops. Difficulty level of problem is easy. 

**Describe the solution you'd like**
Solving the problem using loops for better understanding

**Additional context**
<img width="406" alt="a1" src="https://user-images.githubusercontent.com/76874762/122515896-b55eeb80-d02b-11eb-9465-1e1df8bbdaeb.png">

### Programming language

- [ ] C
- [✔ ] C++
- [ ] Java
- [ ] Python

**Comment by ashutosh887** [comment]
Hey!
Should I work on this ?

**Comment by singhmansi25** [comment]
In which programming language, as I'm going to do in C++ !!!!!!!!

**Comment by ashutosh887** [comment]
I can do with JAVA 
Is it assigned to you ?

**Comment by singhmansi25** [comment]
Not yet !! But I have opened the issue.

**Comment by singhmansi25** [comment]
When I will be assigned the issue ?? I haven't got any updates yet !!!

**Comment by singhmansi25** [comment]
No updates yet @Ayush7614  !!!
Please assign the issue
