### ISSUE TITLE
Union of 2 arrays in python

### ISSUE THREAD

**Issue by siddhi-244** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1163]
# Aim

Given two sorted arrays, find their union.
Example:

Input : arr1[] = {1, 3, 4, 5, 7}
arr2[] = {2, 3, 5, 6}
Output : Union : {1, 2, 3, 4, 5, 6, 7}

What is the objective of the Script
It finds the union of two sorted arrays.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by siddhi-244** [comment]
Can I do it in python ?

**Comment by Ashu-1309** [comment]
I want to do the program kindly assign me the work .

**Comment by Ashu-1309** [comment]
Can it do the same code in C ????
