### ISSUE TITLE
Implementing Queue Using python

### ISSUE THREAD

**Issue by dhruv-varshney** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1182]
**Is your feature request related to a problem? Please describe.**
Aim is to implement a data structure-queue using python 

**Describe the solution you'd like**
To implement the queue i will use the deque class which comes from collections module

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ravikr126** [comment]
already raise issue @dhruv-varshney
