### ISSUE TITLE
 Bubble Sorting using python

### ISSUE THREAD

**Issue by dhruv-varshney** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1183]
**Is your feature request related to a problem? Please describe.**
To implement Bubble sort using Python

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by PradeepBaipadithaya** [comment]
Hi,
Can i try this issue

**Comment by Ayan-thecodeking** [comment]
i can do this in cpp and java language 
please assign :)

**Comment by Harikrishnaa3131** [comment]
Can I do this in Python?
