### ISSUE TITLE
OCTAT image not working. Can u please short out it.

### ISSUE THREAD

**Issue by Ritikkumar992** [Ayush7614/Daily-Coding-DS-ALGO-Practice#120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ayush7614** [comment]
@Ritikkumar992 you work on it then i will assign you or i work on it

**Comment by Ritikkumar992** [comment]
ok thanks @Ayush7614

**Comment by Ritikkumar992** [comment]
@Ayush7614  can u give me some clue how to short out this issue.

**Comment by Ayush7614** [comment]
You dont working on this this issue i will fix it

**Comment by Ritikkumar992** [comment]
ok thanks
