### ISSUE TITLE
Small Factorials of Codechef under LGMSOC'21

### ISSUE THREAD

**Issue by rajeshkumar2024** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1201]
# Aim

- want to add solution of Small Factorials of Codechef under LGMSOC'21

# Details

- Problem link - https://www.codechef.com/problems/FCTRL2
- Problem code - FCTRL2

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ashu-1309** [comment]
I want to work on this program kindly assign me.
