### ISSUE TITLE
The Lead Game of Codechef under LGMSOC'21 

### ISSUE THREAD

**Issue by rajeshkumar2024** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1202]
# Aim

- Want to add solution of The Lead Game of Codechef under LGMSOC'21.

# Details

- Problem link - https://www.codechef.com/problems/TLG
- Problem code - TLG

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by Kaavya-Saxena** [comment]
Please assign this issue to me . i would like to use c++ for this

**Comment by rajeshkumar2024** [comment]
@Ayush7614 @ravikr126 @Amit366 please assign me this issue.

**Comment by Amit366** [comment]
@rajeshkumar2024 which contest is this question from??

**Comment by rajeshkumar2024** [comment]
@Amit366 I have seen this question in practice section.
