### ISSUE TITLE
Total Expenses of Codechef under LGMSOC'21

### ISSUE THREAD

**Issue by rajeshkumar2024** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1203]
# Aim

- Want to add solution of Total Expenses of Codechef under LGMSOC'21

# Details

- Problem Link - https://www.codechef.com/problems/FLOW009
- Problem code - FLOW009

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 @Amit366 @ravikr126 @Saurabh4626 Please Assign me this issue. I will solve this problem in C++.
LGM-SOC'21

THANK YOU

**Comment by ShivanshuVishnoi** [comment]
@Amit366 Please Check the PR I have Created and merge it. I solve the Problem in C++.
LGM-SOC'21

Thank You
