### ISSUE TITLE
Racing Horses of CodeChef under LGMSOC'21

### ISSUE THREAD

**Issue by rajeshkumar2024** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1204]
# Aim

- Want to add solution of Racing Horses from Codechef under LGMSOC'21.

## Language used - Java

# Details

- Problem link - https://www.codechef.com/problems/HORSES
- Problem code - HORSES

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by Kaavya-Saxena** [comment]
I would like to provide the solution to this problem in c++ please assign me this issue

**Comment by rajeshkumar2024** [comment]
@Ayush7614 @ravikr126 @Amit366 please assign me this issue.
