### ISSUE TITLE
[Geeks For Geeks] Lucky alive person in a circle.

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1208]
# Aim

- will be adding solution for [lucky alive person in a circle.](https://practice.geeksforgeeks.org/problems/lucky-alive-person-in-a-circle1229/1) in GFG folder.

# Details

-  Level of the Question - _**Medium**_.
- Topic - _**Bit Manipulation**_

> Problem Statement :-

- Given N people standing in a circle where 1st is having a sword, find the luckiest person in the circle, if, from 1st soldier who is having a sword each has to kill the next soldier and handover the sword to next soldier, in turn, the soldier will kill the adjacent soldier and handover the sword to next soldier such that one soldier remains in this war who is not killed by anyone.

> Please assign me this issue, _**LMG SoC'21**_ Participant.

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

**Comment by Aryan-Srivastava** [comment]
@Saurabh4626 @ravikr126 @Ayush7614 Please Assign me this issue. I will solve it in java.
LGM-SOC'21

Thank You

**Comment by rakesh419s** [comment]
please assign me the above problem statement in python

**Comment by anusham14** [comment]
please assign me this issue in C++. Thank you

**Comment by apran-vs** [comment]
I would like to solve this issue in python

**Comment by kamleshjoshi8102** [comment]
@Saurabh4626 @ravikr126 @Ayush7614 Please Assign me this issue. I will solve it in C.
LGM-SOC'21
