### ISSUE TITLE
Interview questions on binarysearch

### ISSUE THREAD

**Issue by Aiswarika** [Ayush7614/Daily-Coding-DS-ALGO-Practice#121]
Hey @Ayush7614, I want to add interview questions on binarysearch site as a part of the LGM SOC contest. Can you please assign me this issue?

**Comment by sejal1430** [comment]
Hey @Ayush7614 ,  I would like to add some interview question on binary search, so could you please assign this issue to me?

**Comment by Ayush7614** [comment]
Go Ahead @Aiswarika

**Comment by Ayush7614** [comment]
> Hey @Ayush7614 , I would like to add some interview question on binary search, so could you please assign this issue to me?

Sorry @sejal1430 but first issue was assigning to Aiswarika because she asked first if you code in different language then i will assign you

**Comment by Ayush7614** [comment]
@Aiswarika in which langugae you code this issue

**Comment by Aiswarika** [comment]
@Ayush7614  preferably CPP.

**Comment by Ayush7614** [comment]
Okk so @sejal1430 if you code in any other language then i will assign you

**Comment by sejal1430** [comment]
yes @Ayush7614 , I code in java.

**Comment by Ayush7614** [comment]
Go Ahead @sejal1430

**Comment by Ayush7614** [comment]
I will close this issue @sejal1430 @Aiswarika because you can add only single single question for one issue so open new issue and add single single question issue question name
