### ISSUE TITLE
Online Stock Span [Leetcode]

### ISSUE THREAD

**Issue by AvneetSingh2001** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1210]
#### Want to add solution of "Online Stock Span" from Leetcode.
Kindly assign me this problem. I would like to add my solution to this problem in C++ using Stacks.
## Details
Leetcode Problem Link :  [https://leetcode.com/problems/online-stock-span/](https://leetcode.com/problems/online-stock-span/)
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kamleshjoshi8102** [comment]
hi, I want to solve this issue using java
Please assign this issue to me under LGMSOC'21
@Saurabh4626 @Amit366

**Comment by rakesh419s** [comment]
please assign me the above statement in Python Under LGM-SOC'21
