### ISSUE TITLE
Dice Tower question on Codeforces 

### ISSUE THREAD

**Issue by ChetasShree** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1213]
hi, I want to solve this issue using C++
Please assign this issue to me under LGM-SOC21 and HCSSoC .
Looking forward to contribute here...

Question link: https://codeforces.com/contest/225/problem/A
@Ayush7614

**Comment by ChetasShree** [comment]
Can this issue be assigned under HCSSoC also ,if one issue can be assigned under one program ,then pls assign this issue under HCSSoC? @Saurabh4626

**Comment by sejal1430** [comment]
@Ayush7614 , @Amit366 Can I work on this issue in Java?
