### ISSUE TITLE
Longest Consecutive Sequence 

### ISSUE THREAD

**Issue by 19bce502** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1222]
**AIM**
Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence.

Please Assign me under LGM SOC .I will be solving in C++ language.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ashu-1309** [comment]
Can I try this program using python. Kindly allow me.

**Comment by Saurabh4626** [comment]
@Ashu-1309  do in python only
@19bce502  do in c++

**Comment by Ashu-1309** [comment]
Okay
