### ISSUE TITLE
longest sub array using c++

### ISSUE THREAD

**Issue by manognyaa** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1225]
AIM :
to give output of longest sub array  with the sum
**Describe the solution you'd like**
I will be using c++ language for this  @Ayush7614  sir.

**Additional context**

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

I would like to work on this issue sir, please assign me @Ayush7614  sir

**Comment by siddhi-244** [comment]
Can I try in python?
