### ISSUE TITLE
alive  - dynamic problem

### ISSUE THREAD

**Issue by manognyaa** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1226]
#### Aim:
There are n people in a circle waiting to be executed, starting from any position, a person starts executing the a'th person ahead of her, then the person after the one who is executed repeats the same task, as there will be only one person surviving, we have to find the person who will remain alive.

**Describe the solution you'd like**
This will come under dynamic problems folder.
I will be using c++ language  @Ayush7614 sir

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

@Ayush7614 sir, please assign this issue to me, I would like to work on this.

**Comment by Wittty-Panda** [comment]
can i do in python ?
