### ISSUE TITLE
First Missing Positive LeetCode (Hard)

### ISSUE THREAD

**Issue by agamgupta2015** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1230]
**Additional context**
Q :-Given an unsorted integer array nums, find the smallest missing positive integer.
You must implement an algorithm that runs in O(n) time and uses constant extra space.
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
I want to work on this issue

**Comment by harshita9621** [comment]
I want to work on this issue

**Comment by siddhi-244** [comment]
Can I try in python ?

**Comment by 31081998** [comment]
can I resolve this issue in java and c language?

**Comment by Amit366** [comment]
@harshita9621 mention the language

**Comment by 31081998** [comment]
can I resolve this issue in java and c language?

**Comment by harshita9621** [comment]
@Amit366 I try in C++

**Comment by Amit366** [comment]
@harshita9621 cpp is already done.

**Comment by Amit366** [comment]
If u want u can work in java or c

**Comment by harshita9621** [comment]
@Amit366 In java

**Comment by Amit366** [comment]
@31081998 do in c

**Comment by 31081998** [comment]
@Amit366  can I generate a pull request for the First missing positive in Java, as the issue previously assigned to me is submitted by another participant, and the java code is still pending?

**Comment by Amit366** [comment]
Ok @31081998 do in java

**Comment by 31081998** [comment]
@Amit366  kindly assign me write permission
![image](https://user-images.githubusercontent.com/30019483/123842824-d75f4480-d92e-11eb-9271-aa3d0f963002.png)

**Comment by Amit366** [comment]
@31081998 check whether u have cloned the forked repo or not

**Comment by 31081998** [comment]
@Amit366 sir I have cloned the forked repo
