### ISSUE TITLE
Maximum possible subtree sum in a tree  

### ISSUE THREAD

**Issue by harsh6768-svg** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1231]
# Aim

Largest subtree sum in a tree

# Details

- This is the most famous question of  GFG asked many times in interview  
- We will be provided a binary tree and we will find the maximum possible subtree sum in a tree. 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kamleshjoshi8102** [comment]
can I provide my code in Java under LGMSOC21 @Saurabh4626

**Comment by siddhi-244** [comment]
Can I try in python under lgmsoc?

**Comment by Ayush7614** [comment]
Go Ahead @siddhi-244 @kamleshjoshi8102

**Comment by kamleshjoshi8102** [comment]
@ravikr126 sir my pull request not merged
