### ISSUE TITLE
Find the pair with the given sum in doubly linked list

### ISSUE THREAD

**Issue by harsh6768-svg** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1232]
# Aim
Asked many times in interview most famous question of GFG 

# Details

- We will given the doubly linked list with the target value and we need to find the pair with the given target 
- For example:
- Input : head : 1 <-> 2 <-> 4 <-> 5 <-> 6 <-> 8 <-> 9
        x = 7
Output: (6, 1), (5,2)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kamleshjoshi8102** [comment]
@Ayush7614 @Saurabh4626 Can I try this in C under LGMSOC'21
