### ISSUE TITLE
"Hail XOR" Problem of CodeChef

### ISSUE THREAD

**Issue by Mugdha-Hazra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1237]
# Aim

I want to add the code for the "Hail XOR" problem in CodeChef.

# Details

Problem name: Hail XOR
Problem Code:  HXOR
Problem link: https://www.codechef.com/DEC20B/problems/HXOR

Please assign me this issue
LGM-SOC Participant

### Programming language
**C++**
- [ ] C
- [X] C++
- [ ] Java
- [ ] Python

Hello @prudhvirajstark @cmulay @VinayakMohite4040 @shantamsultania @Sumanth2905 sir, I think this is an important question and this should definitely be added in the Daily-Code-DS-Algo-Practice and I will start working on it as soon as I get assigned!! as I am a part of the LGM-SOC'21 participant, so I would like to implement this in c++.

**Comment by Mugdha-Hazra** [comment]
thank you, @Saurabh4626 sir, for assigning me this issue I have create the pull request can you please review it.

**Comment by siddhi-244** [comment]
Can I try in python ?

**Comment by siddhi-244** [comment]
Plzz assign me this in python
