### ISSUE TITLE
Kids With the Greatest Number of Candies

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1241]
# Aim

- I would like to add a Problem in LeetCode Folder.
# Details

- I would like to add Kids With the Greatest Number of Candies Problem of leetcode.
- https://leetcode.com/problems/kids-with-the-greatest-number-of-candies/
- LGM-SOC'21
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Saurabh4626 @ravikr126 @Ayush7614 Please Assign me this issue. I will solve it in C++.
LGM-SOC'21

Thank You

**Comment by Atif0604** [comment]
i want to do in c language @Saurabh4626

**Comment by siddhi-244** [comment]
Can I do in python ? Under lgmsoc
