### ISSUE TITLE
Pascal Triangle (Leetcode)

### ISSUE THREAD

**Issue by surbhi594** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1244]
I would like to add this question in C++ language.

![Screenshot (83)](https://user-images.githubusercontent.com/71223742/122652435-7b413700-d15c-11eb-8d6e-2aa2a04ec3d7.png)

**Comment by harshita9621** [comment]
Can I work on this issue?

**Comment by kamleshjoshi8102** [comment]
Can I provide my code in c under Lgmsoc'21

**Comment by siddhi-244** [comment]
Can I try in python under lgmsoc ?

**Comment by surajm-333** [comment]
I would like to code this problem in Java. Can you please assign this issue to me?

**Comment by Amit366** [comment]
@harshita9621 mention the language

**Comment by Amit366** [comment]
@harshita9621 mention the language

**Comment by harshita9621** [comment]
@Amit366 In C++

**Comment by Amit366** [comment]
@harshita9621 it is already assigned in cpp

**Comment by harshita9621** [comment]
@Amit366 In C

**Comment by harshita9621** [comment]
Can I work on this using C.

**Comment by surajm-333** [comment]
Can I work on this issue in Java?

**Comment by harshita9621** [comment]
@Amit-45 Pascal triangle get updated Kindly review.
