### ISSUE TITLE
Find the Duplicate Number LEETCODE

### ISSUE THREAD

**Issue by Saup21** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1247]
# Finding duplicate number in an array

# Details

- The objective is to find the number that appears more than once in an array using 2-pointer

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by harshita9621** [comment]
Can I work on this issue?

**Comment by Arushi247** [comment]
@Ayush7614 @Saurabh4626 I'd like to work on this issue in C language under HCSSoC

**Comment by Deep06-11** [comment]
I would like to solve this issue in c++ under LGM-SOC'21. Please assign it to me.
