### ISSUE TITLE
CodeChef Bytelandian gold coins 

### ISSUE THREAD

**Issue by vanishasamriddhi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1249]
I want to give the solution of this amazing question that I recently solved on CodeChef. 
https://www.codechef.com/problems/COINS

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by siddhi-244** [comment]
Can I try in python?

**Comment by kamleshjoshi8102** [comment]
Can I provide my code in C/C++ under LGMSOC'21

**Comment by kamleshjoshi8102** [comment]
@Ayush7614 sir what about C ? 😅
