### ISSUE TITLE
Unlucky Ticket of Codeforces

### ISSUE THREAD

**Issue by akash435** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1250]
Want to add the solution of this codeforces question "Unlucky Ticket",
The ques code for this is 160 - B in codeforce.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by akash435** [comment]
@Ayush7614 , please assign me this under LGM SOC, can add the solution of this ques in codeforces section.

**Comment by siddhi-244** [comment]
Can I try in python ?

**Comment by kamleshjoshi8102** [comment]
@Saurabh4626 sir my issues were closed of Codeforces stating you weren't accepting CF questions @Amit366 @Ayush7614 sir why ?

**Comment by kamleshjoshi8102** [comment]
Can  I contribute in C language under LGMSOC'21
