### ISSUE TITLE
 Solution of Shortest Common Supersequence of LeetCode

### ISSUE THREAD

**Issue by Isha307** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1274]
# Aim

- Wants to add the solution of Shortest Common Supersequence of LeetCode

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Isha307** [comment]
@Ayush7614 @Saurabh4626 Please assign me this issue.

**Comment by siddhi-244** [comment]
Can I try in python ?

**Comment by Isha307** [comment]
> # Aim
> * Wants to add the solution of Shortest Common Supersequence of LeetCode
> 
> ### Programming language
> * [ ]  C
> * [x]  C++
> * [ ]  Java
> * [ ]  Python

Please assign me this under LGMSOC'21 ?  @Ayush7614 @Saurabh4626 @ravikr126
