### ISSUE TITLE
Topic wise Leetcode Problem with the difficulty level of Easy to Medium

### ISSUE THREAD

**Issue by Ritikkumar992** [Ayush7614/Daily-Coding-DS-ALGO-Practice#128]

**Comment by Ritikkumar992** [comment]
Hey @Ayush7617 I wish to add some problem regarding the same . Can u please assign me the task.

**Comment by Ayush7614** [comment]
@Ritikkumar992 can you plss tell me you are participant in LGM SOC or not

**Comment by Anuradha0501** [comment]
@Ayush7614  can I also work on this issue as an LGM SOC participant
