### ISSUE TITLE
Reverse Linked List Using Stack Data Structure

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1287]
# Aim

- I would like to add this in Data Structure Folder.

# Details

- I would like to Add Code of Reverse Linked List using Stack Data Structure.
- LGM-SOC'21

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 @Amit366 @Saurabh4626 @ravikr126 Please Assign me this issue. I will solve this in C++.
LGM-SOC'21

Thank You

**Comment by Arushi247** [comment]
@Ayush7614 @Saurabh4626 I'd like to work on this issue in C language under HCSSoC.

**Comment by Deep06-11** [comment]
@Ayush7614 @Amit366 @Saurabh4626 @ravikr126 I would like to solve this issue under LGM-SOC'21. Please assign it to me.

**Comment by harshita9621** [comment]
@Amit366 @Saurabh4626 @Ayush7614 @ravikr126 Kindly assign me this issue using C++ under LGMSOC
