### ISSUE TITLE
Chefland Visa from code chef

### ISSUE THREAD

**Issue by Khushi-agarwal** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1289]
**Is your feature request related to a problem? Please describe.**
I would like to add the solution of the chef land visa question from code chef.
Please assign me this issue under lgm-soc

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by manuvarghese0603** [comment]
I would like to solve this in python
Please assign me this issue under lgm-soc

**Comment by kamleshjoshi8102** [comment]
@Saurabh4626 @ravikr126 @Ayush7614 Please Assign me this issue. I will solve it in java.
LGM-SOC'21

**Comment by Khushi-agarwal** [comment]
@Ayush7614 @Amit366 kindly assign me this issue.

**Comment by Khushi-agarwal** [comment]
@ravikr126 @Saurabh4626 kindly assign me this issue.

**Comment by ravikr126** [comment]
> I would like to solve this in python
> Please assign me this issue under lgm-soc

Without assign you can't create pr .

**Comment by manuvarghese0603** [comment]
> > I would like to solve this in python
> > Please assign me this issue under lgm-soc
> 
> Without assign you can't create pr .

Sir I didn't made any PR , the above PR was made by @suy1968

**Comment by kamleshjoshi8102** [comment]
> > I would like to solve this in python
> > Please assign me this issue under lgm-soc
> 
> Without assign you can't create pr .

Respected sir, I asked before @Khushi-agarwal why I wasn't given? 
: )

**Comment by Amit366** [comment]
@manuvarghese0603 this issue is created by khushi

**Comment by Amit366** [comment]
@Khushi-agarwal u can do in 2 languages. Mention the languages u wanna do in.

**Comment by Khushi-agarwal** [comment]
> @Khushi-agarwal u can do in 2 languages. Mention the languages u wanna do in.

C++ and java

**Comment by manuvarghese0603** [comment]
@Amit366 
Sir I would like to solve it in C++ too.
Please assign me this issue under lgm-soc

**Comment by Amit366** [comment]
@manuvarghese0603 go ahead

**Comment by Khushi-agarwal** [comment]
@Amit366 the code is already present in c++

**Comment by Amit366** [comment]
@Khushi-agarwal where is it present??

**Comment by Khushi-agarwal** [comment]
> @Khushi-agarwal where is it present??

Pr 1350

**Comment by Amit366** [comment]
Ok so it's already done.

**Comment by manuvarghese0603** [comment]
@Amit366 
Sir should I add the c++ code?
Since I didn't created the issue I can't reopen it.

**Comment by Amit366** [comment]
@manuvarghese0603 cpp is already present so don't add
