### ISSUE TITLE
Mountain Scenery question on Codeforces 

### ISSUE THREAD

**Issue by ChetasShree** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1295]
hi, I want to solve this issue using C++
Please assign this issue to me under HCSSoC (Hack Club SRM Summer of Code) .
Looking forward to contribute here...

Question link: https://codeforces.com/contest/218/problem/A
@Ayush7614

**Comment by kamleshjoshi8102** [comment]
hi, I want to solve this issue using C or python
Please assign this issue to me under HCSSoC (Hack Club SRM Summer of Code) .

@Ayush7614

**Comment by ChetasShree** [comment]
@ravikr126 ,my code hasn't been merged??
