### ISSUE TITLE
Median of two Sorted Array of equal size

### ISSUE THREAD

**Issue by neha030** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1305]
I want to add a C++ code for finding the median of two sorted array of equal size in the data structure folder . 
I am a LGM-SOC Participant 
Please assign me this issue

**Comment by Ayan-thecodeking** [comment]
I would like to work on this issue Under LGM-SOC'21.
In java language 
@Ayush7614 @Saurabh4626 @ravikr126 sir Please assign it to me.

**Comment by PriyankaHotchandani** [comment]
I would like to solve this in Python. Please assign it to me under LGM-SoC'21.

**Comment by Arushi247** [comment]
@Ayush7614 @ravikr126 @Saurabh4626 I'd like to work on this issue in C language under HCSSoC. Please assign me this issue.

**Comment by ravikr126** [comment]
This is already in repository@PriyankaHotchandani
