### ISSUE TITLE
Kth Largest Element in an Array 

### ISSUE THREAD

**Issue by neha030** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1322]
I want to solve this issue using C++
Please assign this issue to me under HCSSoC (Hack Club SRM Summer of Code) .
Looking forward to contribute 

@Ayush7614

**Comment by apran-vs** [comment]
I want to solve this issue in python.

**Comment by ayush2011** [comment]
I want to solve this issue using C++.
Please assign this issue to me under LGM-SOC'21
Want to contribute @Ayush7614

**Comment by kamleshjoshi8102** [comment]
I want to solve this issue using java
Please assign this issue to me under HCSSoC (Hack Club SRM Summer of Code) .

**Comment by Harikrishnaa3131** [comment]
@Ayush7614 @Amit366
I want to solve this issue using C
Please assign this issue to me under HCSSoC (Hack Club SRM Summer of Code) .

**Comment by SrihariTadala** [comment]
Im preparing for my  coding interviews and it would really help me if you assign this question to me 
Kindly assign me this issue under LGMSOC

**Comment by sonamgupta136** [comment]
Please assign me this issue under LGMSOC'21.
I will like to solve this in python

**Comment by Amit366** [comment]
This code is already present in the repo
