### ISSUE TITLE
Reverse a Linked List in groups of given size

### ISSUE THREAD

**Issue by Palak2801** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1328]
**Is your feature request related to a problem? Please describe.**
Reverse a Linked List in groups of given size

**Describe the solution you'd like**
Implementation of reversing every k nodes in linked list using C++

Example: 

Input: 1->2->3->4->5->6->7->8->NULL, K = 3 
Output: 3->2->1->6->5->4->8->7->NULL 

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Palak2801** [comment]
@Amit366 @Ayush7614 @ravikr126 @Saurabh4626 , Kindly assign me this issue using C++ under LGMSOC

**Comment by ravikr126** [comment]
Already raised issue @Palak2801
