### ISSUE TITLE
 Check  whether  n	is  present  in	an array  of	size	m	or	not In C language.

### ISSUE THREAD

**Issue by PalakDua-work** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1331]
n is the number u want to check which would given by the user.
Sample Input: 
5
2
1 2 3 4 5
Output : True/false
I wan to give solution in C language.
@Ayush7614  @Saurabh4626 @ravikr126  Please assign me this task under LGM-SOC'21

**Comment by TasnimAnas** [comment]
I want to solve this in C++

**Comment by kamleshjoshi8102** [comment]
please assign me the above problem statement under LGM-SOC'21 in C++ or java

**Comment by siddhi-244** [comment]
Can I try in python

**Comment by nekkantimadhu** [comment]
please assign me the above problem statement under LGM-SOC'21 in C++ or C or Python
