### ISSUE TITLE
Code Chef's Too Much XOR (Hard)

### ISSUE THREAD

**Issue by ghost** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1332]
Code chef's Too Much XOR question with the difficulty of Hard and the contest is over today 12:00 am.

**Comment by rakesh419s** [comment]
please assign me the above problem statement under LGM-SOC'21
I can solve in Python Language.

**Comment by kamleshjoshi8102** [comment]
please assign me the above problem statement under LGM-SOC'21 in C++
