### ISSUE TITLE
Merge two sorted linked lists

### ISSUE THREAD

**Issue by Palak2801** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1333]
**Is your feature request related to a problem? Please describe.**
Merge two sorted linked lists

**Describe the solution you'd like**
Implementation of merge two sorted linked list using C++

For example,
Linked list a : 5->10->15-> NULL 
Linked list b : 2->3->20->NULL
Merge list will be: 2->3->5->10->15->20->NULL

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Palak2801** [comment]
@Amit366 @Ayush7614 @ravikr126 @Saurabh4626 , Kindly assign me this issue using C++ under LGMSOC

**Comment by kamleshjoshi8102** [comment]
@Amit366 @Ayush7614 @ravikr126 @Saurabh4626  , Kindly assign me this issue using java under LGMSOC

**Comment by Arushi247** [comment]
@Ayush7614 @ravikr126 @Saurabh4626 I'd like to work on this issue in C language under HCSSoC. Please assign me this issue.

**Comment by siddhi-244** [comment]
I would like to try in python under lgmsoc

**Comment by ravikr126** [comment]
Start ur work @Arushi247

**Comment by harshita9621** [comment]
@Amit366 @ravikr126 @Ayush7614 @Saurabh4626 Kindly assign me this issue using python under LGMSOC

**Comment by hv65616** [comment]
Hello Community, I  Himanshu Verma, and i would like to work on this issue so kindly please assign me this issue.
Language in which I will write code is C++
