### ISSUE TITLE
[Code Chef] ICPC BALLONS Problem

### ISSUE THREAD

**Issue by rakesh419s** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1334]
# Aim

- Code chef's ICPC BALLONS Problem 
- [https://www.codechef.com/problems/BALLOON](url)

# Details

- What features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- .Python

**Comment by rakesh419s** [comment]
I want to solve the above Problem in Python, please assign me.

**Comment by kamleshjoshi8102** [comment]
@Saurabh4626 @ravikr126 @Ayush7614 Please Assign me this issue. I will solve it in C++.
LGM-SOC'21

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java as apart of LGM-SOC'21.
@ravikr126  @Ayush7614 Please assign it to me. Thankyou!!

**Comment by ravikr126** [comment]
Start your work @rakesh419s
