### ISSUE TITLE
Intersection of two sorted Linked lists

### ISSUE THREAD

**Issue by anusham14** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1352]
**Is your feature request related to a problem? Please describe.**
Intersection of two sorted Linked lists

**Describe the solution you'd like**
I want to work on this issue in C++.

Input:
L1 = 1->2->3->4->5
L2 = 1->3->5
Output: 1 3 5
Explanation: For the given first two linked list, 1, 3 and 5 are the elements in the intersection.

**Describe alternatives you've considered**

**Additional context**
Problem link : https://practice.geeksforgeeks.org/problems/intersection-of-two-sorted-linked-lists/1

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by anusham14** [comment]
@Amit366 @Ayush7614 @ravikr126 @Saurabh4626 Kindly assign me this issue for C++ ,under LGM'SOC

**Comment by Arushi247** [comment]
@Ayush7614 @ravikr126 @Saurabh4626 I'd like to work on this issue in C language under HCSSoC. Please assign me this issue.

**Comment by ravikr126** [comment]
This is already in repository @anusham14
