### ISSUE TITLE
"Optimal Xor Set" problem in CodeChef (June Challenge 2021).

### ISSUE THREAD

**Issue by Mugdha-Hazra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1362]
### Aim
I want to add the code for the "Optimal Xor Set" problem in CodeChef (June Challenge 2021).

### Details
Problem name: Optimal Xor Set
Problem Code: OPTSET
Problem link: https://www.codechef.com/JUNE21C/problems/OPTSET

Please assign me this issue
LGM-SOC Participant

### Programming language

C++
- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

Hello @prudhvirajstark @cmulay @VinayakMohite4040 @shantamsultania @Sumanth2905 sir, I think this is an important question and this should definitely be added in the Daily-Code-DS-Algo-Practice and I will start working on it as soon as I get assigned!! as I am a part of the LGM-SOC'21 participant, so I would like to implement this in c++.

**Comment by Amit366** [comment]
This is already solved
