### ISSUE TITLE
Merge Sort on Linked List [GFG]

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1365]
# Aim

- Will be adding solution for **[Sort the given linked list using Merge Sort.](https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1)**

# Details

- Topic - _Linked List._
- Difficulty level - _Medium_
> Problem Statement -

- Given Pointer/Reference to the head of the linked list, the task is to **_**Sort the given linked list using Merge Sort.**_** **Note**: If the length of linked list is odd, then the extra node should go in the first list while splitting.

> Please assign me this issue, LMG SoC'21 Participant.

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by Aryan-Srivastava** [comment]
@Saurabh4626 @ravikr126 @Ayush7614 Please Assign me this issue. I will be solving it in java.
LGM-SOC'21

Thank You

**Comment by nidhi3108** [comment]
Please Assign me this issue. I will be solving it in c++. I am participating in LGM-SOC.

**Comment by harshita9621** [comment]
Please Assign me this issue. I will be solving it in C. I am participating in LGM-SOC.

**Comment by ravikr126** [comment]
Already in repo @Aryan-Srivastava
