### ISSUE TITLE
Total Set Bits

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1368]
# Aim

- Will be adding solution for [Count total set bits.](https://practice.geeksforgeeks.org/problems/count-total-set-bits-1587115620/1)

# Details

- Topic - _Bit Manipulation._
- Difficulty Level - _Medium_.

> Problem Statement :- 

- You are given a number N. Find the total count of set bits for all numbers from 1 to N(both inclusive).

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

**Comment by Aryan-Srivastava** [comment]
@Saurabh4626 @ravikr126 @Ayush7614 Please Assign me this issue. I will be solving it in java.
LGM-SOC'21

Thank You.

**Comment by kumarshobhit** [comment]
I would like to contribute in C++
