### ISSUE TITLE
Triplets with zero sum problem

### ISSUE THREAD

**Issue by rajat1701** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1372]
**Is your feature request related to a problem? Please describe.**
Finding all triplets with zero sum

**Describe the solution you'd like**
Finding triplets in an array of distinct elements whose sum is zero in C++

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by rajat1701** [comment]
@Ayush7614 @Amit366 @Saurabh4626 @ravikr126 
Kindly assign me this issue, I will do it in C++.

**Comment by ravikr126** [comment]
You can work on it @rajat1701
