### ISSUE TITLE
Deleting Divisors (Problem D from codeforces round 726)

### ISSUE THREAD

**Issue by kumarshobhit** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1376]
**Is your feature request related to a problem? Please describe.**
I want to add the solution for the problem [link]https://codeforces.com/contest/1537/problem/D

Description:
Alice and Bob are playing a game.
They start with a positive integer n and take alternating turns doing operations on it. Each turn a player can subtract from n one of its divisors that isn't 11 or n. The player who cannot make a move on his/her turn loses. Alice always moves first.
Note that they subtract a divisor of the current number in each turn.
 find out who will win the game if both players play optimally.

**Describe the solution you'd like**
An analytical and logical solution consisting of 3 if-else statements based on the parity of the given number.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kumarshobhit** [comment]
@Ayush7614 @Amit366 @Saurabh4626 @ravikr126 kindly assign me this issue.

**Comment by siddhi-244** [comment]
Can I try in python ?

**Comment by ravikr126** [comment]
@kumarshobhit you can start your work

**Comment by siddhi-244** [comment]
@ravikr126 assign me in python

**Comment by ravikr126** [comment]
> @ravikr126 assign me in python

Raise a new issue I will assign you

**Comment by Ayush7614** [comment]
@ravikr126 don't say for raise new issue we were assigned this one

**Comment by ravikr126** [comment]
> @ravikr126 don't say for raise new issue we were assigned this one

But only one will get marks so how the second one will get marks??

**Comment by kumarshobhit** [comment]
@ravikr126  please don't close this issue as I am working on it.

**Comment by Pratik57** [comment]
Assign me in c under LGMSOC21 @ravikr126

**Comment by Pratik57** [comment]
May i submit this in Java also as no one asked for it @Amit366  @sameeksharl 
under LGMSOC'21
