### ISSUE TITLE
Strong Language CodeChef

### ISSUE THREAD

**Issue by sakinanomi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1387]
# Aim

Solution of problem Strong Language of codechef April long challenge
link to question:https://www.codechef.com/APRIL21C/problems/SSCRIPT

# Details

code of the question with proper comments and explanation

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by sakinanomi** [comment]
@ravikr126  please assign this issue to me under LGM SOC.

**Comment by Arushi247** [comment]
@Ayush7614 @ravikr126 I'd like to work on this issue in C language under HCSSoC. Please assign me this issue.

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in python as apart of LGM-SOC'21.
@Ayush7614 @ravikr126  Please assign it to me. Thankyou!!
