### ISSUE TITLE
Sort an array of 0’s, 1’s, and 2’s (Dutch National Flag Problem)

### ISSUE THREAD

**Issue by Harikrishnaa3131** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1392]
Hi, I want to solve this issue using C++
Please assign this issue to me under HCSSoC (Hack Club SRM Summer of Code) .
Looking forward to contribute !!

Question : Given an array of 0s, 1s and 2s sort it in linear time and using constant space.

Input : { 0, 1, 2, 2, 1, 0, 0, 2, 0, 1, 1, 0 }

Output : { 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2 }
 
@Ayush7614

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
Already in the repo
