### ISSUE TITLE
Is palindrome or not

### ISSUE THREAD

**Issue by thejaswin123** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1395]
# Aim

- To write a recursive function that tests if the array is a palindrome and returns a Boolean value.

![image](https://user-images.githubusercontent.com/52855622/123126655-31f82c80-d467-11eb-986e-4083252d8e4a.png)

# Details

-  I want to solve this problem using C++ 
    Please assign this issue to [me](https://github.com/thejaswin123) under HCSSoC (Hack Club SRM Summer of Code)  .
    @Ayush7614 
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by anishamurmu13** [comment]
I want to solve this problem using python.
I'm a participant of LGM-SOC21

**Comment by Srit20** [comment]
I want to solve this problem using java.
I'm a participant of LGM-SOC21

**Comment by 7saikat7** [comment]
please assign me i will solve it in c++

**Comment by thejaswin123** [comment]
Please assign this issue to me under HCSSoC (Hack Club SRM Summer of Code).
@Ayush7614

**Comment by SrihariTadala** [comment]
Im preparing for my  coding interviews and it would really help me if you assign this question to me 
Kindly assign me this issue under LGMSOC

**Comment by Amit366** [comment]
This issue is solved
