### ISSUE TITLE
Adding solution of Codeforces problem Lucky Sum of Digits

### ISSUE THREAD

**Issue by AKSHATNEMA** [Ayush7614/Daily-Coding-DS-ALGO-Practice#140]
With growing era of Competitive Programming and global challenges, people around the world are now more relying on Codeforces to give coding contest and practice skills. Codeforces provides brilliant interface to users with brilliant Questions which are asked in various interview rounds of company.

With so many questions on same side, people hang on between the mess of Questions and don't able to make advantage of quality of Questions on CF. 

Hence, I want to build a roadmap for beginners to start with these questions according to difficulty and will guide them to give answers of questions as well.

This is the starting Question for beginners, more questions will be added by creating issues and I will make seperate folder for Codeforces.

**Comment by AKSHATNEMA** [comment]
@Ayush7614 please assign this issue to me. I will work upon it as soon as LGM-SOC starts.

**Comment by AKSHATNEMA** [comment]
While working on this issue, I want some more members to contribute to this like those who can write solutions for CF Questions in Python and Java also. Interested ones can contact me on Discord with the name "Akshat Nema".

**Comment by Ayush7614** [comment]
Go Ahead @AKSHATNEMA

**Comment by AKSHATNEMA** [comment]
@Ayush7614 @Amit366 sir, this issue will require several PRs to be added on repository. Can I make many PRs for this same issue?

**Comment by AKSHATNEMA** [comment]
So, as suggested by our mentor @Amit366 , I am here by changing this issue from "Addition of Codeforces roadmap and Questions" to "Add solution to problem Lucky Sum of Digits". And will add more problems to this repository by creating issues.
