### ISSUE TITLE
Subarray sum equals to k

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1403]
# Aim

Given an array of integers and an integer k, return the total number of continuous subarrays whose sum equals to k

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by harshita9621** [comment]
Can I work on this issue?

**Comment by Ananya-Misra** [comment]
@harshita9621 I created this issue so that it could be assigned to me.

**Comment by Ananya-Misra** [comment]
@ravikr126 Please Assign this issue to me under LGM-SOC'21.

**Comment by ravikr126** [comment]
Already in repository @Ananya-Misra
