### ISSUE TITLE
Chef and Dice Codechef

### ISSUE THREAD

**Issue by sakinanomi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1409]
# Aim

Solution of codechef problem Chef and Dice from April long challenge
Problem Code: SDICE
Link to problem: https://www.codechef.com/APRIL21C/problems/SDICE

# Details

Solution of the problem with proper comments.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by sakinanomi** [comment]
@ravikr126  Please assign this issue to me under LGM-SOC

**Comment by Pradeep45911** [comment]
@ravikr126 Please assign this issue to me under LGM-SOC'21

**Comment by ravikr126** [comment]
This question is already available@sakinanomi @Pradeep45911

**Comment by sakinanomi** [comment]
> This question is already available@sakinanomi @Pradeep45911

oh! Sorry
