### ISSUE TITLE
Bellman Ford's Algorithm

### ISSUE THREAD

**Issue by manognyaa** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1410]
**Is your feature request related to a problem? Please describe.**
Bellman Ford algorithm is a algorithm where in this will help us to code and it will find the shortest path from a vertex(root) to all other vertices of a weighted graph.

**Describe the solution you'd like**
I will be using C++ for this algorithm. sir, actually I used graph for this algorithm.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
Sir, please assign this to me, I would like to work on this @Ayush7614 sir.

**Comment by Srit20** [comment]
I want to solve this problem using java.
I'm a participant of LGM-SOC21

**Comment by harshita9621** [comment]
I want to solve this problem in C
