### ISSUE TITLE
Dijkstra algorithm

### ISSUE THREAD

**Issue by manognyaa** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1411]
**Is your feature request related to a problem? Please describe.**
How much difficult it is to find the shortest paths between nodes in a graph ? but, in there is a algorithm called
`Dijkstra Algorithm` it will help us to find the shortest paths between nodes in a graph.
there are some key notes we need to keep in mind
- All edges must have None-Negative weights.
- Graph must be connected.

**Describe the solution you'd like**
Sir, I will be using C++ for this graph.  

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
Sir, please assign this issue to me, I would like to work on this @Ayush7614 sir.

**Comment by Ayush7614** [comment]
Already in the repo
