### ISSUE TITLE
Best Time to Buy and Sell Stock - LeetCode

### ISSUE THREAD

**Issue by mrkc2303** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1418]
# Aim

Want to add a solution of "Best Time to Buy and Sell Stock".
Kindly assign me this problem. I would like to add my solution to this problem in C++ in an efficient approach.

# Details

You are given an array of prices where prices[i] is the price of a given stock on an ith day.
You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.
Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by mrkc2303** [comment]
@ravikr126  Please Assign this issue to me under LGM-SOC'21.

**Comment by Arushi247** [comment]
@Ayush7614 I'd like to add my solution in C language under HSSoC. Kindly assign me the issue.
