### ISSUE TITLE
Banker's Algorithm

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1421]
# Aim

I want to add banker's algorithm that is deadlock prevention algorithm.
@ravikr126  Please Assign this issue to me under LGM-SOC'21.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ravikr126** [comment]
This is available in repository@Ananya-Misra

**Comment by Ananya-Misra** [comment]
okay.
