### ISSUE TITLE
Median of two sorted arrays (LEETCODE HARD)

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1422]
# Aim

![image](https://user-images.githubusercontent.com/70848031/123249273-68d14f80-d506-11eb-83d1-b39550a28a08.png)

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ananya-Misra** [comment]
@ravikr126 Please Assign this issue to me under LGM-SOC'21.

**Comment by Pradeep45911** [comment]
@ravikr126 assign this issue to me under LGM-SOC'21

**Comment by shruti29s** [comment]
Can I work on this issue ?

**Comment by ravikr126** [comment]
> Can I work on this issue ?

if @Ananya-Misra not work on this issue then i will assign the next one .

**Comment by Ananya-Misra** [comment]
@ravikr126 I am working on this issue.

**Comment by siddhi-244** [comment]
Can I try in python?
