### ISSUE TITLE
The Wave Codechef June Cook-off problem

### ISSUE THREAD

**Issue by Karnika06** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1432]
Hello!!

I wish to work on The Wave problem from CodeChef June Cook-off 2021 Division 2.

**Problem Statement**
https://www.codechef.com/COOK130B/problems/WAV2/

I would like to use Java language for this issue.
Please assign this issue to me under LGM-SoC'21.

**Comment by manuvarghese0603** [comment]
I would like to solve it in c++.
Please assign this issue to me under LGM-SoC'21.
