### ISSUE TITLE
split the linked list 

### ISSUE THREAD

**Issue by manognyaa** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1435]
**Is your feature request related to a problem? Please describe.**
my aim is : to divide or split the linked list into two parts sir.
`note`
as we all know,
If it's number of nodes in the linked list is even(2n) then both the lists contains n nodes.
If the original list contains odd number of nodes(2n+1) then 1st list contains n+1 nodes and 2nd contains n nodes.

**Describe the solution you'd like**
I will be using c++ sir and it will come under linked list folder sir.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
please assign this issue to me sir, I would like to work on this @Ayush7614  sir.

**Comment by 7saikat7** [comment]
I am new to c++ ds/algo though i would like to try please assign me ! and these are also be counted as a contribution right ?
