### ISSUE TITLE
"XOR Folding" Problem of Codechef

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1439]
# Aim

I want to add the code for "XOR Folding" problem in codechef (June Cook-Off 2021)

# Details

Problem name : XOR Folding
Problem Code : XORFOLD
Problem link : https://www.codechef.com/COOK130C/problems/XORFOLD

Please assign me this issue
LGM-SOC Participant

Programming language
C++

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Khushi-agarwal** [comment]
I would like to add it in java.
Please assign it to me under lgm-soc.

**Comment by Khushi-agarwal** [comment]
@ravikr126 is it assigned to me or not?

**Comment by Amit366** [comment]
@Khushi-agarwal u can go ahead
