### ISSUE TITLE
Impartial Offerings Solution

### ISSUE THREAD

**Issue by sakinanomi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1448]
Solution to problem Impartial Offerings  asked in Code Jam to I/O for Women 2021
link to problem: https://codingcompetitions.withgoogle.com/codejamio/round/00000000004360f2/0000000000777098

# Details
I think including solutions of problems asked in code jam and like can be helpful for everyone searching for solution so I want to add Solution to the above mentioned problem.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by sakinanomi** [comment]
@ravikr126 please assign this issue to me under LGM SOC

**Comment by ravikr126** [comment]
Start your work@sakinanomi

**Comment by sakinanomi** [comment]
@ravikr126  Should I make a new directory for Code Jam to I/O or add the file in Miscellaneous directory??

**Comment by ravikr126** [comment]
Add new directory for codejam @sakinanomi

**Comment by sakinanomi** [comment]
ohk!
