### ISSUE TITLE
0/1 Knapsack problem

### ISSUE THREAD

**Issue by Sakshi1007** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1455]
# 0/1 Knapsack Problem

- I will add a very interesting problem of 0/1 knapsack problem.

# Details

- It is a problem that will follow Dynamic Programming approach. There will be some weights and respected value. We will try to find max value with less weight.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sakshi1007** [comment]
@Ayush7614 plz assign this issue to me.

**Comment by harshita9621** [comment]
@Ayush7614 Can I work on this issue.

**Comment by Sakshi1007** [comment]
@Ayush7614 plz assign this to me

**Comment by priyanshi5** [comment]
@Ayush7614  Please assign this task to me under LGM-SOC'21. I will implement using C++.

**Comment by SrihariTadala** [comment]
Im preparing for my coding interviews and it would really help me if you assign this question to me
Kindly assign me this 
I have immense intrest  in coding

**Comment by Sakshi1007** [comment]
Assign this to me under LGM SOC'21

**Comment by Sakshi1007** [comment]
@Ayush7614 review my PR

**Comment by Srit20** [comment]
Please assign me I will do this in JAVA.

**Comment by Ashu-1309** [comment]
@Ayush7614 please assign me under LGM-Soc 21. I want to do it in python,
