### ISSUE TITLE
Police and Thieves in c++

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1463]
# Aim
create a function catch thieves() that take n, k, and arr[ ] as input parameters and returns the maximum number of thieves that can be caught by the police. 
# Details
Given an array of size n such that each element contains either a 'P' for a policeman or a 'T' for a thief. Find the maximum number of thieves that can be caught by the police. 
Keep in mind the following conditions :

1. Each policeman can catch only one thief.
2. A policeman cannot catch a thief who is more than K units away from him.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

> This is one of the famous Microsoft Interview Question [View Question](https://practice.geeksforgeeks.org/problems/e47329920b4e75869ea7b0e9b7c59ea145ccc22c/1)
> GeeksforGeeks Medium level question
Topic: Greedy

**Comment by hoopinwhoopin** [comment]
can i get this assigned
