### ISSUE TITLE
Maximum XOR of Two Array

### ISSUE THREAD

**Issue by neha030** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1474]
INPUT/OUTPUT
 Enter the vector size
 6
 Enter the elements in the vector
 3 10 5 25 2 8
 The Maximum XOR of two numbers in the array/vector is : 28

 I am a LGM-SOC Participant and want to provide the C++ code for the above Program in the Data Structure folder.
Please assign me this issue.

**Comment by Rounak-chauhan** [comment]
INPUT/OUTPUT
Enter the Arraylist size
6
Enter the elements in the Arraylist
3 10 5 25 2 8
The Maximum XOR of two numbers in the array/ArrayList is : 28
I am LGM_SOC participant and want to provide java code for this program please assign me this issue

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in python as apart of LGM-SOC'21.
@Ayush7614 @Amit366 Please assign it to me. Thankyou!!
