### ISSUE TITLE
Sum replacement in binary tree

### ISSUE THREAD

**Issue by Palak2801** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1481]
Replace each node in binary tree with the sum of its right and left subtree 
Example,

<img width="127" alt="ex" src="https://user-images.githubusercontent.com/85724197/123513582-91467e80-d6ab-11eb-9a5f-c5d49946a909.PNG">

**Describe the solution you'd like**
Implementation using C++

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Palak2801** [comment]
@Ayush7614 @Amit366 @ravikr126 @Saurabh4626 , Kindly assign me this issue under LGMSOC using C++

**Comment by SrihariTadala** [comment]
Im preparing for my internships and it would really help me if you assign this question to me 
Kindly assign me this issue under LGMSOC

**Comment by SrihariTadala** [comment]
Im preparing for my coding interviews and it would really help me if you assign this question to me
Kindly assign me this 
I have immense intrest  in coding
