### ISSUE TITLE
Forming a Magic Square (Hackerrank)

### ISSUE THREAD

**Issue by Karnika06** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1485]
I would like to add the solution to this problem from Hackerrank.
Link to the problem is https://www.hackerrank.com/challenges/magic-square-forming/problem.

I would like to add my solution to this problem in Java language.
Please assign this issue to me under LGM-SoC'21.

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by priyanshi5** [comment]
@Ayush7614 Please assign it to me under LGM-SOC'21, I will implement it in C++

**Comment by hoopinwhoopin** [comment]
please assign it to me under LGM-SOC21 , in java
