### ISSUE TITLE
HTML Tags (Codechef LunchTime)

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1490]
# Aim
![image](https://user-images.githubusercontent.com/70848031/123519630-2fe1d800-d6ca-11eb-824f-7c635e35f714.png)
@ravikr126 Please assign this issue to me.

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by rajeshkumar2024** [comment]
@ravikr126 i want to add solution of this in Java under LGMSOC'21. Please assign me this.
