### ISSUE TITLE
False Numbers(Codechef Lunchtime)

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1491]
# Aim

![image](https://user-images.githubusercontent.com/70848031/123519707-94049c00-d6ca-11eb-97ca-c43b2dbd791a.png)
@ravikr126 Please assign this issue to me.

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Palak2801** [comment]
@ravikr126 , Kindly assign me this issue using C++
