### ISSUE TITLE
Get_Maximum_Maze_Paths

### ISSUE THREAD

**Issue by HitainKakkar** [Ayush7614/Daily-Coding-DS-ALGO-Practice#150]
Greetings sir/Mam,
I would like to contribute the code for this issue in Java.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding letsgrowmore.in/soc/21

I have made a PR for the same.
Kindly assign this issue!!

Regards,
Hitain Kakkar

**Comment by Ayush7614** [comment]
@HitainKakkar go Ahead

**Comment by archismansaha** [comment]
May I add C++ solution of this?

**Comment by HitainKakkar** [comment]
I have been trying to push my PR from last 2 days but when I push the code nothing happens.
I have tried to search on google but could not find the solution!!
kindly Help!!

**Comment by HitainKakkar** [comment]
![image](https://user-images.githubusercontent.com/64975064/121485046-73abc080-c9ed-11eb-9ba8-b5eb39029257.png)
