### ISSUE TITLE
 Group Anagrams (Leetcode Medium)

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1508]
# Aim

![Screenshot 2021-06-27 130543](https://user-images.githubusercontent.com/75210337/123536611-01571200-d749-11eb-9107-63da055dd6fe.png)

# Details

- I would like to solve this question in C++ under LGMSOC'21.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Please assign this issue to me under LGMSOC'21 .

**Comment by rakesh419s** [comment]
please assign me in python

**Comment by Karnika06** [comment]
Please assign this problem to me under LGM-SoC'21 in JAVA language.

**Comment by hoopinwhoopin** [comment]
please assign me this problem in c++
