### ISSUE TITLE
Total Correct Submissions  (Codechef Starters)

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1510]
# Aim
![image](https://user-images.githubusercontent.com/70848031/123545351-282b3d80-d775-11eb-905d-db43e0e43d0b.png)
@ravikr126 Please asign this to me.

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ananya-Misra** [comment]
@ravikr126 Please assign this issue to me.

**Comment by Ananya-Misra** [comment]
@Amit366 Please assign this issue to me.

**Comment by manuvarghese0603** [comment]
I would like to solve it in C++ .
Please assign me this issue under lgm-soc
