### ISSUE TITLE
Sleep Cycle (Codechef Starters)

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1511]
![image](https://user-images.githubusercontent.com/70848031/123545300-f9ad6280-d774-11eb-846d-bd10852d390f.png)
@ravikr126 Please assign this issue to me.
- What is the objective of the Script

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by manuvarghese0603** [comment]
I would like to solve it in C++ too.
Please assign me this issue under lgm-soc
