### ISSUE TITLE
Chess Match (Codechef Starters)

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1512]
![image](https://user-images.githubusercontent.com/70848031/123545380-51e46480-d775-11eb-9117-71737e33b83b.png)
@ravikr126 Please aaign this issue to me.

- What is the objective of the Script

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ananya-Misra** [comment]
@ravikr126 Please assign this issue to me.

**Comment by Ananya-Misra** [comment]
@Amit366 Please assign this issue to me.

**Comment by manuvarghese0603** [comment]
I would like to solve it in C++ .
Please assign me this issue under lgm-soc
