### ISSUE TITLE
Total Correct Submission from code chef

### ISSUE THREAD

**Issue by Khushi-agarwal** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1514]
**Is your feature request related to a problem? Please describe.**

I would like to add the solution to the problem total correct submission from code chef.
Link to the problem- https://www.codechef.com/START5C/problems/TOTCRT

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Khushi-agarwal** [comment]
@ravikr126 please assign me this issue.

**Comment by manuvarghese0603** [comment]
I would like to solve it in C++ .
Please assign me this issue under lgm-soc

**Comment by Khushi-agarwal** [comment]
@Amit366 kindly assign me this issue.

**Comment by Amit366** [comment]
@Khushi-agarwal this issue is already opened #1510
