### ISSUE TITLE
call_by_value

### ISSUE THREAD

**Issue by HitainKakkar** [Ayush7614/Daily-Coding-DS-ALGO-Practice#152]
Greetings sir/Mam,
I would like to contribute the code for this issue in c++/cpp.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding letsgrowmore.in/soc/21

I have made a PR for the same.
Kindly assign this issue!!

Regards,
Hitain Kakkar

**Comment by Ayush7614** [comment]
@HitainKakkar go Ahead
