### ISSUE TITLE
Flappy Bird (CodeChef June Starters)

### ISSUE THREAD

**Issue by Karnika06** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1520]
This issue is from CodeChef Starters June 2021.
I wish to work on this issue in Java language.

**Problem statement**
https://www.codechef.com/START5C/problems/FLAPPYBD/

Please assign this issue to me under LGM-SoC'21.

**Comment by Ayan-thecodeking** [comment]
i want to work on this issue under c++ language 
please assign me @Amit366
