### ISSUE TITLE
Solution of Reverse Integer (Leetcode) in Python under LGMSOC'21.

### ISSUE THREAD

**Issue by rajeshkumar2024** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1539]
# Aim

- Want to add Solution of Reverse Integer (Leetcode) in Python under LGMSOC'21.

# Details

- Problem link - https://leetcode.com/problems/reverse-integer/

### Language used - Python 

@Ayush7614 @ravikr126 please assign me this.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

**Comment by SrihariTadala** [comment]
Im preparing for my internships and it would really help me if you assign this question to me 
Kindly assign me this issue under LGMSOC

**Comment by Amit366** [comment]
@rajeshkumar2024 and @SrihariTadala first finish ur pending issues

**Comment by rajeshkumar2024** [comment]
@Amit366 I have raised a pull request for all my previous task. Please assign me this issue.

**Comment by sonamgupta136** [comment]
@Amit366 please assign me this under LGMSOC'21

**Comment by rajeshkumar2024** [comment]
@Ayush7614 @ravikr126 @Amit366 please assign me this issue.
