### ISSUE TITLE
Solution of Multiply Strings (Leetcode) in python under LGMSOC'21.

### ISSUE THREAD

**Issue by rajeshkumar2024** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1540]
# Aim

- Want to add solution of Multiply Strings in python under LGMSOC'21.

# Details

- Problem link - https://leetcode.com/problems/multiply-strings/

### Language used - Python

@Ayush7614 @ravikr126 please assign me this issue.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

**Comment by SrihariTadala** [comment]
Kindly assign this issue to me

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java as apart of LGM-SOC'21.
@Ayush7614 Please assign it to me. Thankyou!!

**Comment by rajeshkumar2024** [comment]
@Ayush7614 @ravikr126 @Amit366 please assign me this issue.
