### ISSUE TITLE
Solution to Zero Problem - GFG Coding Challenge

### ISSUE THREAD

**Issue by pranjay-poddar** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1542]
Solution to the Zero Problem - GFG Coding Challenge

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

Please assign this task to me.

**Comment by Ayan-thecodeking** [comment]
i want to work on this issue under java language 
please assign me 
@Amit366
