### ISSUE TITLE
Solution to Total Correct Submissions

### ISSUE THREAD

**Issue by nagasaisriya** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1545]
**Is your feature request related to a problem? Please describe.**
I would like to add the solution to *Total Correct Submissions* from code chef
Link to the problem: https://www.codechef.com/START5C/problems/TOTCRT

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by nagasaisriya** [comment]
Hey @Amit366 , I've made a pr. Do check it out and please add LGMSOC and corresponding level labels under this issue.
 Thank you :)

**Comment by Amit366** [comment]
@nagasaisriya cpp is already done . Can u do in any other language??

**Comment by nagasaisriya** [comment]
> @nagasaisriya cpp is already done . Can u do in any other language??

I'm sorry, But I was assigned for cpp at first.

**Comment by Amit366** [comment]
Ok no problem
