### ISSUE TITLE
The Celebrity Problem ( GFG Medium)

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1546]
# Aim
![Screenshot 2021-06-28 021327](https://user-images.githubusercontent.com/75210337/123558935-b83da700-d7b6-11eb-9a2f-04b0ddd79e8b.png)

## Details
I would like to solve this question in C++ under LGMSOC'21.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Please assign this issue to me under LGMSOC'21 .

**Comment by Sanskriti2401** [comment]
@ravikr126 @Ayush7614 @Saurabh4626 Please assign this issue to me under LGMSOC'21 .

**Comment by Palak2801** [comment]
@Amit366 @Ayush7614 @ravikr126 I want to implement the same using C under LGM-SOC'21, kindly assign me this issue
