### ISSUE TITLE
Solution of Check if Two String Arrays are equivalent (Leetcode) in Java under LGMSOC'21.

### ISSUE THREAD

**Issue by rajeshkumar2024** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1548]
# Aim

- Want to add Solution of Check if Two String Arrays are equivalent (Leetcode) in Java under LGMSOC'21.

# Details

- Problem link - https://leetcode.com/problems/check-if-two-string-arrays-are-equivalent/

### Language used - Java

@Ayush7614 @ravikr126 please assign me this.

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by Rounak-chauhan** [comment]
please assign me this issue i will like to do this  in java language
@Ayush7614 @ravikr126

**Comment by Rounak-chauhan** [comment]
@Amit366 sir in pull request of #1780 i had commit both the codes of the issue assigned to me please merge it and i also attached the output of the following

**Comment by rajeshkumar2024** [comment]
@Amit366 please assign me this issue.

**Comment by Rounak-chauhan** [comment]
@Amit366  sir please review my PR
