### ISSUE TITLE
Trapping Rain Water - LeetCode (Hard)

### ISSUE THREAD

**Issue by mrkc2303** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1550]
# Aim

Want to add a solution of "Trapping Rain Water"
Kindly assign me this problem. I would like to add my solution to this problem in C++ in an easy and efficient way.
Link to the problem: https://leetcode.com/problems/trapping-rain-water/

# Details

Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

Example 1:
Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]
Output: 6

Example 2:
Input: height = [4,2,0,3,2,5]
Output: 9

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by mrkc2303** [comment]
Please assign me this issue under LGMSOC'21

**Comment by Rounak-chauhan** [comment]
please assign me this issue under LGMSOC'21 i will like to do this in java with minimum time complexity @Ayush7614 @Amit366
