### ISSUE TITLE
Level order insertion in binary tree

### ISSUE THREAD

**Issue by Soumyadeep-rick** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1552]
A menu-driven program for Level order insertion in a binary tree and for displaying iterative preorder, inorder, postorder traversals, and level-order traversal. Also, for displaying the no. of nodes and height of the tree.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by SrihariTadala** [comment]
Im preparing for my coding interviews and it would really help me if you assign this question to me
Kindly assign me this 
I have immense intrest  in coding
