### ISSUE TITLE
Sieve of Eratorthenes Algorithm problem-GFG

### ISSUE THREAD

**Issue by Suryadipsinh** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1560]
Problem : Find number of prime numbers less than given number using Sieve of Eratorthenes Algorithm.
Source: GFG

Language : C 

I would like to add more efficient solution using Sieve of Eratorthenes Algorithm in C++ language.

Thank you.

**Comment by SrihariTadala** [comment]
Im preparing for my coding interviews and it would really help me if you assign this question to me
Kindly assign me this 
I have immense interest  in codin

**Comment by Ayush7614** [comment]
> Im preparing for my coding interviews and it would really help me if you assign this question to me
> Kindly assign me this
> I have immense interest in codin

You can do in which langauge

**Comment by viki4545** [comment]
Hey @Ayush7614 can i solve this issue using java would you like to assign me

**Comment by SrihariTadala** [comment]
I would like to do in Java

**Comment by siddhi-244** [comment]
Can I try in python ?
