### ISSUE TITLE
Solution for Combination Sum of LeetCode

### ISSUE THREAD

**Issue by Isha307** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1562]
# Aim

Solution for Combination Sum of LeetCode

# Details

Solution for Combination Sum of LeetCode

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by hoopinwhoopin** [comment]
### **AIM**
Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target. You may return the combinations in any order.

The same number may be chosen from candidates an unlimited number of times. Two combinations are unique if the frequency of at least one of the chosen numbers is different.

It is guaranteed that the number of unique combinations that sum up to target is less than 150 combinations for the given input
### **EXAMPLE**
Input: candidates = [2,3,6,7], target = 7
Output: [[2,2,3],[7]]
Explanation:
2 and 3 are candidates, and 2 + 2 + 3 = 7. Note that 2 can be used multiple times.
7 is a candidate, and 7 = 7.
These are the only two combinations.
### **CONTSTRAINTS**
1 <= candidates.length <= 30
1 <= candidates[i] <= 200
All elements of candidates are distinct.
1 <= target <= 500
 Can i please work on this issue @Isha307

**Comment by hoopinwhoopin** [comment]
i would like to work on this issue under LGMSOC-21 (C++), please assign it to me @Isha307
