### ISSUE TITLE
Codechef's Total Correct Submissions 

### ISSUE THREAD

**Issue by rakesh419s** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1566]
# Aim

Codechef's Total Correct Submissions  a Question from CodeChef contest which is completed 1day ago
https://www.codechef.com/START5B/problems/TOTCRT

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- . Python

**Comment by rakesh419s** [comment]
please assign me in Python , LGM-SOC'21

**Comment by Amit366** [comment]
@rakesh419s this is already done
