### ISSUE TITLE
Chess Match

### ISSUE THREAD

**Issue by rakesh419s** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1567]
# Aim

Chess Match at https://www.codechef.com/START5B/problems/BLITZ3_2

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- . Python

**Comment by rakesh419s** [comment]
please assign me in python

**Comment by breeze37** [comment]
Please assign me this is C

**Comment by AastikSharma05** [comment]
please assign me this in  C++

**Comment by Amit366** [comment]
This issue is already solved
