### ISSUE TITLE
Codechef Chess Match in C++

### ISSUE THREAD

**Issue by tanvi355** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1568]
Problem link : https://www.codechef.com/START5C/problems/BLITZ3_2

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

Additional context: LGM-SoC'21 participant

**Comment by tanvi355** [comment]
Please assign this to me @ravikr126 @Saurabh4626

**Comment by Subhradeep10** [comment]
@tanvi355 Can I work on it?

**Comment by Amit366** [comment]
This issue is already solved
