### ISSUE TITLE
Cyclic Quadrilateral

### ISSUE THREAD

**Issue by rakesh419s** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1569]
# Aim

-Cyclic Quadrilateral at https://www.codechef.com/START5A/problems/CYCLICQD

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- . Python

**Comment by rakesh419s** [comment]
please assign me in python

**Comment by AastikSharma05** [comment]
@Ayush7614 @ravikr126  please assign me in C++

**Comment by breeze37** [comment]
@Ayush7614 @ravikr126 please assign me this in C
