### ISSUE TITLE
Add 1 to a number represented as linked list.

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1575]
# Aim

- will be adding question in GFG folder [Add 1 to a number represented as linked list.](https://practice.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1)

# Details

> Problem Statement :-

- A number N is represented in Linked List such that each digit corresponds to a node in linked list. You need to add 1 to it.

> Test Cases -

Input:
LinkedList: 4->5->6
Output: 457 

Input:
LinkedList: 1->2->3
Output: 124 

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

> Please assign me this issue,@Ayush7614 @Amit366 @ravikr126 @Saurabh4626 LGM SoC'21 participant

**Comment by Arushi247** [comment]
@Ayush7614 I'd like to work on this issue in C language under HCSSoC. Kindly assign me this issue.

**Comment by SrihariTadala** [comment]
Im preparing for my  coding interviews and it would really help me if you assign this question to me 
Kindly assign me this issue under LGMSOC
