### ISSUE TITLE
Wave Array

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1577]
# Aim

- will be adding wave array question in GFG folder.

# Details

> Problem Statement :-

- Given a sorted array arr[] of distinct integers. Sort the array into a wave-like array and return it. In other words, arrange the elements into a sequence such that a1 >= a2 <= a3 >= a4 <= a5..... (considering the increasing lexicographical order).

> TestCases :-

- Input:
n = 5
arr[] = {1,2,3,4,5}
Output: 2 1 4 3 5
Explanation: Array elements after 
sorting it in wave form are 
2 1 4 3 5.

- Input:
n = 6
arr[] = {2,4,7,8,9,10}
Output: 4 2 8 7 10 9
Explanation: Array elements after 
sorting it in wave form are 
4 2 8 7 10 9.

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

> Please assign me this issue,@Ayush7614 @Amit366 @ravikr126 @Saurabh4626 LGM SoC'21 participant

**Comment by Arushi247** [comment]
@Ayush7614 I'd like to work on this issue in C language under HCSSoC. Please assign me this issue.

**Comment by hoopinwhoopin** [comment]
can you assign this to me in c++

**Comment by hoopinwhoopin** [comment]
https://github.com/hoopinwhoopin/Wavearray.git  @Amit366 done
