### ISSUE TITLE
Bitonic Point.

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1578]
# Aim

- Will be adding solution for Bitonic Point problem  in GFG folder.

# Details

> Problem Statement :-

- Given an array arr of n elements which is first increasing and then may be decreasing, find the maximum element in the array.
Note: If the array is increasing then just print then last element will be the maximum value.

> TestCases :-

- Input: 
n = 9
arr[] = {1,15,25,45,42,21,17,12,11}
Output: 45
Explanation: Maximum element is 45.

- Input: 
n = 5
arr[] = {1, 45, 47, 50, 5}
Output: 50
Explanation: Maximum element is 50.

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

> Please assign me this issue,@Ayush7614 @Amit366 @ravikr126 @Saurabh4626 LGM SoC'21 participant

**Comment by manuvarghese0603** [comment]
I would like to solve it in C++ .
Please assign me this issue under lgm-soc
