### ISSUE TITLE
Flattening a Linked List 

### ISSUE THREAD

**Issue by 19bce502** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1593]
AIM 
Given a Linked List of size N, where every node represents a sub-linked-list and contains two pointers:
(i) a next pointer to the next node,
(ii) a bottom pointer to a linked list where this node is head.
Each of the sub-linked-list is in sorted order.
Flatten the Link List such that all the nodes appear in a single level while maintaining the sorted order. 
Note: The flattened list will be printed using the bottom pointer instead of next pointer.

Please Assign Me Under LGMSOC . I will be doing in C++ language

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Aryan-Srivastava** [comment]
I guess this one is already present in the GFG folder.

**Comment by SrihariTadala** [comment]
Kindly assign me this
I have immense intersect in coding
