### ISSUE TITLE
number of nodes and connected Components in an undirected graph 

### ISSUE THREAD

**Issue by Surajvatsya** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1599]
# Aim

To find out the number of nodes and components in an undirected graph 
# Details

Given an undirected graph, find out the number of nodes and components in an undirected graph.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
@Ayush7614 bhiya, kindly assign me this issue to work on, in c++.

**Comment by SrihariTadala** [comment]
Im preparing for my coding interviews and it would really help me if you assign this question to me
Kindly assign me this 
I have immense intrest  in coding

**Comment by Palak2801** [comment]
@Amit366 @Ayush7614,  I want implement the same using C under LGM-SOC'21, Kindly assign me this issue
