### ISSUE TITLE
kadane's algorithm

### ISSUE THREAD

**Issue by Rounak-chauhan** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1601]
# Aim

- Given nums = [-2, 1, -3, 4].
Compare all elements with the cumulative sum stored in the previous index.

Since -2 < 0, value -2 doesn't contribute to the sum. Thus, ignore it and proceed to the next index.
Since 1 > 0, value 1 does contribute. Hence, compute -3+1 = -2 and store it in index 2.
The result vector is so far: [-2, 1, -2, 4]. Last element to evaluate is 4.
Since -2 < 0, -2 does not contribute positively to the sum. Thus, ignore it.
Having checked all elements, the final result vector is: [-2, 1, -2, 4].
The maximum subarray is max(num)=4.

# Details

- i will like to do this in java language please assign me this under LGMSOC'21

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by Rounak-chauhan** [comment]
please assign me this under java under LGMSOC'21

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in C++ as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by Arushi247** [comment]
@Ayush7614 I'd like to work on this issue in C language under HCSSoC. Kindly assign me this issue.

**Comment by sonamgupta136** [comment]
Please assign me this issue in python language under LGMSOC'21 @Ayush7614

**Comment by Amit366** [comment]
This is already done
