### ISSUE TITLE
Remove Duplicate Element from Unsorted Linked List

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1603]
# Aim

- Solution for remove duplicate element from sorted linked list is already in the repository, hence

- will be adding solution for Remove Duplicate Element from Unsorted Linked List.

# Details

- Given an unsorted linked list of N nodes. The task is to remove duplicate elements from this unsorted Linked List. When a value appears in multiple nodes, the node which appeared first should be kept, all others duplicates are to be removed.

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

> Please assign me this issue,@Ayush7614 @Amit366 @ravikr126 @Saurabh4626

**Comment by Arushi247** [comment]
@Ayush7614 I'd like to work on this issue in C language under HCSSoC. Kindly assign me this issue.
