### ISSUE TITLE
Maximum for every window of size K .

### ISSUE THREAD

**Issue by puneetkaur2929** [Ayush7614/Daily-Coding-DS-ALGO-Practice#161]
Maximum in each window of size K

**Problem statement**
find the maximum for each and every contiguous subarray of size k
**Example:**
Given : Array a[]={2,5,1,8,3} & K (i.e. Window Size)=2
Output= 5 5 8 8 

Hey @Ayush7614  I would like to solve this issue using sliding window technique + Deque.

Language : I am interested to work in C++.

please assign this issue to me under LGM-SOC 21.

**Comment by Ayush7614** [comment]
Go Ahead @puneetkaur2929
