### ISSUE TITLE
Rotate array by K(medium) LeetCode

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1615]
# Aim

- will be adding solution for [Rotate array by k](https://leetcode.com/problems/rotate-array/) in leetcode folder.

# Details

> Problem Statement -

- Given an array, rotate the array to the right by k steps, where k is non-negative.

> Test Case -

- Input: nums = [1,2,3,4,5,6,7], k = 3
Output: [5,6,7,1,2,3,4]
Explanation:
rotate 1 steps to the right: [7,1,2,3,4,5,6]
rotate 2 steps to the right: [6,7,1,2,3,4,5]
rotate 3 steps to the right: [5,6,7,1,2,3,4]

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

> Please assign me this issue,@Ayush7614 @Amit366 @ravikr126 @Saurabh4626

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in python as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by Rounak-chauhan** [comment]
i want to implement this in java as a part of LGM_SOC21
@Ayush7614 @Amit366  please assign it to me

**Comment by ravikr126** [comment]
Already raised issue
