### ISSUE TITLE
Majority Element(Leetcode)

### ISSUE THREAD

**Issue by codingninja11** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1618]
## AIM
I will be adding a question in the Leetcode folder [Majority Element](https://leetcode.com/problems/majority-element/).

## Details
> Problem Statement:-
-  Given an array nums of size n, return the majority element.
The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.

> Test Cases:-

Input: nums = [3,2,3]
Output: 3
Input: nums = [2,2,1,1,1,2,2]
Output: 2

Please Assign me this issue @Amit366  @ravikr126  @Saurabh4626 
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Arushi247** [comment]
@Ayush7614 I'd like to work on this issue in C language under HCSSoC. Kindly assign me this issue.

**Comment by sonamgupta136** [comment]
@ravikr126  I like to work in this issue in Python under LGMSOC21
