### ISSUE TITLE
Count occurrences of an element in a sorted array.

### ISSUE THREAD

**Issue by puneetkaur2929** [Ayush7614/Daily-Coding-DS-ALGO-Practice#162]
**Problem statement**
find the occurrences of an element in a sorted array.
**Example:**
Given : Array a[]={1,1,2,2,2,3,4,5} & element=2
Output= 3 

Hey @Ayush7614 I would like to solve this issue using Binary search.

Language : I am interested to work in C++.

please assign this issue to me under LGM-SOC 21.

**Comment by Ayush7614** [comment]
Go Ahead @puneetkaur2929

**Comment by prudhvirajstark** [comment]
Hello,
Good Morning

@puneetkaur2929 @Ayush7614 , Here is the pull request for the issue  #170. (Count occurrences of an element in a sorted array)
Hope this answer will be helpful or Have it as a reference.

Thanks,
Prudhvi raj

**Comment by kumarshobhit** [comment]
I am interested to code the problem in Java language.

**Comment by PadminiRai** [comment]
@Ayush7614 _I'd like to work on this issue , kindly assign this issue to me under LGM-SOC 21._

**Problem statement**
_Count occurrences of an element in a sorted array._

**Example:**
_Input :_  a[] = {1, 2, 2, 2, 2, 2, 3,},   x = 2
_Output :_ 5

**Language :** Python3.
**Approach :**  Improved Binary Search
**Time Complexity :** O(Logn)

**Comment by kumarshobhit** [comment]
I would like to contribute in java language
