### ISSUE TITLE
Permutations - LeetCode

### ISSUE THREAD

**Issue by mrkc2303** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1623]
# Aim

Want to add a solution of "Permutations"
Kindly assign me this problem. I would like to add my solution to this problem in C++ easily and efficiently using recursion.
Link to the problem: https://leetcode.com/problems/permutations/

# Details

Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.

Example 1:
Input: nums = [1,2,3]
Output: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]

Example 2:
Input: nums = [0,1]
Output: [[0,1],[1,0]]

Example 3:
Input: nums = [1]
Output: [[1]]

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by mrkc2303** [comment]
Please assign me this issue under LGM-SOC'21

**Comment by Rounak-chauhan** [comment]
i will like to contribute the solution in java using recursion please assign me underLGMSOC21
