### ISSUE TITLE
Merge K sorted Linked List (Leetcode: Hard)

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1628]
# Aim

To create a function that solves the problem
# Details

Given a pointer of Linked List Merge all of them in ascending order
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

## Leetcode Hard Difficulty Problem [Link](https://leetcode.com/problems/merge-k-sorted-lists/)
Approach used: using Priority Queue

**Comment by sonamgupta136** [comment]
Please assign me this issue under LGMSOC'21
I will like to contribute in Python language

**Comment by MDivakarPal** [comment]
I want to solve this problem using java. Kindly assign me this issue.
