### ISSUE TITLE
Implementation of stack in Python

### ISSUE THREAD

**Issue by pranita736** [Ayush7614/Daily-Coding-DS-ALGO-Practice#163]
# Aim

- Stack in Python

# Details

- Implementation of stack in Python

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

**Comment by pranita736** [comment]
@Ayush7614 Assign this to me under LGM-Soc'21

**Comment by Ayush7614** [comment]
Go Ahead @pranita736
