### ISSUE TITLE
Minimize the Heights II (GFG Medium)

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1633]
# Aim
![Screenshot 2021-07-01 164450](https://user-images.githubusercontent.com/75210337/124116590-c298c300-da8c-11eb-9b19-e3a94e281529.png)

# Details

I would like to solve Minimize the Heights II in C++ language under LGMSOC'21.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 @Amit366 Kindly assign me this issue under LGMSOC'21.

**Comment by apran-vs** [comment]
I would Like to solve this issue with python under LGMSoC'21.
