### ISSUE TITLE
Palindromic partitioning (HARD)(GFG)

### ISSUE THREAD

**Issue by Soham-Official** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1635]
I would like to add a Question Palindromic Partitioning 
problem link https://practice.geeksforgeeks.org/problems/palindromic-patitioning4845/1/?track=md-dp&batchId=144

Problem Statement
Given a string str, a partitioning of the string is a palindrome partitioning if every sub-string of the partition is a palindrome. Determine the fewest cuts needed for palindrome partitioning of given string.

Test case:
Example 1:
Input: str = "ababbbabbababa"
Output: 3
Explaination: After 3 partitioning substrings 
are "a", "babbbab", "b", "ababa".

Example 2:
Input: str = "aaabba"
Output: 1
Explaination: The substrings after 1
partitioning are "aa" and "abba".

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Soham-Official** [comment]
@ravikr126  @Amit366  Kindly assign me this issue under LGMSOC'21.

**Comment by sonamgupta136** [comment]
@ravikr126 @Amit366 please assign me this under LGMSOC'21.I will like to do this task in Python and c++ both
