### ISSUE TITLE
Reversing words in a String-leetcode

### ISSUE THREAD

**Issue by yellowberard** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1638]
AIM
Want to add solution the "Reversing words in  a String".
Kindly assign me this problem I want to add solution to this problem in C++.
Link To the problem:-https://leetcode.com/problems/reverse-words-in-a-string/

DETAILS
Given an input string s, reverse the order of the words.

A word is defined as a sequence of non-space characters. The words in s will be separated by at least one space.

Return a string of the words in reverse order concatenated by a single space.
Example 1:

Input: s = "the sky is blue"
Output: "blue is sky the"
Example 2:

Input: s = "  hello world  "
Output: "world hello"
Explanation: Your reversed string should not contain leading or trailing spaces.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by yellowberard** [comment]
Please assign me this issue under LGM-SOC'21

**Comment by sonamgupta136** [comment]
Kindly assign me this issue under LGMSOC'21

**Comment by 1218muskan** [comment]
I would like to code in Python. Kindly assign me this issue under LGM SoC'21

**Comment by Ayan-thecodeking** [comment]
i want to work on this issue under java language 
please assign me

**Comment by 889-dj** [comment]
i want to work on this issue under cpp please assign it to me @Amit366
