### ISSUE TITLE
Construct Binary Tree from Inorder and Postorder Traversal

### ISSUE THREAD

**Issue by Palak2801** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1646]
I want to give code for solution of this problem-
https://practice.geeksforgeeks.org/problems/tree-from-postorder-and-inorder/1

**Describe the solution you'd like**
Implementation using C++

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Palak2801** [comment]
@Ayush7614 @Amit366 @ravikr126 @Saurabh4626 . Kindly assign me this issue using C++

**Comment by ravikr126** [comment]
Duplicate issue

**Comment by Palak2801** [comment]
@ravikr126 Earlier issue was created to construct binary tree from preorder and inorder but I have created issue to construct binary tree from postorder and inorder

**Comment by Palak2801** [comment]
> Duplicate issue
@ravikr126 Earlier issue was created to construct binary tree from preorder and inorder but I have created issue to construct binary tree from postorder and inorder.
Could you please assign this issue to me
