### ISSUE TITLE
Rotate a Linked List _GFG 

### ISSUE THREAD

**Issue by Anshika-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1647]
**Question**
Given a singly linked list of size N. The task is to rotate the linked list counter-clockwise by k nodes, where k is a given positive integer smaller than or equal to length of the linked list.

Accuracy: 33.33% (Medium)

**Example 1:**

Input:
N = 5
value[] = {2, 4, 7, 8, 9}
k = 3
Output: 8 9 2 4 7
Explanation:
Rotate 1: 4 -> 7 -> 8 -> 9 -> 2
Rotate 2: 7 -> 8 -> 9 -> 2 -> 4
Rotate 3: 8 -> 9 -> 2 -> 4 -> 7

I would like to contribute in this under LGMSOC'21.

**Comment by sonamgupta136** [comment]
Please assign me this issue under LGMSOC'21.
I would like to solve this in c++

**Comment by drashtipatel2503** [comment]
Can I do this with python?
