### ISSUE TITLE
Allocate minimum number of pages to each student .

### ISSUE THREAD

**Issue by puneetkaur2929** [Ayush7614/Daily-Coding-DS-ALGO-Practice#165]
**Problem statement**
Allocate number of books such that maximum number of pages each student should read is minimized.
**Example:**
**Given** : N number of books, array A[N] where A[i] gives number of pages in ith book.  S number of students among those  books are to allocated.
N=4 A[]={20,34,12,27}
S=2
**Output**= 59 

Hey @Ayush7614 I would like to solve this issue using Binary search.

Language : I am interested to work in C++.

please assign this issue to me under LGM-SOC 21.

**Comment by Jagannath8** [comment]
Can I implement in Java? I'm a participant of LGM-SOC 21.
