### ISSUE TITLE
Job Sequencing Problem  

### ISSUE THREAD

**Issue by 19bce502** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1656]
AIM 
Given a set of N jobs where each job i has a deadline and profit associated to it. Each job takes 1 unit of time to complete and only one job can be scheduled at a time. We earn the profit if and only if the job is completed by its deadline. The task is to find the maximum profit and the number of jobs done.

Note: Jobs will be given in the form (Job id, Deadline, Profit) associated to that Job.

Please Assign me under LGMSOC'2021 . I will be doing in C++ Language.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by priyanshi5** [comment]
@Ayush7614 I would like to solve this issue in Python. Please assign me this under LGM-SOC'21

**Comment by sonamgupta136** [comment]
Please assign me this issue under LGMSOC'21.
I would like to solve in java.
