### ISSUE TITLE
Russian Peasant Multiplication algorithm 

### ISSUE THREAD

**Issue by Sumanth2905** [Ayush7614/Daily-Coding-DS-ALGO-Practice#168]
# Aim

- Implementation of Russian Peasant multiplication algorithm

# Details

- Multiplication of two numbers using bitwise operators

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Amit366** [comment]
@Sumanth2905 mention the language

**Comment by Sumanth2905** [comment]
@Amit366 Assign this to me in C++.

**Comment by Sriram-bb63** [comment]
I would like to solve this in python
