### ISSUE TITLE
Restructuring the repository

### ISSUE THREAD

**Issue by tanvi355** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1681]
**Is your feature request related to a problem? Please describe.**
Navigating through the repository is difficult due to repetitive codes to the same problem in one folder.

**Describe the solution you'd like**
Arranging the codes as:
CodeChef:
    |- C
    |- C++
    |- Java
    |-Python

Hackerrank:
    |- C
    |- C++
    |- Java
    |-Python
and so on for all the websites.

**Additional context**
LGM-SoC'21 participant

**Comment by tanvi355** [comment]
@Amit366

**Comment by AtrikGit6174** [comment]
As a participant and a fellow problem solver, I feel the Algorithms or Problem solving parts can be skipped being classified into Languages.
However, for HackerRank, if it is a language based problem, then it would help being organised into individual languages.

**Comment by tanvi355** [comment]
Hey @AtrikGit6174, I get your point but I already discussed this with the mentor before raising an issue. I thought of classifying the code into languages so that it will be easier for contributors to check before making issues and also for further maintaining the project. 
Let's please wait for the mentors and PA to respond.
Some classification is needed is what we both agree upon right?

**Comment by Amit366** [comment]
@tanvi355 it would be better if it is sorted according to language

**Comment by tanvi355** [comment]
> @tanvi355 it would be better if it is sorted according to language

Yes, so should I start working on this?

**Comment by Amit366** [comment]
Yes
