### ISSUE TITLE
Maximum Production(July Long Challenge)

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1685]
# Aim

![image](https://user-images.githubusercontent.com/70848031/124260907-d8ba8800-db4d-11eb-8717-f30c33dae2df.png)

@ravikr126 Please assign this issue to me

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Kaavya-Saxena** [comment]
please assign this issue to me i want to provide its answer in c++ @Amit366
