### ISSUE TITLE
XxOoRr (July Long Challenge)

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1687]
# Aim
![image](https://user-images.githubusercontent.com/70848031/124261180-20411400-db4e-11eb-8d27-18eff8791599.png)

@ravikr126 Please assign this issue to me

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by siddhi-244** [comment]
Can I try in c++ or python
