### ISSUE TITLE
Optimal Denomination (July Long Challenge)

### ISSUE THREAD

**Issue by Ananya-Misra** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1688]
# Aim

![image](https://user-images.githubusercontent.com/70848031/124261394-5c747480-db4e-11eb-8e4d-98e39738f0f2.png)
@ravikr126 Please assign this issue to me.

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Amit366** [comment]
@Ananya-Misra you cannot add solution to on going contest.
