### ISSUE TITLE
First index of a number in the array

### ISSUE THREAD

**Issue by siddhi-244** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1689]
Given an array of length N and an integer x, you need to find and return the first index of integer x present in the array. Return -1 if it is not present in the array.
First index means, the index of first occurrence of x in the input array.
Do this recursively. Indexing in the array starts from 0.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by siddhi-244** [comment]
Can I try in c++ under lgmsoc

**Comment by girija0707** [comment]
please assign this to me in python

**Comment by Himanshu-Shinde** [comment]
Assign to me i will code it using JAVA or C++ under LGMSOC

**Comment by Vidhi6340** [comment]
Please assign me this issue under LGMSOC'21. I would like to contribute the code in C.

**Comment by Amit366** [comment]
@Himanshu-Shinde try in Java

**Comment by Vidhi6340** [comment]
I have generated Pull Request which fixes this issue. Kindly review it @Amit366

**Comment by Vidhi6340** [comment]
@Amit366 I have created a new PR in which I have added the file in the proper folder and also test cases have been added. Please review it.
