### ISSUE TITLE
Want to add questions of Codechef and leetcode 

### ISSUE THREAD

**Issue by archismansaha** [Ayush7614/Daily-Coding-DS-ALGO-Practice#169]
# Aim

-I want to add questions from (vector recursion,oops,linkedlist)of leetcode(top 100 liked)and codechef(div 3) questions in C++

# Details

- What the features will your script have

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Amit366** [comment]
@archismansaha Can u elaborate which questions?? Like some program or interview questions

**Comment by archismansaha** [comment]
I want to add past Div 3 short and long contests questions from codechef and from leetcode top 100liked questions of array, recursion oops and linked list based questions

**Comment by Amit366** [comment]
@archismansaha u cannot add all the questions but u can add one by one . Since it is an open source so everyone should get a chance.

**Comment by archismansaha** [comment]
So May I add Questions Of codechef of April and May Long and short contests?? Will it be ok??

**Comment by Amit366** [comment]
@archismansaha  see u can create separate issues with a single question. And max we can assign 3 to 4 issues at a time.

**Comment by archismansaha** [comment]
Ok sir

**Comment by Ayush7614** [comment]
@archismansaha plss define your language in which language you can do question

**Comment by archismansaha** [comment]
I will do in C++

**Comment by archismansaha** [comment]
Actually as per I mentioned later I had created spereated issues with mentioning questions which has been assigned to me... Will you close this issue??
