### ISSUE TITLE
last index of number in an array

### ISSUE THREAD

**Issue by girija0707** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1690]
Given an array of length N and an integer x, you need to find and return the last index of integer x present in the array. Return -1 if it is not present in the array.
Last index means - if x is present multiple times in the array, return the index at which x comes last in the array.
You should start traversing your array from 0, not from (N - 1).
Do this recursively. Indexing in the array starts from 0.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by girija0707** [comment]
can I try this in c++

**Comment by siddhi-244** [comment]
Can I try in python

**Comment by Vidhi6340** [comment]
Please assign me this issue under LGM-soc21. I will like to contribute the code in C.

**Comment by zaydmughal** [comment]
can i try this in Java or c+?
