### ISSUE TITLE
Valid Sudoku (Leetcode)

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1698]
# Aim
![Screenshot 2021-07-02 173818](https://user-images.githubusercontent.com/75210337/124272524-7d43c680-db5c-11eb-83cc-a2dbf38822e2.png)

# Details

I would like to solve Valid Sudoku question in C++ language under LGMSOC'21.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Kindly assign me this issue under LGMSOC'21

**Comment by apran-vs** [comment]
I would like to work on this issue in Python under LGMSoC'21.
Please assign me.

**Comment by sonamgupta136** [comment]
Please assign me this issue under LGMSOC'21.
I will like to contribute in Java .
