### ISSUE TITLE
Double Ended Queue Implementation in C

### ISSUE THREAD

**Issue by radhikaaojha** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1699]
**Is your feature request related to a problem? Please describe.**
Double Ended Queue Implementation in C

**Describe the solution you'd like**
Using structure queue in C

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by radhikaaojha** [comment]
@ravikr126 @Ayush7614 @Amit366 Kidnly assign me this issue

**Comment by siddhi-244** [comment]
Can I try in c++

**Comment by goyal-Dushi** [comment]
Hey @ravikr126, I want to address the issue, please assign me possible.

**Comment by NidhiChaurasia** [comment]
Hello, @ravikr126 , Kindly assign me this issue as I can solve this in C .

**Comment by radhikaaojha** [comment]
> Hello, @ravikr126 , Kindly assign me this issue as I can solve this in C .

Hey! I am already doing it in C
