### ISSUE TITLE
Bug in a Data Structures program

### ISSUE THREAD

**Issue by pratyush-kr** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1700]
**Describe the bug**
The file 'Doubly-Linked-List.cpp' under folder 'Data Structures' contains array like indexing using maps but no where it updates the maps after Insertions or Deletions making the map useless after some operation

**To Reproduce**
1. Go to 'Data\ Structures/ Doubly-Linked-List.cpp 
2. Run the Program
3. Insert a few nodes linearly then print the lists and then again insert Nodes Randomly this time and print again.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Expected behavior**
It should be able to update the map after appropriate insertions and deletions.

**Comment by chicken-biryani** [comment]
Hey, @pratyush-kr 
1) Never start working on an issue till the time it has not been assigned to you.
2) I am closing this PR, don't touch the already existing code in the repositry.
Make a separate file and name it 'doubly - linked - list -2 ' or something like that. Okay?

**Comment by pratyush-kr** [comment]
okay assign me i will be making a new file

**Comment by pratyush-kr** [comment]
@chicken-biryani can you please do a review?
