### ISSUE TITLE
Reverse an Array Using Stack Data Structure

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1702]
# Aim

- I would like to add code in data structure folder.
# Details

-  I would like to add Reverse an Array Using Stack Data Structure in data structure folder.
- LGM-SOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Saurabh4626 @Amit-45 @Ayush7614 @ravikr126 Please Assign me this issue. I will solve it in C++.
LGM-SOC'21

Thank You

**Comment by ravikr126** [comment]
Already in repository please check first then raise issue
