### ISSUE TITLE
All Queue Operation using Array and Linked List Implementation

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1704]
# Aim

- I would like to add it in a Data Structure Folder.
# Details

- I would like to add all **Queue** Operations like Enqueue, Dequeue, Display etc. using Array and Linked List Implementation in a Single Code.
- LGM-SOC'21
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Saurabh4626 @Amit-45 @Ayush7614 @ravikr126 Please Assign me this issue. I will solve it in C++.
LGM-SOC'21

Thank You

**Comment by ravikr126** [comment]
Already raised issue .First check then raise
