### ISSUE TITLE
All Deque operation with Input Restricted and Output Restricted

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1705]
# Aim

- I would like to add it in Data Structure Folder.

# Details

- I would like to add all Deque Operation with both types in a single code.
 1. Input Restricted.
 2. Output Restricted
- LGM-SOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Saurabh4626 @Amit-45 @Ayush7614 @ravikr126 Please Assign me this issue. I will solve it in C++.
LGM-SOC'21

Thank You

**Comment by ravikr126** [comment]
Already raised issue
