### ISSUE TITLE
Infix to Postfix

### ISSUE THREAD

**Issue by skimran2000** [Ayush7614/Daily-Coding-DS-ALGO-Practice#171]
# Aim

- Convert the infix expression to postfix expression using stack data structure

# Details

- By scanning the infix expression from left to right, when I will get any operand, simply add them to the postfix form, and when I get operator and parenthesis, add them in the stack maintaining the precedence of them. At the end pop the stack out completely to get postfix expression

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by skimran2000** [comment]
I am a LGM-SOC'21 Participant and has opened this issue to write the above program

**Comment by toth2000** [comment]
I would like to create a PR for the JAVA part.

**Comment by Amit366** [comment]
@toth2000 are u a participant of LGM??

**Comment by toth2000** [comment]
> @toth2000 are u a participant of LGM??

Yes

**Comment by Amit366** [comment]
> > @toth2000 are u a participant of LGM??
> 
> Yes

@toth2000 mention this in all ur comments

**Comment by pranita736** [comment]
@Amit366 @Ayush7614 Assign this to me in Python under LGM-SoC'21.

**Comment by Amit366** [comment]
@pranita736 you already have 5 issues assigned so first them and then will assign this one.

**Comment by dpshikha476** [comment]
I am a LGM-SOC'21 Participant and would you please assign me the C++ part.

**Comment by Amit366** [comment]
@dpshikha476 its already assigned for C++. If u want u can try with different language

**Comment by dpshikha476** [comment]
Can I work with C?

**Comment by Amit366** [comment]
@dpshikha476 go ahead

**Comment by pranita736** [comment]
@Amit366 Can we start creating PR now? or should we wait till June 10?

**Comment by Amit366** [comment]
@pranita736 u have to wait till 10th

**Comment by siddhi-244** [comment]
Can I work with C++?

**Comment by Amit366** [comment]
@siddhi-244 it's already assigned

**Comment by siddhi-244** [comment]
Can't I try in python?

**Comment by siddhi-244** [comment]
Sir the python task was given to me @Amit366

**Comment by Amit366** [comment]
Yes

**Comment by siddhi-244** [comment]
Ok sir I will do that today !

**Comment by siddhi-244** [comment]
Sir please review my pr @Amit366
