### ISSUE TITLE
Maximum Production(July long challenge)

### ISSUE THREAD

**Issue by bindaldhara** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1715]
AIM:
Chefland has 7 days in a week. Chef is very conscious about his work done during the week.

There are two ways he can spend his energy during the week. The first way is to do x units of work every day and the second way is to do y (>x) units of work for the first d (<7) days and to do z (<x) units of work thereafter since he will get tired of working more in the initial few days.

Find the maximum amount of work he can do during the week if he is free to choose either of the two strategies.

Leave it unchecked Owner will mark it :)
-->
- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by bindaldhara** [comment]
Please assign this issue to me

**Comment by chicken-biryani** [comment]
@bindaldhara in which language would you like to do this?

**Comment by Amit366** [comment]
U cannot add solution to ongoing contest.
