### ISSUE TITLE
Double linked list

### ISSUE THREAD

**Issue by skimran2000** [Ayush7614/Daily-Coding-DS-ALGO-Practice#172]
# Aim

- Creating a double linked list

# Details

- Doubly linked list is a type of linked list in which each node apart from storing its data has two links. The first link points to the previous node in the list and the second link points to the next node in the list. The first node of the list has its previous link pointing to NULL similarly the last node of the list has its next node pointing to NULL.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by skimran2000** [comment]
I am a LGM-SOC'21 Participant and has opened this issue to write the above program

**Comment by toth2000** [comment]
I would like to create a PR for the JAVA part.
