### ISSUE TITLE
Suggestion: To re-organise the Data Structures folder

### ISSUE THREAD

**Issue by AtrikGit6174** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1726]
Data Structures folder can be re-organised by adding a sub-folder for Linked Lists and collecting solutions of LL of  the folder into the new subfolder.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by chicken-biryani** [comment]
@AtrikGit6174 structuring the files is something I was thinking about too...

Either it could be program wise or language wise.

Something that can be discussed.

**Comment by chicken-biryani** [comment]
@Ayush7614 thoughts?

**Comment by AtrikGit6174** [comment]
I think doing it program-wise will be better... 
Actually many problems are found similar across the sites. If there would have been a way of linking shortcuts, then it would have been much beneficial to keep one copy of same problems across the various folders of CP-sites.

**Comment by Amit366** [comment]
@AtrikGit6174 I guess someone is already working on this issue. #1681
