### ISSUE TITLE
C++ Solution for "Integer to Roman" on LeetCode under LGMSOC21

### ISSUE THREAD

**Issue by AtrikGit6174** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1745]
C++ Solution for "Integer to Roman" on LeetCode under LGMSOC21
[https://leetcode.com/problems/integer-to-roman/](https://leetcode.com/problems/integer-to-roman/)

![image](https://user-images.githubusercontent.com/64845750/124348621-81c5b900-dc08-11eb-9d4c-f70876e6f013.png)

@Amit366 @ravikr126 @Ayush7614 

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by monishamandal02** [comment]
Can I contribute my solution in C++? I am kinda confused that they will assign us tasks or we have to pick questions ourselves?

**Comment by Amit366** [comment]
@monishamandal02 C++ is already assigned. If u want u can contribute in another language

**Comment by AtrikGit6174** [comment]
@monishamandal02 You can pick your own questions, solve them. Then create an issue requesting to be assigned, generate the corresponding PR.

@Amit366 Please verify whether I am right or not.

**Comment by Amit366** [comment]
@monishamandal02 yes atrik is right

But if u want to solve this question then u can choose another language.
