### ISSUE TITLE
Geek-onacci numbers

### ISSUE THREAD

**Issue by manognyaa** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1747]
**Is your feature request related to a problem? Please describe.**
Given four  integers x, y, z, N. x, y, z represents the first three numbers of geek-onacci series. 
Geek created a random series and given a name geek-onacci series.

**Describe the solution you'd like**
I will be using C++ sir.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

@Amit366 @Ayush7614 please assign this issue to me , I would like to work on it sir.

**Comment by siddhi-244** [comment]
Can I try in python?
