### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by skimran2000** [Ayush7614/Daily-Coding-DS-ALGO-Practice#175]
# Aim

- Sorting an array using shell sort algorithm

# Details

- Sorting an array using shell algorithm in c++ language

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by skimran2000** [comment]
I am a LGM-SOC'21 Participant and has opened this issue to write the above program

**Comment by Sriram-bb63** [comment]
I would like to solve this in python
