### ISSUE TITLE
Codechef June Long Challenge 2021 Division 3 rated  

### ISSUE THREAD

**Issue by NidhiChaurasia** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1756]
The Codechef Contest Solutions in preferred language and contribute this project in every possible way in terms of Competitive Programming .

The main aim of mine is to make these cross-platforms more encouraging and interesting for Budding programmers.

The Sequential solution and least time-complexity codes will be accepted else the Partial Solutions would make no sense until an optimized solution is accomplished.

Link to the Running Contest :-
https://www.codechef.com/JULY21/?itm_medium=navmenu&itm_campaign=JULY21

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Amit366** [comment]
@NidhiChaurasia This issue is already been solved
