### ISSUE TITLE
Move all negative numbers to beginning

### ISSUE THREAD

**Issue by KushagraJain58-cmd** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1766]
# Aim

Want to add a solution of "Move all negative numbers to beginning"
Kindly assign me this problem. I would like to add my solution to this problem in C++ easily and efficiently using swapping.
Link to the problem: https://www.geeksforgeeks.org/move-negative-numbers-beginning-positive-end-constant-extra-space/

# Details

An array contains both positive and negative numbers in random order. Rearrange the array elements so that all negative numbers appear before all positive numbers.

Examples : 

Input: -12, 11, -13, -5, 6, -7, 5, -3, -6
Output: -12 -13 -5 -7 -3 -6 11 6 5
Note: Order of elements is not important here.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by KushagraJain58-cmd** [comment]
Please assign me this issue under LGM-SOC'21

**Comment by ANSHUL22122001** [comment]
Please assign me this issue

**Comment by Rounak-chauhan** [comment]
Please assign me this issue under LGM-soc21 i will like to do it java

**Comment by KushagraJain58-cmd** [comment]
Please assign this issue under LGM-SOC'21 @ravikr126

**Comment by KushagraJain58-cmd** [comment]
Please assign this issue under LGM-SOC'21 @chicken-biryani

**Comment by chicken-biryani** [comment]
@ANSHUL22122001 @KushagraJain58-cmd in what languages would you want to do it?

**Comment by KushagraJain58-cmd** [comment]
I would like to  use c++

**Comment by KushagraJain58-cmd** [comment]
Please assign this issue under LGM-SOC'21 @Ayush7614

**Comment by Vidhi6340** [comment]
Please assign me this issue under LGMSOC'21. I would like to contribute in C.

**Comment by Vidhi6340** [comment]
I have created the pull request to fix this PR.Kindly review it @Amit366 @chicken-biryani

**Comment by Vidhi6340** [comment]
@Amit366 I have created a new pull request in which I have added the test cases and the file has been added in proper folder. Please Review it.
