### ISSUE TITLE
Sort an array of 0s,1s and 2s

### ISSUE THREAD

**Issue by KushagraJain58-cmd** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1768]
# Aim

Want to add a solution of "Sort an array of 0s,1s and 2s"
Kindly assign me this problem. I would like to add my solution to this problem in C++ easily and efficiently using DNF sorting.
Link to the problem: https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/

# Details
Given an array A[] consisting 0s, 1s and 2s. The task is to write a function that sorts the given array. The functions should put all 0s first, then all 1s and all 2s in last.
Examples: 
 
Input: {0, 1, 2, 0, 1, 2}
Output: {0, 0, 1, 1, 2, 2}

Input: {0, 1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1}
Output: {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2}

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by KushagraJain58-cmd** [comment]
Please assign me this issue under LGM-SOC'21

**Comment by Rounak-chauhan** [comment]
please assign me this issue under LGM-soc21 i will like to contribute the code in java

**Comment by Vidhi6340** [comment]
Please assign me this issue under LGM-SOC21. I will like to contribute in C.

**Comment by KushagraJain58-cmd** [comment]
Please assign this issue under LGM-SOC'21 @ravikr126

**Comment by KushagraJain58-cmd** [comment]
Please assign this issue under LGM-SOC'21 @chicken-biryani

**Comment by chicken-biryani** [comment]
@KushagraJain58-cmd what language would you like to do this in?

**Comment by KushagraJain58-cmd** [comment]
I would like to use c++

**Comment by hiteshv01** [comment]
Please assign me this issue under LGM-SOC'21
I would like to contribute in all the given languages

**Comment by chicken-biryani** [comment]
@hiteshv01 you can't do it in all languages, as the rest are already doing it in C Java and C++. However, you can do it in Python.

**Comment by Rounak-chauhan** [comment]
solution of sort 012 in java #1786 the second commit in for sorting please review my PR @ravikr126

**Comment by Vidhi6340** [comment]
I have generated the pull request of this issue. Please take a look into it @ravikr126

**Comment by Vidhi6340** [comment]
@Amit366 I have generated a new pull request for this issue in which the code is added in the proper folder and test cases also have been added. Please take a look into it.
