### ISSUE TITLE
Palindromic Substrings (Leetcode Medium)

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1777]
# Aim

![Screenshot 2021-07-04 122117](https://user-images.githubusercontent.com/75210337/124376112-fceba580-dcc2-11eb-8d36-0f8ae6b5ccec.png)

# Details

I would like to solve the Palindromic Substrings question in C++ under LGMSOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Kindly assign me this issue.

**Comment by 31081998** [comment]
Sir ,Kindly assign me this issue in python.
@Amit366 @Ayush7614

**Comment by 31081998** [comment]
@ravikr126 @Amit366 Sir Kindly reopen the issue as the task assigned to me is still pending. I want to generate PR for that.
