### ISSUE TITLE
Tree of Coprimes

### ISSUE THREAD

**Issue by akash-rajak** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1782]
Want to add solution to this problem of leetcode

![1](https://user-images.githubusercontent.com/57003737/124377830-b6e70f80-dccb-11eb-9044-8e42da0fad75.jpg)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by akash435** [comment]
@Amit366 , please assign this to me under LGM SOC

**Comment by Ayan-thecodeking** [comment]
i want to work on this issue under java language 
please assign me
