### ISSUE TITLE
Rearrange a LinkedList in C++

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1794]
# Aim

Create a Function that rearranges LinkedList as the given information below:
# Details
Given a singly linked list, the task is to rearrange it in a way that all odd position nodes are together and all even positions nodes are together.
Assume the first element to be at position 1 followed by the second element at position 2 and so on.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
GeeksforGeeks Medium level problem: [Link](https://practice.geeksforgeeks.org/problems/rearrange-a-linked-list/1)

**Comment by Anchal1226** [comment]
Please assign me this issue..
