### ISSUE TITLE
Rainwater trapping problem

### ISSUE THREAD

**Issue by palakagarwal5230** [Ayush7614/Daily-Coding-DS-ALGO-Practice#180]
**Problem:**
Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it is able to trap after raining.

**Example:**
Input: arr[]   = {3, 0, 2, 0, 4}
Output: 7
We can trap "3 units" of water between 3 and 2,
"1 unit" on top of bar 2 and "3 units" between 2 
and 4.

**Basic Insight**
An element of the array can store water if there are higher bars on the left and right. The amount of water to be stored in every element can be found out by finding the heights of bars on the left and right sides. The idea is to compute the amount of water that can be stored in every element of the array. 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by palakagarwal5230** [comment]
I am a LGM-SOC'21 Participant and has opened this issue. I want to write c++ solution to it.

**Comment by Amit366** [comment]
@palakagarwal5230 may I know is this from leetcode??

**Comment by palakagarwal5230** [comment]
Yes this problem is from Leetcode

**Comment by siddhi-244** [comment]
Can I try this in c++?

**Comment by Amit366** [comment]
@siddhi-244 try in another language

**Comment by siddhi-244** [comment]
> @siddhi-244 try in another language

Can I try in python?

**Comment by Yakshit310** [comment]
Hi, I'm an LGM SOC participant and would like to work on this in Python language. It would be great if this could be assigned to me.

**Comment by Amit366** [comment]
@Yakshit310 it's already assigned in python. Try other language

**Comment by siddhi-244** [comment]
Sir In which folder do I upload my file?

**Comment by siddhi-244** [comment]
@Amit366 sir I am done with the implementation in which folder should I upload my file?

**Comment by siddhi-244** [comment]
Sir I have done it in python @Amit366 
![20210610_175719](https://user-images.githubusercontent.com/69195262/121524880-61de1380-ca15-11eb-8b80-5d22c0971787.jpg)

**Comment by siddhi-244** [comment]
i have created a pr @Amit366  plzz review it

**Comment by Yakshit310** [comment]
@Amit366 JavaScript?

**Comment by Amit366** [comment]
@Yakshit310 no js

**Comment by Yakshit310** [comment]
@Amit366 C ?

**Comment by Amit366** [comment]
@palakagarwal5230 can do it in C. Since java, python and c++ are already done. So r u comfortable in c??
