### ISSUE TITLE
Deepest Leaves Sum of leetcode under LGMSOC'21

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1806]
# Aim
![Screenshot (1005)](https://user-images.githubusercontent.com/73896596/124419721-b443f300-dd7b-11eb-8d60-cbf9b2e1d728.png)
#Details
i would like to work on this issue using BFS in c++
### Programming language
- [x] C++

**Comment by SnehaAgarwal361** [comment]
@Ayush7614 Please assign me this issue.

**Comment by Ayan-thecodeking** [comment]
I want to work on this issue under java language 
please assign me  @Ayush7614
