### ISSUE TITLE
A C++ solution for Merge Without Extra Space (GFG- Hard) 

### ISSUE THREAD

**Issue by geekySapien** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1817]
# Description

### Given two sorted arrays arr1[] of size N and arr2[] of size M. Each array is sorted in non-decreasing order. Merge the two arrays into one sorted array in non-decreasing order without using any extra space.

# Link to the Problem Statement: [Link](https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays-1587115620/1)

# Test Case 1
# Input:
### arr2[] = {0, 2, 6, 8, 9}
# Output: 0 1 2 3 5 6 7 8 9
# Explanation:
### arr2[] = {5, 6, 7, 8, 9}

# Test Case 2
# Input:
### arr2[] = {5, 18, 20}
# Output: 5 10 12 18 20
# Explanation:
### arr2[] = {12, 18, 20}

# Sir, I can work on this issue and provide C++ solution for the same. Kindly Assign me this issue under LGM-SOC'21

**Comment by siddhi-244** [comment]
Can I try in python?

**Comment by Rounak-chauhan** [comment]
can i do in java?
