### ISSUE TITLE
Want to add solution of Birthday Gift Question

### ISSUE THREAD

**Issue by archismansaha** [Ayush7614/Daily-Coding-DS-ALGO-Practice#182]
# Aim
want to add solution of this question of codechef in c++ :
 https://www.codechef.com/LTIME96C/problems/TWINGFT
Assign me this issue under LGM-SOC
- What is the objective of the Script

# Details

- What the features will your script have

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by Anuradha0501** [comment]
I want to add solution of this question in java language as a participant of an LGM SOC 21 can you assign this to me also.

**Comment by Ayush7614** [comment]
Go Ahead @Anuradha0501
