### ISSUE TITLE
Spiral Matrix  (Leetcode Medium)

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1820]
# Aim
![Screenshot 2021-07-05 152120](https://user-images.githubusercontent.com/75210337/124453344-e87fd980-dda4-11eb-9701-5427792f09ad.png)

# Details

I would like to solve Spiral Matrix question in C++ language under LGMSOC'21.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 kindly assign me this issue under LGMSOC'21.

**Comment by ravikr126** [comment]
This question is in repo .@Sanskriti2401

**Comment by Sanskriti2401** [comment]
@ravikr126 Ok, I will create other new issue.
