### ISSUE TITLE
Best Time to Buy and Sell Stock III

### ISSUE THREAD

**Issue by mrkc2303** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1825]
# Aim

I want to add the solution for "Best Time to Buy and Sell Stock III"
I want to add this problem in C++ in an efficient approach. 
Link: https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/

# Details

You are given an array prices where prices[i] is the price of a given stock on the ith day.

Find the maximum profit you can achieve. You may complete at most two transactions.

Note: You may not engage in multiple transactions simultaneously (i.e., you must sell the stock before you buy again).

### Programming language 

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by mrkc2303** [comment]
@ravikr126 Please assign me this issue under LGM-SOC'21 
I want to do it in C++

**Comment by Rounak-chauhan** [comment]
@ravikr126  please assign me this issue in java

**Comment by siddhi-244** [comment]
Can I try in python
