### ISSUE TITLE
Common Elements

### ISSUE THREAD

**Issue by mrkc2303** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1826]
# Aim

I would like to add the solution for problem "Common Elements" in C++ using efficient approach. 
Link: https://practice.geeksforgeeks.org/problems/common-elements1132/1

# Details

Given three arrays sorted in increasing order. Find the elements that are common in all three arrays.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by mrkc2303** [comment]
@ravikr126 Please assign me this issue under LGM-SOC'21. 
I will add the solution in C++.

**Comment by Rounak-chauhan** [comment]
@ravikr126  sir can i do this in java language by using hashmap it has minimum time complexity
