### ISSUE TITLE
Want add solution of the question Total Components

### ISSUE THREAD

**Issue by archismansaha** [Ayush7614/Daily-Coding-DS-ALGO-Practice#183]
# Aim
want to add the solution of the problem in c++:
https://www.codechef.com/LTIME96C/problems/NUMCOMP1
Assign me this issue under LGM-SOC
- What is the objective of the Script

# Details

- What the features will your script have

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by tech-rounak** [comment]
@archismansaha  I recently added this question in codechef interview question

**Comment by archismansaha** [comment]
In which language?

**Comment by tech-rounak** [comment]
c++
