### ISSUE TITLE
To Display Spiral Matrix (GFG)

### ISSUE THREAD

**Issue by yellowberard** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1830]
Aim

Given a matrix of size r*c. Traverse the matrix in spiral form.
link to the Question:-  https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix-1587115621/1#
 Details
We have given a matrix and we have to display it's spiral form.
For Example:-
Input:
r = 4, c = 4
matrix[][] = {{1, 2, 3, 4},
           {5, 6, 7, 8},
           {9, 10, 11, 12},
           {13, 14, 15,16}}
Output: 
1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by yellowberard** [comment]
@ravikr126 Please assign me this issue under LGM-SOC'21.
I will add the solution in C++

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java as apart of LGM-SOC'21.
@ravikr126 @Amit366 Please assign it to me. Thankyou!!
