### ISSUE TITLE
Search in a row-column sorted Matrix (GFG)

### ISSUE THREAD

**Issue by yellowberard** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1831]
Aim
Given a matrix of size n x m, where every row and column is sorted in increasing order, and a number x. Find whether element x is present in the matrix or not.
link:- https://practice.geeksforgeeks.org/problems/search-in-a-matrix-1587115621/1/?category[]=Matrix&category[]=Matrix&page=1&query=category[]Matrixpage1category[]Matrix

# Details

To find if a number is present in sorted matrix or not. I will solve this question using C++. I will use shortest path to reach the Number if present.
eg
input:
n = 3, m = 3, x = 62
matrix[][] = {{ 3, 30, 38},
              {36, 43, 60},
              {40, 51, 69}}
Output: 0 

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by yellowberard** [comment]
@ravikr126 Sir, Please assign me this issue under LGM-SOC'21.

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java as apart of LGM-SOC'21.
@ravikr126 @Amit366 Please assign it to me. Thankyou!!
