### ISSUE TITLE
Count and Say (LeetCode)

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1835]
# Aim
![Screenshot 2021-07-06 130051](https://user-images.githubusercontent.com/75210337/124560657-b2049600-de5a-11eb-9efa-e2e4c3d3dfdb.png)

# Details

I would like to solve count and say in C++ language under LGMSOC'21

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 @Amit366 Kindly assign me this issue under LGMSOC'21.

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java as apart of LGM-SOC'21.
@ravikr126 @Amit366 Please assign it to me. Thankyou!!
