### ISSUE TITLE
Data Strucuture- Operations on linkedlist

### ISSUE THREAD

**Issue by KshitijS01** [Ayush7614/Daily-Coding-DS-ALGO-Practice#184]
### AIM

- Operations on linkedlist.

### DETAILS

- *Operations on linkedlist*
1. Insertion of a node ( at beginning,  at end, after/before a given location, before a node with given data).
2. Deletion 
3. Searching
4. Sorting
5. Reverse a linkedlist
6. Merging

### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by KshitijS01** [comment]
I am a LGM-SOC'21 Participant and has opened this issue to write the above program.

**Comment by Ayush7614** [comment]
Go Ahead @KshitijS01

**Comment by mitali-1703** [comment]
> I am a LGM-SOC'21 Participant and has opened this issue to write the above program.

Hey @KshitijS01 in which language will you be contributing to this issue? Actually I want to contribute in C++ so could you please tell?

**Comment by chandu6111** [comment]
Hi @Ayush7614 
I am a LGM-SOC'21 Participant
I would like to contribute to this issue in C++

**Comment by KshitijS01** [comment]
> 
> 
> > I am a LGM-SOC'21 Participant and has opened this issue to write the above program.
> 
> Hey @KshitijS01 in which language will you be contributing to this issue? Actually I want to contribute in C++ so could you please tell?

I'm using C language. @mitali-1703

**Comment by mitali-1703** [comment]
> Go Ahead @KshitijS01

@Ayush7614 will you please assign me this issue for C++ under LGM-SOC'21??

**Comment by AnkitaKataria22** [comment]
kindly assign me this issue

**Comment by Aman-Dhimann** [comment]
Hello @Ayush7614  @Amit366  .I am efficient in java . And have a good hand in DSA . I want to contribute to this issue.

**Comment by Rounak-chauhan** [comment]
> ### AIM
> * Operations on linkedlist.
> 
> ### DETAILS
> * _Operations on linkedlist_
> 
> 1. Insertion of a node ( at beginning,  at end, after/before a given location, before a node with given data).
> 2. Deletion
> 3. Searching
> 4. Sorting
> 5. Reverse a linkedlist
> 6. Merging
> 
> ### Programming language
> * [x]  C
> * [ ]  C++
> * [ ]  Java
> * [ ]  Python
i will like to work in java language please assign me this problem under LGMSOC21

**Comment by Amit366** [comment]
@Aman-Dhimann do u want to implement in java??

**Comment by Rounak-chauhan** [comment]
yes i will love to implement in java

**Comment by Rounak-chauhan** [comment]
#1587 @Amit366 operation in linked list in java is done please review my code

**Comment by Rounak-chauhan** [comment]
@Ayush7614  please review my request on linked list operation in java and let me know if its okay or  not

**Comment by Rounak-chauhan** [comment]
please review my code @Amit366
