### ISSUE TITLE
Coding Questions related to Stacks and Queues.

### ISSUE THREAD

**Issue by dpshikha476** [Ayush7614/Daily-Coding-DS-ALGO-Practice#185]
I am a LGM-SOC'21 Participant and has opened this issue to add all the coding questions related to Stacks and Queues from various platforms. Could you please assign me this (Language -  C++)? @Ayush7614

**Comment by Amit366** [comment]
@dpshikha476 you can add separate questions. Since this is an open source so everyone needs to contribute so create separate problem issues and then solve.

**Comment by dpshikha476** [comment]
Sure

> @dpshikha476 you can add separate questions. Since this is an open source so everyone needs to contribute so create separate problem issues and then solve.

Sure👍
