### ISSUE TITLE
Want to add a Question Construct Binary Tree from Inorder & Preorder Traversal

### ISSUE THREAD

**Issue by devkumar326** [Ayush7614/Daily-Coding-DS-ALGO-Practice#186]
## Aim
want to add the solution of the problem in Python:
https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/
Assign me this issue under LGM-SOC

**Details**
This question has been asked in Interviews of Amazon and Microsoft many times.

**Comment by Ayush7614** [comment]
> @Ayush7614 sir, I want to add the solution of same question in C++. Please assign me for that.
> I am participant of LGM-SOC program.

@devkumar326 @AKSHATNEMA go Ahead

**Comment by jayant766** [comment]
I can do this in C or C++ or pyhon.

Assign me plz.
LGM_SOC
