### ISSUE TITLE
 Group Anagrams - LeetCode

### ISSUE THREAD

**Issue by akash-rajak** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1863]
Want to add solution to this problem in LeetCode.

test case 1:
Input: strs = ["eat","tea","tan","ate","nat","bat"]
Output: [["bat"],["nat","tan"],["ate","eat","tea"]]

text case 2:
Input: strs = [""]
Output: [[""]]

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by akash435** [comment]
@Amit366 ,please assign this to me under LGM SOC.
