### ISSUE TITLE
Data Structures - Trees

### ISSUE THREAD

**Issue by dpshikha476** [Ayush7614/Daily-Coding-DS-ALGO-Practice#187]
### AIM
To add all the operations on trees, binary trees and BSTs like insertion, deletion, traversing, searching, etc.

**Language**

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by dpshikha476** [comment]
Can I work on this under LGM-SOC'21? (Language - C++) @Ayush7614

**Comment by Amit366** [comment]
@dpshikha476 u can do one by one Opera by creating separate issues

**Comment by dpshikha476** [comment]
Ok! I'll do that👍
