### ISSUE TITLE
Rotate Matrix 90 degree

### ISSUE THREAD

**Issue by manognyaa** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1874]
**Is your feature request related to a problem? Please describe.**
For the given matrix, the compiler will rotate the matrix into 90 degree and will give the output sir

**Describe the solution you'd like**
I would like to do it on c++ language sir

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by manognyaa** [comment]
please assign this issue to me sir, I would like to work on it @Ayush7614 sir.

**Comment by 2000shivam659** [comment]
Can i try it in java ? please assign me...
