### ISSUE TITLE
C++ AtCoder Dynamic Problem 

### ISSUE THREAD

**Issue by se-prashant** [Ayush7614/Daily-Coding-DS-ALGO-Practice#189]
# Aim

- I want to add solutions to AtCoder DpConetst 
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
@se-prashant plss describe your language in which language you want to add solution

**Comment by se-prashant** [comment]
@Ayush7614 I want to add solutions in c++.

**Comment by Ayush7614** [comment]
Go Ahead @se-prashant
