### ISSUE TITLE
Maximum Length of Repeated Subarray-Python

### ISSUE THREAD

**Issue by Zualemo-xo** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1899]
# Aim

- Provide the python code for Maximum Length of Repeated Subarray-Python

# Details

![image](https://user-images.githubusercontent.com/61049979/125000027-0e3f0400-e06d-11eb-9e88-4bf086ce0493.png)

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [X ] Python

**Comment by Zualemo-xo** [comment]
@ravikr126 Kindly assign me this issue under LGMSOC'21.

**Comment by siddhi-244** [comment]
Can I try in c++

**Comment by Zualemo-xo** [comment]
@Ayush7614 @Amit366 @ravikr126 @Saurabh4626 , Kindly review my PR #1903 .

**Comment by 2000shivam659** [comment]
can i try in java ?
