### ISSUE TITLE
Sum of nodes on the longest path from root to leaf node

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1913]
# Aim

![Screenshot 2021-07-10 032831](https://user-images.githubusercontent.com/75210337/125139865-efa14180-e12e-11eb-8455-5e9a67ac9aa8.png)

# Details

I would like to solve Sum of nodes on the longest path from root to leaf node in C++language under LGMSOC'21.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Kindly assign me this issue under LGMSOC'21

**Comment by 444-555-fatima** [comment]
kindly assign me this issue
