### ISSUE TITLE
First Unique Character in a String under LGMSOC'21

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1921]
# Aim

i would like to work on this issue in C++ using Unordered_maps.

# Details
Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1.

 

Example 1:

Input: s = "leetcode"
Output: 0

### Programming language

- [ ] C++

**Comment by Rounak-chauhan** [comment]
please assign me this issue under java language

**Comment by 2000shivam659** [comment]
Please assign me this issue 
### ##Programing Language 
- [ ] JAVA

**Comment by nickel-28** [comment]
Please assign me this particular issue
