### ISSUE TITLE
Stack implementation using Linked List.

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1930]
# Aim

- Stack implementation using Linked List

# Details

- will be adding code for implementing stack using linked list in Data Structure/Stack/Java 

### Programming language
- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

**Comment by Aryan-Srivastava** [comment]
@Amit366 @Ayush7614 @ravikr126 Please Assign me this Issue. I will solve it in java.

Thank you

**Comment by Rounak-chauhan** [comment]
please allow me this to do in java @ravikr126 @Amit366
