### ISSUE TITLE
Merge Two BST

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1934]
# Aim

![Screenshot 2021-07-11 101326](https://user-images.githubusercontent.com/75210337/125183092-34150600-e231-11eb-8350-65789502ded6.png)

# Details

I would like to solve Merge Two BST in C++ under LGMSOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Kindly assign me this issue.

**Comment by Rounak-chauhan** [comment]
please assign me this issue in java under LGMSOC21 @ravikr126

**Comment by 2000shivam659** [comment]
Please assign me this

### Programming language

- [ ] JAVA
