### ISSUE TITLE
Duplicate subtree in Binary Tree 

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1935]
# Aim

![Screenshot 2021-07-11 102400](https://user-images.githubusercontent.com/75210337/125183224-6410d900-e232-11eb-9398-2ac8e9a46fcd.png)

# Details

I would like to solve  Duplicate subtree in Binary Tree  in C++ under LGMSOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Kindly assign me this issue under LGMSOC'21

**Comment by Rounak-chauhan** [comment]
please assign me this issue in java language @ravikr126
