### ISSUE TITLE
Concentric square pattern using 2D array In C

### ISSUE THREAD

**Issue by abhaydev360** [Ayush7614/Daily-Coding-DS-ALGO-Practice#194]
**Aim**
Solution of Concentric Square pattern 

**Details**
I want to code of Concentric Square pattern using 2d array in C
### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

I am a LGM-SOC'21 Participant and has opened this issue to write the above program. 
@Ayush7614 @Amit366  pls assign me this issue

**Comment by aktamoli0910** [comment]
Can I work on C++ code for this project?
