### ISSUE TITLE
Palindrome Linked List (Leetcode) LGMSOC'21 

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1944]
# Aim

i would like to work on this issue under LGMSOC'21

# Details

![Screenshot (1019)](https://user-images.githubusercontent.com/73896596/125201696-dd89e500-e28d-11eb-8f13-09661a1d8f44.png)

### Programming language
<!--

- [ ] C++

**Comment by ravikr126** [comment]
This question is already in repository
