### ISSUE TITLE
Number of 1 Bits under LGMSOC'21

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1945]
# Aim

I would like to work on this issue.

# Details

![Screenshot (1018)](https://user-images.githubusercontent.com/73896596/125201756-04481b80-e28e-11eb-8fcb-5c022d4ca01a.png)

### Programming language
C++

**Comment by 2000shivam659** [comment]
Please assign me this

### Programming language

- [ ] JAVA
