### ISSUE TITLE
C++ Solution to "Swap Nodes in Pairs" on LeetCode under LGMSOC21

### ISSUE THREAD

**Issue by AtrikGit6174** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1951]
I would like to add the C++ Solution to "Swap Nodes in Pairs" on LeetCode under LGMSOC21.
It is using recursion.
[https://leetcode.com/explore/learn/card/recursion-i/250/principle-of-recursion/1681/](https://leetcode.com/explore/learn/card/recursion-i/250/principle-of-recursion/1681/)

![image](https://user-images.githubusercontent.com/64845750/125207603-d7563180-e2aa-11eb-9b3c-fafea84abaf2.png)

Please assign me this issue.
@Amit366 @ravikr126 @Ayush7614 
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by 2000shivam659** [comment]
Please assign me this under LGM-SOC'21
@Amit366  @ravikr126  @Ayush7614 
I would like to solve this using recursion method.
### Programing Language

- [ ]  C
- [ ]  C++
- [ ]  Java
- [ ]  Python
- [ ]  Python
