### ISSUE TITLE
Integer to English Words (Leetcode)

### ISSUE THREAD

**Issue by akash-rajak** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1959]
Want to add solution to this leetcode problem.

first test case :
Input: num = 123
Output: "One Hundred Twenty Three"

second testcase :
Input: num = 1234567891
Output: "One Billion Two Hundred Thirty Four Million Five Hundred Sixty Seven Thousand Eight Hundred Ninety One"

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by akash435** [comment]
@Amit366 please assign this to me under LGM SOC.
