### ISSUE TITLE
Tower of Hanoi under LMG SOC'21

### ISSUE THREAD

**Issue by simarjeet30** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1962]
It consists of three rods and a number of disks of different diameters, which can slide onto any rod , Only one disk may be moved at a time , Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack or an empty rod , No disk may be placed on top of a disk that is smaller than it.

I would like to solve this problem using recursion where firstly I will put n-1 discs from A to B rod and then n th disc from A to C , and lastly all discs from B to C . 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by simarjeet30** [comment]
I would request all the mentors to please assign this to me ,My code will have proper comments and examples.

**Comment by Rounak-chauhan** [comment]
please allow me this to do in java @ravikr126 @Amit366

**Comment by nidh-cyber** [comment]
@ravikr126 @Amit366 please assign this issue to me, I would like to solve this problem using recursion where firstly I will put n-1 discs from A to B rod and then n th disc from A to C , and lastly all discs from B to C in c++
