### ISSUE TITLE
Normal BST to Balanced BST(GFG)

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1971]
# Aim

![Screenshot 2021-07-13 024949](https://user-images.githubusercontent.com/75210337/125357390-3ab49200-e385-11eb-9370-7427af662dc6.png)

# Details

I would like to solve  Normal BST to Balanced BST in C++ under LGMSOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 @Amit366  Kindly assign me this issue under LGMSOC'21

**Comment by 2000shivam659** [comment]
can I try in java ? @ravikr126

**Comment by Rounak-chauhan** [comment]
please allow me this to do in java @ravikr126 @Amit366

**Comment by 2000shivam659** [comment]
Please reopen this issue as task is assigned to me today and I want to generate PR.
