### ISSUE TITLE
k-th smallest element in BST 

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1972]
# Aim

![Screenshot 2021-07-13 025818](https://user-images.githubusercontent.com/75210337/125358338-62582a00-e386-11eb-98a8-33ef00c993bc.png)

# Details

I would like to solve k-th smallest element in BST   in C++ under LGMSOC'21

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 @Amit366 Kindly assign me this issue under LGMSOC'21

**Comment by 2000shivam659** [comment]
can I try in java ? @ravikr126

**Comment by Rounak-chauhan** [comment]
please allow me to do this java language

**Comment by 2000shivam659** [comment]
Please reopen this issue as task is assigned to me today and I want to generate PR.
