### ISSUE TITLE
 Subtree of Another Tree under LGMSOC'21

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1986]
# Aim

I would like to work on this issue under LGMSOC'21 using recursive technique

# Details

![Screenshot (1021)](https://user-images.githubusercontent.com/73896596/125495837-9982de0c-c7f2-4150-8e77-604a78d607a4.png)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Rounak-chauhan** [comment]
i will like to do this in java

**Comment by 2000shivam659** [comment]
✋ Can I do this ?
### Programing language

- [ ] Java
