### ISSUE TITLE
Pattern problems using C/C++

### ISSUE THREAD

**Issue by KshitijS01** [Ayush7614/Daily-Coding-DS-ALGO-Practice#199]
### AIM

- Solving pattern problems using C/C++ 

### DETAILS

- Solving pattern problems (like pyramid, triangle, diamond etc ) using C/C++ language.

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [ ] Python

I am a LGM-SOC'21 Participant has opened this issue. @Ayush7614 , @Amit366 please assign me this issue.

**Comment by Amit366** [comment]
@KshitijS01 which pattern question do u want to solve?? 
Any particular question??

**Comment by Ayush7614** [comment]
We are not accepting this type question like Pattern problem we accept hackerank,gfg and Data Structures and Algorithms Question @KshitijS01
