### ISSUE TITLE
Rotten Oranges( GFG)

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1991]
# Aim

![Screenshot 2021-07-14 010738](https://user-images.githubusercontent.com/75210337/125514649-e18db650-a656-4bbb-8daa-faa0103e770a.png)

# Details

I would like to solve Rotten Oranges  in C++ under LGMSOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Kindly assign me this issue under LGMSOC'21

**Comment by sonamgupta136** [comment]
@ravikr126 #1991  can I try in Python ?
