### ISSUE TITLE
Linked List Cycle II (Leetcode)

### ISSUE THREAD

**Issue by 2000shivam659** [Ayush7614/Daily-Coding-DS-ALGO-Practice#1995]
https://leetcode.com/problems/linked-list-cycle-ii/
<img width="637" alt="cd" src="https://user-images.githubusercontent.com/76156804/125573740-0cad4b4d-e62d-43a5-b076-fbb0c24bda0c.png">
# Aim
Given a linked list, return the node where the cycle begins. If there is no cycle, return null.
# Details
Example 1:
Input: head = [3,2,0,-4], pos = 1
Output: tail connects to node index 1
Explanation: There is a cycle in the linked list, where tail connects to the second node.

Example 2:
Input: head = [1,2], pos = 0
Output: tail connects to node index 0
Explanation: There is a cycle in the linked list, where tail connects to the first node.
### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by 2000shivam659** [comment]
assign me this.....in java language.

**Comment by kamleshjoshi8102** [comment]
@Ayush7614 I would like to add my C++ solution under LGMSOC'21
