### ISSUE TITLE
Questions on Array

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2]
Solve more questions on Array

**Comment by Rohit-FSD** [comment]
@Ayush7614  assign me this task.

**Comment by Ayush7614** [comment]
bro project is under contest so i am unable to assign you this time

**Comment by Rohit-FSD** [comment]
@Ayush7614 okay!

**Comment by Ruchip16** [comment]
@Ayush7614  Can you assign this issue to me for LetsgrowMore-SOC and also I am currently practicing questions on the array from leetcode so I would be able to do this

**Comment by Ayush7614** [comment]
> @Ayush7614 Can you assign this issue to me for LetsgrowMore-SOC and also I am currently practicing questions on the array from leetcode so I would be able to do this

Hey @Ruchip16 thanku for intrest but currently the program was not started when it was started then i will assign you this

**Comment by Ruchip16** [comment]
@Ayush7614 Okay sure

**Comment by sejalvasan** [comment]
Can you please assign this issue to me?

**Comment by Ayush7614** [comment]
> Can you please assign this issue to me?

Under program or without program

**Comment by sejalvasan** [comment]
> > Can you please assign this issue to me?
> 
> Under program or without program

>Under LetsgrowMore program

**Comment by Ayush7614** [comment]
> > > Can you please assign this issue to me?
> > 
> > 
> > Under program or without program
> 
> > Under LetsgrowMore program

@sejalvasan I assigned to you but program was start from 10 june so your contribution not count for program for program contribution count from 10 of June but if you work for without program then I assign you but if you work for program then scores will count from 10 of june

**Comment by Ruchip16** [comment]
@Ayush7614  hey, reminding that I would be glad to contribute to this issue from 10th June

**Comment by Sakalya100** [comment]
Hey @Ayush7614 . I would like to contribute to the project and add relevant questions to the repo regularly. Please assign me this under the program on 10th June.

**Comment by vajpayeemrudul** [comment]
I would like to add some good questions on this issue.Can you pls assign this to me.

**Comment by Ayush7614** [comment]
@sejalvasan @Ruchip16 Go Ahead but do not same questions if you addded same question then code in different langauges

**Comment by Ayush7614** [comment]
@Sakalya100 you also Go Ahead

**Comment by Ruchip16** [comment]
@Ayush7614 We have to start working on this from 10th June right?

**Comment by Ayush7614** [comment]
> @Ayush7614 We have to start working on this from 10th June right?

Yes

**Comment by Ruchip16** [comment]
@Ayush7614 Hey, Just wanted to clarify one thing that do we need to add questions here or **how do we need to do it** like **select a question from Leetcode/Gfg on arrays** and then **solve that question** and **make a PR for that question**, but where do we need to post the question ad as 3 contributors are contributing in the worst case what if we select the same question?

**Comment by mitali-1703** [comment]
> Solve more questions on Array

@Ayush7614 Hi. Can I add basic to intermediate level questions of array under   LetsgrowMore-SOC,if you could assign me this?

**Comment by Ruchip16** [comment]
Hey, @Ayush7614  I can work on this issue from tomorrow right?
