### ISSUE TITLE
Construct Binary Tree from Preorder and Inorder Traversal leetcode medium under LGMSOC'21

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2004]
# Aim
i would like to work on this issue using unordered maps in c++
# Details

105. Construct Binary Tree from Preorder and Inorder Traversal
Medium

Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.

 

Example 1:

Input: preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]
Output: [3,9,20,null,null,15,7]
Example 2:

Input: preorder = [-1], inorder = [-1]
Output: [-1]
 

Constraints:

1 <= preorder.length <= 3000
inorder.length == preorder.length
-3000 <= preorder[i], inorder[i] <= 3000
preorder and inorder consist of unique values.
Each value of inorder also appears in preorder.
preorder is guaranteed to be the preorder traversal of the tree.
inorder is guaranteed to be the inorder traversal of the tree.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by SnehaAgarwal361** [comment]
Please assign me thi sissue @ravikr126 @Ayush7614

**Comment by ravikr126** [comment]
It's already in repo @SnehaAgarwal361
