### ISSUE TITLE
"Maximum Production" problem of codechef

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2006]
# Aim

I want to add the code for "Maximum Production" problem of codechef (July Challenge 2021)
Contest ended on July 12th 

# Details

Problem name : Maximum Production
Problem Code : EITA
Problem link : https://www.codechef.com/JULY21C/problems/EITA

Please assign me this issue
LGM-SOC Participant

Programming language
C++

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by manuvarghese0603** [comment]
@Amit366 @ravikr126 @Ayush7614 Please assign this issue to me under the label LGM-SOC

**Comment by shruti3000** [comment]
@Amit366 @ravikr126 @Ayush7614 Please assign this issue to me under the label LGM-SOC for python
