### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by nikhil00shinde** [Ayush7614/Daily-Coding-DS-ALGO-Practice#201]
# Aim

- In the Algorithm part, I want to add Kadane's Algorithm

# Details

- Maximum Subarray Sum in the Array

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

I  want to write a C++  and Java solution to it.

@Ayush7614 assign me this issue under LGM-SOC'21.

**Comment by Amit366** [comment]
@nikhil00shinde This algorithm already exists in GFG folder. So I am closing it.
