### ISSUE TITLE
Vector-Erase HackerRank

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2014]
**Problem Link:**
https://www.hackerrank.com/challenges/vector-erase/problem

**Aim:**
You are provided with a vector of N integers. Then, you are given 2 queries. For the first query, you are provided with 1 integer, which denotes a position in the vector. The value at this position in the vector needs to be erased. The next query consists of 2 integers denoting a range of the positions in the vector. The elements which fall under that range should be removed. The second query is performed on the updated vector which we get after performing the first query.

**Details:**
![image](https://user-images.githubusercontent.com/81305824/125666494-c6929705-4926-4f71-9fd2-692b23bf7827.png)

**Programming Language:**
- [x]  C++
- [ ]  Java
- [ ]  C
- [ ]  Python

**Comment by gunjan-g** [comment]
Please assign this issue to me under the label LGM-SOC

**Comment by Ashu-1309** [comment]
Please assign me under LGM-SOC 21 . I would like to do it in python .
