### ISSUE TITLE
Middle of three using minimum comparison

### ISSUE THREAD

**Issue by baljeet-singh97** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2034]
# Aim

- Middle of three using minimum comparison

# Details

- Given three distinct numbers A, B and C. Find the number with value in middle (Try to do it with minimum comparisons)

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by baljeet-singh97** [comment]
assign this issue to me, under LGM-SOC
@Amit366 @ravikr126 @Ayush7614

**Comment by 2000shivam659** [comment]
can i try in java ?
@Amit366 @ravikr126 @Ayush7614

**Comment by ravikr126** [comment]
> can i try in java ?
> @Amit366 @ravikr126 @Ayush7614

Create pr for this I will merge it
