### ISSUE TITLE
Simple Array Sum

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2041]
**Program Link:**
https://www.hackerrank.com/challenges/simple-array-sum/problem

**Aim:**
Given an array of integers, find the sum of its elements.
For example, if the array ar = [1,2,3], 1+2+3=6 , so return 6.

**Function Description**
Complete the simpleArraySum function in the editor below. It must return the sum of the array elements as an integer.
simpleArraySum has the following parameter(s):
- ar: an array of integers

**Details:**
![image](https://user-images.githubusercontent.com/81305824/125865762-aee06ccc-3a69-4f7e-a11b-bb7d1c48d7f5.png)

**Programming Languages:**
- [x]  C++
- [ ]  C
- [ ]  Java
- [ ]  Python

**Comment by gunjan-g** [comment]
@Amit366 @ravikr126 @Ayush7614 Please assign this issue to me under the label LGM-SOC

**Comment by ravikr126** [comment]
Already in repo @gunjan-g

**Comment by gunjan-g** [comment]
> Already in repo @gunjan-g

@ravikr126 the issue is not present in HackerRank C++ repositry, please check
