### ISSUE TITLE
A Very Big Sum

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2042]
**Program Link:**
https://www.hackerrank.com/challenges/a-very-big-sum/problem

**Aim:**
In this challenge, you are required to calculate and print the sum of the elements in an array, keeping in mind that some of those integers may be quite large.

**Function Description**
Complete the aVeryBigSum function in the editor below. It must return the sum of all array elements.
aVeryBigSum has the following parameter(s):

- int ar[n]: an array of integers .

Return
- long: the sum of all array elements

**Details:**
![image](https://user-images.githubusercontent.com/81305824/125866208-0e615bd8-8863-4c08-8636-0ff0516eaf27.png)

**Programming Languages:**
- [x]  C++
- [ ]  C
- [ ]  Java
- [ ]  Python

**Comment by gunjan-g** [comment]
@Amit366 @ravikr126 @Ayush7614 Please assign this issue to me under the label LGM-SOC

**Comment by shruti3000** [comment]
@Amit366 @ravikr126 @Ayush7614 Please assign this issue to me under the label LGM-SOC for python
