### ISSUE TITLE
Plus Minus HackerRank

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2043]
**Program Link:**
https://www.hackerrank.com/challenges/plus-minus/problem

**Aim:**
Given an array of integers, calculate the ratios of its elements that are positive, negative, and zero. Print the decimal value of each fraction on a new line with 6 places after the decimal.

**Details:**
![image](https://user-images.githubusercontent.com/81305824/125866587-b3436245-f85c-4a33-9fa6-c89b35fa0028.png)

**Programming Languages:**
- [x]  C++
- [ ]  C
- [ ]  Java
- [ ]  Python

**Comment by gunjan-g** [comment]
@Amit366 @ravikr126 @Ayush7614 Please assign this issue to me under the label LGM-SOC

**Comment by ravikr126** [comment]
Already in repo @gunjan-g

**Comment by gunjan-g** [comment]
> Already in repo @gunjan-g

@ravikr126 the issue is not present in HackerRank C++ repositry, please check

**Comment by Amit366** [comment]
@gunjan-g u can work on it

**Comment by gunjan-g** [comment]
> @gunjan-g u can work on it

Please add the label of LGM-SOC
