### ISSUE TITLE
Mini-Max Sum

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2044]
**Program Link:**
https://www.hackerrank.com/challenges/mini-max-sum/problem

**Aim:**
Given five positive integers, find the minimum and maximum values that can be calculated by summing exactly four of the five integers. Then print the respective minimum and maximum values as a single line of two space-separated long integers.

**Details:**
![image](https://user-images.githubusercontent.com/81305824/125866819-68eeab96-76e6-4b2a-b095-6d23c307e17b.png)

**Programming Languages:**
- [x]  C++
- [ ]  C
- [ ]  Java
- [ ]  Python

**Comment by gunjan-g** [comment]
@Amit366 @ravikr126 @Ayush7614 Please assign this issue to me under the label LGM-SOC

**Comment by nickel-28** [comment]
@Amit366 @ravikr126 @Ayush7614 Please assign this issue to me under the label LGM-SOC
