### ISSUE TITLE
Print the Elements of a Linked List

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2046]
**Aim:**
This is an to practice traversing a linked list. Given a pointer to the head node of a linked list, print each node's  element, one per line. If the head pointer is null (indicating the list is empty), there is nothing to print.
Complete the printLinkedList function in the editor below.

printLinkedList has the following parameter(s):
- SinglyLinkedListNode head: a reference to the head of the list

Print
- For each node, print its  value on a new line

**Details:**
![image](https://user-images.githubusercontent.com/81305824/125867493-eb31a696-9b34-44fa-840e-2f07b9fb655f.png)

**Programming Languages:**
- [x]  C++
- [ ]  C
- [ ]  Java
- [ ]  Python

**Comment by gunjan-g** [comment]
@Amit366 @ravikr126 @Ayush7614 Please assign this issue to me under the label LGM-SOC

**Comment by ravikr126** [comment]
Already in repo @gunjan-g
