### ISSUE TITLE
Video Solution For Hard and Easy Questions 

### ISSUE THREAD

**Issue by SahityaRoy** [Ayush7614/Daily-Coding-DS-ALGO-Practice#205]
**Is your feature request related to a problem? Please describe.**
Yes it's a new feature because if we add video solution it will be more beneficial for students and easy to understand the code.

**Describe the solution you'd like**
Video solution helps students too easily understand , because many students prefare videos thats why i think its very necessary to upload videos.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
Sorry but this is diffrent for the project
