### ISSUE TITLE
Tower of Hanoi 

### ISSUE THREAD

**Issue by drishika2002** [Ayush7614/Daily-Coding-DS-ALGO-Practice#206]
I would like to add the code for the Tower of Hanoi problem under LGM SOC'21.

Language: C++
Please assign this issue to me.

**Comment by div0510** [comment]
I would like to add the code for the Tower of Hanoi problem under LGM SOC'21.

I have already made such a program prior during my practice. 
Made using C++
Please assign this issue to me.

**Comment by drishika2002** [comment]
> I would like to add the code for the Tower of Hanoi problem under LGM SOC'21.
> 
> I have already made such a program prior during my practice.
> Made using C++
> Please assign this issue to me.

Hi @div0510
I have already been assigned this issue and I am coding it in C++ so, it would be great if you code it in java or python.

**Comment by nikhil00shinde** [comment]
@Amit366 @Ayush7614 I would like to implement the Java part for this code.

**Comment by nikhil00shinde** [comment]
@Amit366 I have completed the java part of the code

**Comment by Kartikey0205** [comment]
Please assign @Amit366 to do this with C-language!

**Comment by mitali-1703** [comment]
@Ayush7614 @Amit366 please assign me this to do in C-language!

**Comment by mitali-1703** [comment]
Hey @Ayush7614 @Amit366 can u assign me this issue in C++ under LGM-SOC'21 as there's only C language code for this prblm??
