### ISSUE TITLE
Solution of XxOoRr codechef problem

### ISSUE THREAD

**Issue by sakinanomi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2061]
# Aim
Solution to codechef problem XxOoRr from July long challenge in c language

link: https://www.codechef.com/JULY21C/problems/XXOORR 

### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by sakinanomi** [comment]
@ravikr126  please assign this issue to me under LGM-Soc

**Comment by shruti3000** [comment]
@ravikr126  i would like to work on this issue.

**Comment by ravikr126** [comment]
It already in repo@sakinanomi @shruti3000
