### ISSUE TITLE
TWO MISSING NUMBERS 

### ISSUE THREAD

**Issue by manognyaa** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2064]
**Is your feature request related to a problem? Please describe.**
this code will help to find the two missing numbers.
 
**Describe the solution you'd like**
I would like to use Java sir.

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

please assign this issue to me @Ayush7614 sir. I would like to work on this issue.

**Comment by suy1968** [comment]
please assign me as I am participant of LGMSOC'21
I used Python3
