### ISSUE TITLE
Open the lock under LGMSOC'21

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2066]
# Aim
i would like to work on this issue under LGMSOC'21 In c++

# Details
![Screenshot (1023)](https://user-images.githubusercontent.com/73896596/125989218-004fc345-25f8-48a0-af1f-bbe600b89adb.png)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by AliHaider20** [comment]
Can you share the link to the challenge?

**Comment by SnehaAgarwal361** [comment]
here you go!
https://leetcode.com/explore/learn/card/queue-stack/

**Comment by SnehaAgarwal361** [comment]
Please assign me this issue @Ayush7614 @ravikr126
