### ISSUE TITLE
Perfect squares

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2067]
# Aim
i would like to work on this issue under LGMSOC'21

# Details

![Screenshot (1024)](https://user-images.githubusercontent.com/73896596/125989419-6a2d63cb-831b-43f1-831d-f9ab215da8d2.png)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by SnehaAgarwal361** [comment]
Please assign me this issue @Ayush7614 @ravikr126

**Comment by 2000shivam659** [comment]
I would like to try this in java under LGMSOC'21.

**Comment by shruti3000** [comment]
Please assign me this issue @Ayush7614 @ravikr126 for python
