### ISSUE TITLE
Sereja and Dima problem

### ISSUE THREAD

**Issue by drishika2002** [Ayush7614/Daily-Coding-DS-ALGO-Practice#207]
Sereja and Dima play a game. The rules of the game are very simple. The players have n cards in a row. Each card contains a number, all numbers on the cards are distinct. The players take turns, Sereja moves first. During his turn, a player can take one card: either the leftmost card in a row or the rightmost one. The game ends when there are no more cards. The player who has the maximum sum of numbers on his cards by the end of the game wins. 

Sereja and Dima are being greedy. Each of them chooses the card with the larger number during his move.Inna is a friend of Sereja and Dima. She knows which strategy the guys are using, so she wants to determine the final score, given the initial state of the game. Help her.

Input:
4
4 1 2 10
Output:
12 5

I want to code it in C++ under LGM SOC'21. Please assign me this issue.

**Comment by sadikRizvi31** [comment]
Hey !  I want to Contribute my Solution to this problem . Can you assing this to me ?

**Comment by nikhil00shinde** [comment]
@Amit366 @Ayush7614  I would like to implement this code in Java. Please assign me for the Java part.
