### ISSUE TITLE
majority elements

### ISSUE THREAD

**Issue by baljeet-singh97** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2071]
# Aim

- majority elements

# Details

- Given an array A of N elements. Find the majority element in the array. A majority element in an array A of size N is an element that appears more than N/2 times in the array.

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by baljeet-singh97** [comment]
requesting to assign this to me under lgmsoc.
@Amit366 @ravikr126 @Ayush7614

**Comment by priyanshi5** [comment]
I would like to work on this issue. Please assign this issue to me under LGMSOC'21

**Comment by shruti3000** [comment]
Please assign this issue to me under LGMSOC'21.
@Amit366 @ravikr126 @Ayush7614

**Comment by baljeet-singh97** [comment]
guyz i raised this issue, i want to submit this sol, why u all are requesting too 😀 😃 😄 😁

**Comment by shruti3000** [comment]
Okk ..i didn't knew that !

**Comment by baljeet-singh97** [comment]
merged with issue #2105
