### ISSUE TITLE
Flood Fill 

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2080]
# Aim

![Screenshot 2021-07-17 163308](https://user-images.githubusercontent.com/75210337/126034932-a87c3085-f5f1-4777-b782-4a3c2292312e.png)

# Details

I would like to solve Flood Fill  in C++ under LGMSOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Kindly assign me this issue under LGMSOC'21

**Comment by Rounak-chauhan** [comment]
please assign me this under java
