### ISSUE TITLE
3 Sum problem

### ISSUE THREAD

**Issue by shruti3000** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2081]
# Aim

- Leetcode Problem

# Details

- [https://leetcode.com/problems/3sum/](url)

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by vaishali-goyal24** [comment]
@ravikr126  Kindly assign me this issue under LGMSOC'21

**Comment by vaishali-goyal24** [comment]
Assign this issue to me, under LGM-SOC
@Amit366 @ravikr126 @Ayush7614

**Comment by ravikr126** [comment]
Already in repo
