### ISSUE TITLE
Kth Smallest Element in a BST leetcode

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2089]
# Aim

i want to solve this issue under LGMSOC using the fact bst has its children in a structured way in c++

# Details

![Screenshot (1031)](https://user-images.githubusercontent.com/73896596/126046712-f97bf46c-5bd4-4185-a01c-e038233376aa.png)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by SnehaAgarwal361** [comment]
please assign me this issue @Ayush7614 @ravikr126

**Comment by Rounak-chauhan** [comment]
please assign me this issue i really wanted to work in java @Ayush7614 @ravikr126

**Comment by SnehaAgarwal361** [comment]
please assign me this issue @ravikr126 @Ayush7614

**Comment by Rounak-chauhan** [comment]
PLEASE ASSIGN ME THIS ISSUE @ravikr126 @Saurabh4626 @Ayush7614 in java
