### ISSUE TITLE
Solution for calculating the maximum absolute difference between the sum of two non-overlapping subarrays

### ISSUE THREAD

**Issue by cmulay** [Ayush7614/Daily-Coding-DS-ALGO-Practice#209]
# Aim

- Find the maximum absolute difference between the sum of two non-overlapping subarrays

# Details

- Solution for finding the maximum absolute difference between the sum of two non-overlapping subarrays in linear time.

### Programming language

- [ ] C
- [ X ] C++
- [ X ] Java
- [ X ] Python

Kindly assign me this issue, I would like to work on the PS under LGM-SOC'21.

**Comment by cmulay** [comment]
@Amit366 I would like to provide the solution in all the three languages i.e C++, Python and Java

**Comment by Amit366** [comment]
@cmulay u can choose only one language

**Comment by Amit366** [comment]
if no is interested then u can continue

**Comment by cmulay** [comment]
Ok, I will do it in CPP
