### ISSUE TITLE
Count triplets with sum smaller than X 

### ISSUE THREAD

**Issue by baljeet-singh97** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2092]
# Aim

- Count triplets with sum smaller than X 

# Details

- Given an array arr[] of distinct integers of size N and a sum value X, the task is to find count of triplets with the sum smaller than the given sum value X.

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by baljeet-singh97** [comment]
assign this to me under lgmsoc21 
@Amit366  @ravikr126  @Ayush7614

**Comment by Rounak-chauhan** [comment]
assign this to me under lgmsoc21 under java @Amit366
