### ISSUE TITLE
Cheapest Flights Within K Stops

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2094]
# Aim

![Screenshot 2021-07-18 032318](https://user-images.githubusercontent.com/75210337/126050098-defbf14d-4bca-4343-a46a-92481b2c8dc7.png)

# Details

I would like to solve Cheapest Flights Within K Stops in C++ under LGMSOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126  Kindly assign me this issue under LGMSOC'21

**Comment by Rounak-chauhan** [comment]
assign this to me under lgmsoc21 under java @Amit366
