### ISSUE TITLE
Minumum swap to sort

### ISSUE THREAD

**Issue by baljeet-singh97** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2116]
# Aim

- Minumum swap to sort

# Details

- Given an array of n distinct elements. Find the minimum number of swaps required to sort the array in strictly increasing order.

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by baljeet-singh97** [comment]
assign this issue to me @ravikr126

**Comment by Ashu-1309** [comment]
Please assign me under LGM-SOC @ravikr126 . it want to do it python

**Comment by nikhil00shinde** [comment]
@Amit366 @ravikr126   Please assign me under LGM-SOC. I want to implement it in JAVA.
