### ISSUE TITLE
Print Multiplication Table of any Integer in C

### ISSUE THREAD

**Issue by KimtVak8143** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2131]
# Aim

- Print Multiplication Table of any Integer.

# Details

-Using Basic Flow control and Arithmetic Manipulation

### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Tanya1323** [comment]
i want to solve this problem in c++ language .pls assign me its issue under LGMSOC label

**Comment by jainapoorva40** [comment]
Please assign this issue to me @Ayush7614 under LGMSOC'21.
I want to solve it in C++.
