### ISSUE TITLE
 Palindromic Substrings under LGMSOC'21

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2136]
# Aim
i would like to work on this issue under LGMSOC using strings in C++

# Details

Palindromic Substrings

Given a string s, return the number of palindromic substrings in it.

A string is a palindrome when it reads the same backward as forward.

A substring is a contiguous sequence of characters within the string.

 

Example 1:

Input: s = "abc"
Output: 3
Explanation: Three palindromic strings: "a", "b", "c".
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by SnehaAgarwal361** [comment]
PLEASE ASSIGN ME THIS ISSUE @ravikr126 @Saurabh4626 @Ayush7614

**Comment by Rounak-chauhan** [comment]
PLEASE ASSIGN ME THIS ISSUE @ravikr126 @Saurabh4626 @Ayush7614 in java

**Comment by Ayush7614** [comment]
Already we have
