### ISSUE TITLE
Intersection Point in Y Shapped Linked Lists 

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2137]
# Aim

![Screenshot 2021-07-21 011521](https://user-images.githubusercontent.com/75210337/126386114-e8475abc-02e3-4bde-b32c-4f0d34d469d5.png)

# Details

I would like to solve Intersection Point in Y Shapped Linked Lists in C++ under LGMSOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by suy1968** [comment]
Please assign me as I am participant of LGMSOC21

**Comment by Sanskriti2401** [comment]
@ravikr126 Kindly assign me this issue under LGMSOC'21
