### ISSUE TITLE
Delete loop from linked list

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2138]
# Aim

- will be adding code for [remove loop from linked list](https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1#) in Gfg/Java folder

# Details

> problem statement -

- Given a linked list of N nodes such that it may contain a loop.

> A loop here means that the last node of the link list is connected to the node at position X. If the link list does not have any loop, X=0.

Remove the loop from the linked list, if it is present. 

> Example -

- Input:
N = 3
value[] = {1,3,4}
X = 2
Output: 1
Explanation: The link list looks like
1 -> 3 -> 4
     ^    |
     |____|    
A loop is present. If you remove it 
successfully, the answer will be 1. 

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

**Comment by suy1968** [comment]
please assign me as I am participant of LGMSOC21
