### ISSUE TITLE
Solution to Partition Problem using Dynamic Programming

### ISSUE THREAD

**Issue by cmulay** [Ayush7614/Daily-Coding-DS-ALGO-Practice#214]
# Aim

- To solve the partition problem by using dynamic programming

# Details

- for given set of positive integer numbers, solution is to find whether it can be divided into two subsets with equal sum.

### Programming language
- [ ] C
- [ X ] C++
- [  X ] Java
- [  X ] Python

Kindly assign me this issue, I would like to work on the PS under LGM-SOC'21.

**Comment by girija0707** [comment]
kindly assign this to me in c++
