### ISSUE TITLE
X - Tower

### ISSUE THREAD

**Issue by soma2000-lang** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2146]
# Aim

- What is the objective of the Script
I would like to solve this famous atcoder  dp series problem

# Details

Problem link-https://atcoder.jp/contests/dp/tasks/dp_x

### Programming languageI 
I would like to code in c++

**Comment by soma2000-lang** [comment]
@ravikr126 Please assign me this issue.I am a particpant of LGMSOC-21

**Comment by nickel-28** [comment]
@ravikr126 Kindly assign me this issue
