### ISSUE TITLE
Want to add Basic Mathematics questions for all beginners in CP 

### ISSUE THREAD

**Issue by mitali-1703** [Ayush7614/Daily-Coding-DS-ALGO-Practice#215]
When base is strong, foundation can also be laid strong. So here I come with some basic mathematics questions to help all those beginners in the coding era.

**Comment by mitali-1703** [comment]
@Ayush7614 will oyu please assign me this task under LGM-SOC'21?

**Comment by Ayush7614** [comment]
You can add only one question for one issue not all question so i closed this issue you can open new issue and add single single problems

**Comment by mitali-1703** [comment]
> You can add only one question for one issue not all question so i closed this issue you can open new issue and add single single problems

Ok no problem
