### ISSUE TITLE
Want to add bubble sort question in CPP

### ISSUE THREAD

**Issue by mitali-1703** [Ayush7614/Daily-Coding-DS-ALGO-Practice#216]

**Comment by mitali-1703** [comment]
> Sorting is really an important concept not only from coding perspective but also in general. Would love to add all sorting questions with their solutions at one place in C++ to help every student go through this single document containing all sorts of merging problems like:-
> 
> * Insertion Sort
> * Bubble Sort
> * Selection Sort
> * Quick Sort
> * Merge Sort

Hey @Ayush7614 please assign me this underLGM-SOC'21.

**Comment by mitali-1703** [comment]
@Ayush7614 please assign me this under LGM-SOC'21

**Comment by Ayush7614** [comment]
Mitali i unassigned this issue simply first you can work on one sort so that all the participants get chance

**Comment by mitali-1703** [comment]
> Mitali i unassigned this issue simply first you can work on one sort so that all the participants get chance

Ok no problem I will add only 1 question, now can you assign me this?

**Comment by Ayush7614** [comment]
You can edit your issue or open other issue like add insertion sort in C++

**Comment by mitali-1703** [comment]
> You can edit your issue or open other issue like add insertion sort in C++

@Ayush7614 now can you assign me this under LGM-SOC'21??

**Comment by Ayush7614** [comment]
Ya it looks good nice work Mitali go Ahead

**Comment by mitali-1703** [comment]
> Ya it looks good nice work Mitali go Ahead

@Ayush7614 Thank you

**Comment by radhikaaojha** [comment]
@Ayush7614 I can add the implementation of the same through C ,Kindly Assign.

**Comment by khushboo2202** [comment]
@Ayush7614 can you assign me this issue under lgm-soc21

**Comment by radhikaaojha** [comment]
@ayush7614 @Amit366  @ravikr126  I commented Jun11,2021.Can you please assign this to me for C language?
