### ISSUE TITLE
Palindrome Partitioning (LeetCode)

### ISSUE THREAD

**Issue by akash-rajak** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2163]
Want to add solution to this leetcode problem

Input: s = "aab"
Output: [["a","a","b"],["aa","b"]]

Input: s = "a"
Output: [["a"]]

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by akash435** [comment]
@Ayush7614 please assign this to me under LGM SOC.
