### ISSUE TITLE
Reverse Linked List- LeetCode

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2168]
**Ques.**
Given the head of a singly linked list, reverse the list, and return the reversed list.

Example 1:
Input: head = [1,2,3,4,5]
Output: [5,4,3,2,1]

Example 2:
Input: head = [1,2]
Output: [2,1]

Example 3:
Input: head = []
Output: []

**Programming Language:**

- [x] C++
- [ ] C
- [ ] Java
- [ ] Python

**Comment by gunjan-g** [comment]
@sameeksharl @ravikr126 please assign me this issue under LGMSOC

**Comment by ravikr126** [comment]
Already in repo@gunjan-g
