### ISSUE TITLE
WANT TO ADD ARRAYLEVEL(BASIC AND INTERMEDIATE) IN C LANGUAGE

### ISSUE THREAD

**Issue by PalakDua-work** [Ayush7614/Daily-Coding-DS-ALGO-Practice#217]
Arrays are the most basic concept in data structures and to start up with competitive coding.
I want to add array level questions both basic and intermediate level questions in one folder.
Please assign this task to me.

I am selected as a participant inLGM-SOC'21

**Comment by PalakDua-work** [comment]
Please assign me under LGM SOC'21

**Comment by PalakDua-work** [comment]
@Ayush7614 please assign me this under LGM-SOC'21

**Comment by Ayush7614** [comment]
sorry palak i have closed ths=is issue you can add only single question like for ex "reversed array"
