### ISSUE TITLE
Implement two stack in an array

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2173]
# Aim

- will be adding solution for [Implement two stack in an array](https://practice.geeksforgeeks.org/problems/implement-two-stacks-in-an-array/1#) in Gfg/java folder.

# Details

- task is to implement  2 stacks in one array efficiently.

> Example 1:

Input:
push1(2)
push1(3)
push2(4)
pop1()
pop2()
pop2()

Output:
3 4 -1

Explanation:
push1(2) the stack1 will be {2}
push1(3) the stack1 will be {2,3}
push2(4) the stack2 will be {4}
pop1()   the poped element will be 3 
from stack1 and stack1 will be {2}
pop2()   the poped element will be 4 
from stack2 and now stack2 is empty
pop2()   the stack2 is now empty hence -1 .

### Programming language

- [ ] C
- [ ] C++
- [X] Java
- [ ] Python

**Comment by Tanya1323** [comment]
pls assign me this issue i want to do this code in c++ language

**Comment by Rounak-chauhan** [comment]
Please assign this issue to me under LGM-SoC'21 in java
@ravikr126 @sameeksharl @Amit366 @Ayush7614
