### ISSUE TITLE
 Gray Code Under LGMSOC

### ISSUE THREAD

**Issue by SnehaAgarwal361** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2179]
# Aim
I WOULD LIKE TO WORK ON THIS ISSUE USING BIT MASKING UNDER LGMSOC
# Details
 Gray Code
Medium
An n-bit gray code sequence is a sequence of 2n integers where:

Every integer is in the inclusive range [0, 2n - 1],
The first integer is 0,
An integer appears no more than once in the sequence,
The binary representation of every pair of adjacent integers differs by exactly one bit, and
The binary representation of the first and last integers differs by exactly one bit.
Given an integer n, return any valid n-bit gray code sequence.

 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by SnehaAgarwal361** [comment]
please assign me this issue @Ayush7614 @ravikr126

**Comment by ravikr126** [comment]
It already in repo @SnehaAgarwal361
