### ISSUE TITLE
Want to add the solution of all knapsack CP problems using DYNAMIC PROGRAMMING

### ISSUE THREAD

**Issue by Anshika-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#219]
I am a participant of LGM-SOC. Please assign me this issue.
Language I will be using: C++
Thank You!

**Comment by Anshika-Srivastava** [comment]
@Ayush7614 please assign me this as a part of LGMSOC'21

**Comment by Ayush7614** [comment]
First tell me this is single question or not

**Comment by Anshika-Srivastava** [comment]
This is a single type of question from which multiple CP questions can be formed. If you want I can open a separate issue for each
