### ISSUE TITLE
Spiral Order Matrix in C++

### ISSUE THREAD

**Issue by Yash-Sakre** [Ayush7614/Daily-Coding-DS-ALGO-Practice#220]
# Aim

- Print the 2D matrix in Spiral Order.

# Details

- Example : matrix = [[1,2,3],[4,5,6],[7,8,9]]
  The code Print the matrix in Spiral form like : [1,2,3,6,9,8,7,4,5]

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

I am a participant of LGM-SOC. Please assign me this issue.

**Comment by nidhi3108** [comment]
Hi I have knowledge of c++ and i am participating in LGM-Summer Of Code.
I am very eager to solve this problem. Please assign me this issue to me.

**Comment by Amit366** [comment]
@nidhi3108 u choose any other language
