### ISSUE TITLE
Expedition Problem

### ISSUE THREAD

**Issue by Shaishav0507** [Ayush7614/Daily-Coding-DS-ALGO-Practice#222]
Hey @Ayush7614,
I want to add expedition problem so please assign me to do it
Thanks...
Leave it unchecked Owner will mark it :)
-->
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by AnkitaKataria22** [comment]
@Ayush7614  pls assign me

**Comment by Shaishav0507** [comment]
Done and merged
