### ISSUE TITLE
Triangular Number 

### ISSUE THREAD

**Issue by sunilchormare** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2233]
## Aim

Triangular Number 

## Details
Given a number ***n***.Check whether it is a triangular number or not.
Note: A number is termed as a triangular number if we can represent it in the form of a triangular grid of points such that the points form an equilateral triangle and each row contains as many points as the row number, i.e., the first row has one point, the second row has two points, the third row has three points and so on.
The starting triangular numbers are 1, 3 (1+2), 6 (1+2+3), 10 (1+2+3+4).

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by sunilchormare** [comment]
Assign this issue to me, under **LGM-SoC'21**
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by sameeksharl** [comment]
Go ahead @sunilchormare
