### ISSUE TITLE
Largest Rectangular Area in a Histogram

### ISSUE THREAD

**Issue by Karnika06** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2236]
# Aim

- Find the largest rectangular area possible in a given histogram where the largest rectangle can be made of a number of contiguous bars. For simplicity, assume that all bars have same width and the width is 1 unit.
- Link to the problem: https://www.geeksforgeeks.org/largest-rectangle-under-histogram/

# Details

- I will be using stack to solve this problem with the time complexity O(n).

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

I would like to solve this problem using C++ language.
Please assign this issue to me under LGMSOC'21.

**Comment by Karnika06** [comment]
Please assign this issue to me under LGM-SoC'21
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by sameeksharl** [comment]
@Karnika06 assigned

**Comment by Rounak-chauhan** [comment]
Please assign this issue to me under LGM-SoC'21 in java
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by Amit366** [comment]
@Karnika this problem is already present in the repo
