### ISSUE TITLE
Day of the week 

### ISSUE THREAD

**Issue by sunilchormare** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2237]
## Aim

Day of the week 

## Details

Write a program that calculates the day of the week for any particular date in the past or future.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by sunilchormare** [comment]
Assign this issue to me, under LGM-SoC'21
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by sameeksharl** [comment]
Go ahead @sunilchormare
