### ISSUE TITLE
Handshakes

### ISSUE THREAD

**Issue by sunilchormare** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2239]
## Aim

Handshakes

## Details

We have **n** persons sitting on a round table. Any person can do a handshake with any other person.

![tem](https://user-images.githubusercontent.com/66204436/126896707-d807f0b2-c773-480b-94de-d418a0524ec4.PNG)

Handshake with 2-3 and 1-4 will cause cross.
In how many ways these **n** people can make handshakes so that no two handshakes cross each other. **n** would be even. 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by sunilchormare** [comment]
Assign this issue to me, under LGM-SoC'21
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by sunilchormare** [comment]
pls assign this issue to me under **LGM-SoC'21** @ravikr126 @sameeksharl

**Comment by 2000shivam659** [comment]
please assign me this in **java** language.
