### ISSUE TITLE
Maximum Array XOR

### ISSUE THREAD

**Issue by Karnika06** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2245]
# Details

- This problem was asked in Codechef Starters July challenge. 
- Problem link: https://www.codechef.com/START7C/problems/MAXARXOR/

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

I would like to work on this problem using Java language.
Please assign this issue to me under LGMSoC'21.

**Comment by Karnika06** [comment]
Please assign this issue to me under LGM-SoC'21
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by 2000shivam659** [comment]
please assign me this **java** language.

**Comment by Rounak-chauhan** [comment]
Please assign this issue to me under LGM-SoC'21 in java
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by Amit366** [comment]
@Karnika06 I am sorry this problem is already present in the repo

**Comment by Karnika06** [comment]
Hey @Amit366 , sorry but I checked it before creating issue and it is not present. It is from recent Starters July Challenge. If it is present with another name then I didn't knew about that. But please I would request you to check it once.

**Comment by Karnika06** [comment]
Since you have reopened this issue, should I create another PR? @Amit366

**Comment by Amit366** [comment]
@Karnika06 yeah
