### ISSUE TITLE
CamelCase- HackerRank

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2247]
**Ques.**
There is a sequence of words in CamelCase as a string of letters, , having the following properties:

It is a concatenation of one or more words consisting of English letters.
All letters in the first word are lowercase.
For each of the subsequent words, the first letter is uppercase and rest of the letters are lowercase.
Given s, determine the number of words in s.

**Example**
s= oneTwoThree
There are 3 words in the string: 'one', 'Two', 'Three'.

**Details:**
![image](https://user-images.githubusercontent.com/81305824/126910785-a8f4ad8f-e78c-48c8-8164-6b64dfd85e0e.png)

**Programming Language**
- [x] C++

**Comment by gunjan-g** [comment]
@ravikr126 @sameeksharl please assign this issue to me under LGMSOC

**Comment by 2000shivam659** [comment]
Please assign me this in **java** language.

**Comment by 2000shivam659** [comment]
hey, @sameeksharl what about my pull request ?
