### ISSUE TITLE
Pangrams- HackerRank

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2257]
**Ques.**
A pangram is a string that contains every letter of the alphabet. Given a sentence determine whether it is a pangram in the English alphabet. Ignore case. Return either pangram or not pangram as appropriate.

Example
s="The quick brown fox jumps over the lazy dog"
The string contains all letters in the English alphabet, so return pangram.

**Details:**
![image](https://user-images.githubusercontent.com/81305824/127040964-87571c6e-c074-414b-8a59-599fc66b3021.png)

**Programming Language:**
- [x] C++

**Comment by gunjan-g** [comment]
@sameeksharl @ravikr126 please assign this issue to me under LGMSOC

**Comment by ravikr126** [comment]
Already in repo
