### ISSUE TITLE
Maximal Rectangle (LeetCode) (Hard)

### ISSUE THREAD

**Issue by Karnika06** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2258]
# Details

- Given a rows x cols binary matrix filled with 0's and 1's, find the largest rectangle containing only 1's and return its area.
- This problem is from LeetCode. It can be solved using stack. I will be using next smallest and previous smallest element problems.
- Link to the problem: https://leetcode.com/problems/maximal-rectangle/

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

I would like to work on this issue using C++ language.
Please assign me this issue under LGMSoC'21.

**Comment by Karnika06** [comment]
Please assign this issue to me under LGM-SoC'21
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by Rounak-chauhan** [comment]
Please assign this issue to me under LGM-SoC'21 in java
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by Pratik57** [comment]
Please assign this issue to me under LGM-SoC'21 in python
@ravikr126 @sameeksharl @Amit366 @Ayush7614

**Comment by ravikr126** [comment]
> Please assign this issue to me under LGM-SoC'21 in python
> @ravikr126 @sameeksharl @Amit366 @Ayush7614

You can also work on it @Pratik57  just create pr of this question .No need to open a new issue

**Comment by Pratik57** [comment]
> > Please assign this issue to me under LGM-SoC'21 in python
> > @ravikr126 @sameeksharl @Amit366 @Ayush7614
> 
> You can also work on it @Pratik57 just create pr of this question .No need to open a new issue

No, i am not opening any new issue. In this issue if you can assign me for working in python then i can send the pull request.

**Comment by sameeksharl** [comment]
@Pratik57 go ahead

**Comment by Pratik57** [comment]
@sameeksharl Sorry but this question comes in category of hard problem atleast it should be level 3 or 2.
