### ISSUE TITLE
Check Graph whether it is Bipartite using DFS

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2263]
# Aim

- I would like to add in Data Structure Folder.

# Details

- I would like to add solution of Bipartite Graph using DFS.
- LGM-SOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@sameeksharl @Amit366 @Ayush7614 @ravikr126 Please Assign me this issue. I will solve it in C++.
LGM-SOC'21

Thank You

**Comment by sameeksharl** [comment]
@ShivanshuVishnoi go ahead

**Comment by Rounak-chauhan** [comment]
can i try in java @ShivanshuVishnoi
