### ISSUE TITLE
"Chess Format" problem of codechef

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2267]
# Aim

I want to add the code for "Chess Format" problem of codechef (Starters 7)

# Details

Problem name : Chess Format
Problem Code : CHSFORMT
Problem link : https://www.codechef.com/START7C/problems/CHSFORMT

Please assign me this issue
LGM-SOC Participant

Programming language
C++

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by manuvarghese0603** [comment]
@ravikr126  Kindly assign me this issue under LGMSOC'21

**Comment by 2000shivam659** [comment]
Please assign me this in **java** language.
