### ISSUE TITLE
"Food Chain" problem of codechef

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2268]
# Aim

- What is the objective of the Script

# Details

Problem name : Food Chain 
Problem Code : FODCHAIN
Problem link : https://www.codechef.com/START7C/problems/FODCHAIN

Please assign me this issue
LGM-SOC Participant

Programming language
C++

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by manuvarghese0603** [comment]
@ravikr126  Kindly assign me this issue under LGMSOC'21

**Comment by 2000shivam659** [comment]
Please assign me this in **java** language.
