### ISSUE TITLE
N-Queen Problem 

### ISSUE THREAD

**Issue by div0510** [Ayush7614/Daily-Coding-DS-ALGO-Practice#227]
I would like to add a code for N-queen problem under backtracking folder 
I will do this with the help of recursion.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by surajm-333** [comment]
Hi, I would like to code this solution in Java. Please assign this issue to me.

**Comment by Amit366** [comment]
@div0510 mention the language

**Comment by div0510** [comment]
I am working on this issue using C++

**Comment by Amit366** [comment]
@div0510 is it regarding permutations and combination in NQueen??

**Comment by div0510** [comment]
It is regarding backtracking

**Comment by Amit366** [comment]
Ok then go ahead.

**Comment by Amit366** [comment]
@div0510 why did u close this issue?

**Comment by div0510** [comment]
@Amit366  Sorry it was by mistake

**Comment by div0510** [comment]
Can I know my commit for n-queen using c++ was passed??

**Comment by Amit366** [comment]
Yes it is merged

**Comment by div0510** [comment]
Thank you !! Had a great experience working with you.

May I know how can I add folder since I want to add code for different types of pattern

**Comment by Amit366** [comment]
@div0510 u can create a separate issue for that and then create a folder named simple programs

**Comment by div0510** [comment]
Thanks I will surely try for this
