### ISSUE TITLE
"Ceiling Sum" problem of codechef 

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2273]
# Aim

I want to add the code for "Ceiling Sum" problem of codechef (Starters 7)

# Details

Problem name : Ceiling Sum
Problem Code : CEILSUM
Problem link : https://www.codechef.com/START7C/problems/CEILSUM

Please assign me this issue
LGM-SOC Participant

Programming language
C++

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by manuvarghese0603** [comment]
@ravikr126  Kindly assign me this issue under LGMSOC'21

**Comment by 2000shivam659** [comment]
I would like to solve this in **java** language.
