### ISSUE TITLE
"Chef and GCD" problem of codechef

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2284]
# Aim

I want to add the code for "Chef and GCD" problem of codechef (July Cook-Off)

# Details

Problem name : Chef and GCD
Problem Code : CHFGCD
Problem link : https://www.codechef.com/COOK131C/problems/CHFGCD

Please assign me this issue
LGM-SOC Participant

Programming language
C++

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by manuvarghese0603** [comment]
@ravikr126  Kindly assign me this issue under LGMSOC'21

**Comment by ravikr126** [comment]
Already in repo
