### ISSUE TITLE
Shortest Distance in Weighted graph using BFS

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2291]
# Aim

- I would like to add in Data Structure Folder.

# Details

- I would like to add solution of Shortest Distance in Weighted graph using BFS.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@sameeksharl @Amit366 @Ayush7614 @ravikr126 Please Assign me this issue. I will solve it in C++.
LGM-SOC'21

Thank You

**Comment by vilsi12** [comment]
Can you assign me in java
