### ISSUE TITLE
Strong Password- HackerRank

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2299]
**Ques.**
Louise joined a social networking site to stay in touch with her friends. The signup page required her to input a name and a password. However, the password must be strong. The website considers a password to be strong if it satisfies the following criteria:

1. Its length is at least 6.
2. It contains at least one digit.
3. It contains at least one lowercase English character.
4. It contains at least one uppercase English character.
5. It contains at least one special character. The special characters are: !@#$%^&*()-+

She typed a random string of length n in the password field but wasn't sure if it was strong. Given the string she typed, can you find the minimum number of characters she must add to make her password strong?

**Details:**
![image](https://user-images.githubusercontent.com/81305824/127738573-6961eb07-61e5-47df-b202-2d197b12db58.png)

**Programming Language:**
- [x] C++

**Comment by gunjan-g** [comment]
please assign this issue to me under LGMSOC

**Comment by inimitable034** [comment]
please assign this issue to me under LGMSOC

I can do this in java ,c++
with 0(n) time complexity

**Comment by gunjan-g** [comment]
@ravikr126 @sameeksharl please assign this issue to me under LGMSOC

**Comment by gunjan-g** [comment]
@ravikr126 @sameeksharl please assign this issue to me under LGMSOC

**Comment by inimitable034** [comment]
I also had Created a pr in c++
Shall I submit a new solution in another language? 
@ravikr126

**Comment by ravikr126** [comment]
> I also had Created a pr in c++
> Shall I submit a new solution in another language? 
> @ravikr126 

She already done in c++

**Comment by inimitable034** [comment]
Can i do in java? Or python?
