### ISSUE TITLE
Codechef problem with Problem Code - Mod Equality

### ISSUE THREAD

**Issue by inimitable034** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2301]
Codechef problem with code - Mod Equality

PROBLEM STATEMENT :-
->> You are given N non-negative integers A1,A2,…,AN. You are allowed to perform following operation any number of times:

Choose any valid index i (1≤i≤N) and a positive integer M>0 and replace Ai with AimodM. That is, replace Ai with its remainder when divided by M, which is a value between 0 and M−1, inclusive.
M does not need to be same between different operations.
Find the minimum number of operations to make all the array elements equal.

Note: Since the input and output are large, prefer using fast input-output methods.
Input Format
The first line contains an integer T - the number of test cases. Then T test cases follow.
The first line of each test case contains an integer N - the size of array.
The second line contains N integers A1,A2,…,AN - the elements of the array.
Output Format
For each test, print one line containing an integer which denotes minimum number of operations performed to make all the elements equal.

Constraints
1≤T≤104
1≤N≤105
0≤Ai≤2⋅109
It is guaranteed that the sum of N over all test cases does not exceed 106.
Sample Input 1 
2
3
2 1 3
3
1 1 3
Sample Output 1 
3
1
Explanation
In first test case, we can make all the elements equal by following operations:

Take i=1 and M=2 and do A1:=A1mod2=0.
Take i=2 and M=1 and do A2:=A2mod1=0.
Take i=3 and M=3 and do A3:=A3mod3=0.
After these 3 operations we have all the elements equal to zero.
In second test case, we can perform following operation:

Choose i=3 and M=2 and do A3:=A3mod2=1.
After this operation all the elements are 1.

- >> What is the objective of the Script

The solution to the problem in O(n) Time complexity.

LINK TO THE PROBLEM :- https://www.codechef.com/COOK131B/problems/MODEQUAL

### Programming language

- [ ] C
- [✔ ] C++
- [ ] Java
- [ ] Python

**Comment by manuvarghese0603** [comment]
issue #2008 
Question already exist

**Comment by inimitable034** [comment]
> issue #2008
> Question already exist

Question change updated

**Comment by inimitable034** [comment]
> issue #2008
> Question already exist

Question Change updated .
verify please

**Comment by inimitable034** [comment]
\assign

**Comment by inimitable034** [comment]
please assign the issue sir @manuvarghese0603

**Comment by manuvarghese0603** [comment]
> please assign the issue sir @manuvarghese0603 

@inimitable034 
Sorry but I am not a mentor.

**Comment by manuvarghese0603** [comment]
I am tagging mentors for further reference

@Amit366 @ravikr126 @Ayush7614

**Comment by manuvarghese0603** [comment]
@ravikr126 
Sir this issue was not created by me.
I don't have anything to contribute in this issue.

**Comment by inimitable034** [comment]
Thank you sir. @ravikr126

**Comment by inimitable034** [comment]
Hii sir , @ravikr126 
I have added the solution for the mod-equality question in c++.
Please review the PR.

**Comment by inimitable034** [comment]
Sir LGM SOC label is not there is this.
will it be considered or not

**Comment by inimitable034** [comment]
@Amit366

**Comment by Amit366** [comment]
The labels associated with the merged PRs will be considered
