### ISSUE TITLE
"Beautiful Pairs" problem of codechef

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2305]
# Aim

I want to add the code for "Beautiful Pairs" problem of codechef (July Lunchtime 2021)

# Details

Problem name : Beautiful Pairs
Problem Code : BUTYPAIR
Problem link : https://www.codechef.com/LTIME98C/problems/BUTYPAIR

Please assign me this issue
LGM-SOC Participant

Programming language
C++

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by manuvarghese0603** [comment]
@ravikr126  Kindly assign me this issue under LGMSOC'21

**Comment by suy1968** [comment]
Please Assign me as I am a participant of LGMSOC'21 @manuvarghese0603 @Ayush7614
I used Python3
