### ISSUE TITLE
Alternating Characters- HackerRank

### ISSUE THREAD

**Issue by gunjan-g** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2315]
**Ques.**
You are given a string containing characters A and B only. Your task is to change it into a string such that there are no matching adjacent characters. To do this, you are allowed to delete zero or more characters in the string.

Your task is to find the minimum number of required deletions.
Example
s=AABAAB
Remove an A at positions 0 and 3 to make s='ABAB' in 2 deletions.

**Details:**
![image](https://user-images.githubusercontent.com/81305824/127782498-65a12171-89cf-46f5-b4da-cdf35e35381f.png)

**Programming Language:**
- [x] C++

**Comment by gunjan-g** [comment]
please assign this issue to me under LGMSOC

**Comment by suy1968** [comment]
Please assign me this issue as I am a participant in LGMSOC'21
I used Python 3 @gunjan-g

**Comment by gunjan-g** [comment]
@sameeksharl @ravikr126 please assign this issue to me under LGMSOC

**Comment by gunjan-g** [comment]
@sameeksharl @ravikr126 please assign this issue to me under LGMSOC
