### ISSUE TITLE
Adding solution to Codeforces problem "Letters"

### ISSUE THREAD

**Issue by AKSHATNEMA** [Ayush7614/Daily-Coding-DS-ALGO-Practice#232]
This issue is part of my codeforces series of Questions and roadmap. Since a roadmap starts from beginer Questions, this is 2nd problem to this series.

Solution to this problem will be added in C++ language by me , with good explanation of logic in code. There will be necessary comments inside the solution to help understand the viewer on how the code works.

Link of the problem is:
[Letters](https://codeforces.com/contest/978/problem/C)

### Programming language

- [ ] C
- [×] C++
- [ ] Java
- [ ] Python

**Comment by AKSHATNEMA** [comment]
@Ayush7614 please assign this issue to me.

**Comment by Ayush7614** [comment]
First tell me what is the question like this is single question or you can say that you have to add Codeforces problems

**Comment by AKSHATNEMA** [comment]
It is a single Question
