### ISSUE TITLE
 Longest Consecutive Sequence

### ISSUE THREAD

**Issue by Sanskriti2401** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2325]
# Aim

![Screenshot 2021-08-03 002440](https://user-images.githubusercontent.com/75210337/127910356-7b960eee-66a3-4558-b1f4-2e41c65e8b05.png)

# Details

I would like to solve  Longest Consecutive Sequence in C++ under LGMSOC'21

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sanskriti2401** [comment]
@ravikr126 Kindly assign me this issue under LGMSOC'21

**Comment by ravikr126** [comment]
It already in repo
