### ISSUE TITLE
Basic Mathematics questions with solutions at one place in any language

### ISSUE THREAD

**Issue by mitali-1703** [Ayush7614/Daily-Coding-DS-ALGO-Practice#234]
Anyone interested can also contribute to this issue since each participant is allowed to put just 1 question with solution for 1 issue.

**Comment by mitali-1703** [comment]
@Ayush7614 Can you please assign me this under LGM-SOC'21 for C++ language??

**Comment by Ayush7614** [comment]
Mitali i will tell you na like you can opened issue with particular name of question

**Comment by mitali-1703** [comment]
Oo extremely sorry I will close this issue. I misunderstood what you said sorry for that.
