### ISSUE TITLE
XOR operation

### ISSUE THREAD

**Issue by nik464** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2346]
# Aim
Given an integer array A of N integers, find the pair of integers
in the array which have minimum XOR value and print the minimum XOR value.
        Input : arr[] =  {9, 5, 3}
        Output : 6
        All pair with xor value (9 ^ 5) => 12, 
        (5 ^ 3) => 6, (9 ^ 3) => 10.
        Minimum XOR value is 6

I want to provide the code in C++ under LGM-SOC'21
Please assign me this issue @ravikr126 sir and @Amit366 sir.

# Details

- I will make an integer array and print the pair of integers which have minimum XOR value. I will use bitwise operators.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by nik464** [comment]
please assign me this issue under LGM SOC

**Comment by ravikr126** [comment]
Already in repo
