### ISSUE TITLE
Write a program to solve Sudoku problem

### ISSUE THREAD

**Issue by surajm-333** [Ayush7614/Daily-Coding-DS-ALGO-Practice#235]
I will like to code the solution of the sudoku problem under the Backtracking folder in Java language.
Please assign this issue to me.

**Comment by Ayan-thecodeking** [comment]
hey I also want to add solution of sudoku problem in c++
please assign me this issue

**Comment by Amit366** [comment]
@Ayan-thecodeking its solved in cpp
