### ISSUE TITLE
I want to add the code for "red alert"code of codechef lunch time july 2021 in java as I  am a participant of LGMSOC'21 @manuvarghese0603 @Ayush7614

### ISSUE THREAD

**Issue by Anu2001-prog** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2369]
**AIM**
I want to add the code for "Red Alert"problem of codechef(july lunchtime 2021) in java programming language
please assign me the issue
- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python
@Ayush7614 @manuvarghese0603 

> @Anu2001-prog are u a participant of LGMSOC??

yes

**Comment by manuvarghese0603** [comment]
@Anu2001-prog 
I am not a mentor.

**Comment by Amit366** [comment]
@Anu2001-prog are u a participant of LGMSOC??
