### ISSUE TITLE
(Codeforces)112A petya and string

### ISSUE THREAD

**Issue by AmanAssassin** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2373]
Solved Question 112A of Codeforces in c++

**Comment by aniket-24** [comment]
Please Assign this issue to me, under LGM-SOC

**Comment by Harshit1123** [comment]
can I solve this issue under hacktoberfest 21?

**Comment by Abhicoder03** [comment]
Hey, Can i contribute to this issue under hacktoberfest 2021?
