### ISSUE TITLE
DataStructures_Tree: Foldable Binary Tree

### ISSUE THREAD

**Issue by aswinikalyan30** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2390]
# Aim

- To find if the binary tree is a Foldable tree or not

# Details

- Passing a binary tree, identify if the binary tree is foldable or not

### Programming language
C++

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

Please assign this issue to me

**Comment by khushijhawar** [comment]
Please assign this task to me. I would add the C++ code to find if a binary tree is foldable or not.

**Comment by Ayush7614** [comment]
Under which Program

**Comment by aswinikalyan30** [comment]
> Under which Program

Under HacktoberFest2021
