### ISSUE TITLE
Add solution of Fractional Knapsack in C++

### ISSUE THREAD

**Issue by AKSHATNEMA** [Ayush7614/Daily-Coding-DS-ALGO-Practice#241]
Fractional Knapsack is a very good question in Greedy Algorithms.I will like to add the solution of this problem in C++. 
This is part of LGM-SOC contribution

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by AKSHATNEMA** [comment]
Please assign this issue to me

**Comment by Amit366** [comment]
@AKSHATNEMA u have 5 assigned issues so after completing them you will be further assigned.

**Comment by kamleshjoshi8102** [comment]
@Ayush7614 @Amit366 Please Assign me This Issue Under LGMSOC in C++ or Java
