### ISSUE TITLE
 Minimum Size Subarray Sum (Leetcode)

### ISSUE THREAD

**Issue by Jaincode123** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2412]
**Aim**
Given an array of positive integers nums and a positive integer target, return the minimal length of a contiguous subarray [numsl, numsl+1, ..., numsr-1, numsr] of which the sum is greater than or equal to target. If there is no such subarray, return 0 instead.

### Programming language
C++

**Comment by Jaincode123** [comment]
Please assign this to me under Hacktoberfest

**Comment by DurveshKumarPal** [comment]
@Ayush7614  can you assign me this task.
