### ISSUE TITLE
Qualifying to Pre-Elimination: CodeChef Solution

### ISSUE THREAD

**Issue by jyoti-anjaly** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2427]
# Aim

- What is the objective of the Script
I want to add the solution of this problem https://www.codechef.com/SDPCB21/problems/QUALPREL  in CodeChef Folder.
Can you please assign me this issue under Hecktober fest label?

# Details

- What the features will your script have
I want to give the solution of this problem in C++. I will give the clean code with proper comments and explanation. 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by jyoti-anjaly** [comment]
@Ayush7614  Can you please assign this issue to me under Hecktoberfest?

**Comment by Dhruvil03** [comment]
Can you please assign this issue to me under Hacktoberfest?
