### ISSUE TITLE
Running Sum of 1d Array (Leetcode)

### ISSUE THREAD

**Issue by jyoti-anjaly** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2428]
# Aim

- What is the objective of the Script
- I want to give the solution of this problem on Leetcode: https://leetcode.com/problems/running-sum-of-1d-array/

# Details

- What the features will your script have
- I want to give the solution in C++ with proper clean code.
- Can you please assign this issue under Hacktoberfest?

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by jAY1jS** [comment]
### **Aim**

- Objective of Script 
- I want to contribute in this Leetcode problem. 
- Link :  [Problem](https://leetcode.com/problems/running-sum-of-1d-array/)

### **Details**

- Features of the script I will provide
- I can provide the solution in Java with clean code.
- Can you please assign me this issue under Hacktoberfest?

### **Programming language**

- [ ]  C
- [ ]  C++
- [x]  Java
- [ ]  Python

**Comment by yoursauce** [comment]
> # Details
> * I want to give the solution in python with proper clean code.
> * Can you please assign this issue under Hacktoberfest?
> 
> ### Programming language
> * [ ]  C
> * []  C++
> * [ ]  Java
> * [x]  Python

**Comment by SirAbhi13** [comment]
Can you please assign this issue to me.

 ### Programming language
 * [ ]  C
 * [ ]  C++
 * [ ]  Java
 * [x]  Python

**Comment by Sayan-Manna** [comment]
# Aim

- I want to contribute on this [problem](https://leetcode.com/problems/running-sum-of-1d-array/)

# Details

- Clean C code , please assign me on this.

### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by DurveshKumarPal** [comment]
For C++ code assign me.

**Comment by DurveshKumarPal** [comment]
#2470 Problem Solutions in java.

**Comment by DurveshKumarPal** [comment]
#2471 Problem Solutions in CPP.

**Comment by Dhruvil03** [comment]
@Ayush7614 Sir, can you please assign #2471 problem to me under Hacktober Fest?

**Comment by Gourav-s12** [comment]
can i work in this issue?
