### ISSUE TITLE
Solution of Space Arrays

### ISSUE THREAD

**Issue by Nikhita28** [Ayush7614/Daily-Coding-DS-ALGO-Practice#244]
**Problem Statement**
Finally, progress reached the Madoka family and she decided to play with her little sister in the sensational game Space Arrays.
The rules of the game are as follows:
Initially, a sequence a1,a2,…,aN is given.
The players alternate turns.
In each turn, the current player must choose an index i and increment ai, i.e. change ai to ai+1.
Afterwards, if there is no permutation p1,p2,…,pN of the integers 1 through N such that ai≤pi holds for each valid i, the current player loses.
Otherwise, the game continues with the next turn.
Madoka is asking you to help her ― tell her if the first player (the player that plays in the first turn) or second player wins this game if both play optimally.
**Input:**
4
4
1 2 3 3
4
1 1 3 3
5
1 2 2 1 5
3
2 2 3

**Output:**
First
Second
Second
Second

I would like to add the code in C++ as a part of Lgmsoc.
Link to the problem: https://www.codechef.com/MARCH21C/problems/SPACEARR

**Comment by Amit366** [comment]
@Nikhita28 I am sorry this algorithm already exists in the repo. If u want u can change the language

**Comment by Nikhita28** [comment]
Alright I'll write the code in java
