### ISSUE TITLE
Add Types of Inheritance in CPP

### ISSUE THREAD

**Issue by adityarajsahoo** [Ayush7614/Daily-Coding-DS-ALGO-Practice#2465]
# Aim

To add all types of Inheritance with code in CPP.

# Details

1. Single Inheritance
2. Multiple Inheritance
3. Multi level Inheritance
4. Hybrid Inheritance
5. Hierarchical Inheritance

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by prashun07** [comment]
@adityarajsahoo  Assign me this task under hacktoberfest . I want to complete it using C++ with proper code and documentation.
