### ISSUE TITLE
The stock span problem

### ISSUE THREAD

**Issue by jaya232** [Ayush7614/Daily-Coding-DS-ALGO-Practice#247]
I would like to solve  The stock span problem under LGM SOC'21.

Language: C++
Please assign this issue to me.

**Comment by Ayan-thecodeking** [comment]
hey I want to add the solution for span problem in c++
could you please assign this issue to me

**Comment by Amit366** [comment]
@Ayan-thecodeking u can choose any other language

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking u can choose any other language

I can also do in 

> @Ayan-thecodeking u can choose any other language
I can also do in c language ...
Please assign me now
