### ISSUE TITLE
Sort an array of 0s, 1s and 2s

### ISSUE THREAD

**Issue by neha030** [Ayush7614/Daily-Coding-DS-ALGO-Practice#248]
Given an array A[] consisting 0s, 1s and 2s. The task is to write a function that sorts the given array. The functions should put all 0s first, then all 1s and all 2s in last.

Example:
 
Input: {0, 1, 2, 0, 1, 2}
Output: {0, 0, 1, 1, 2, 2}

I am a LGM-SOC'21 Participant and want to provide C++ Solution.

**Comment by siddhi-244** [comment]
Can I try this in python? 
I am a lgmsoc participant

**Comment by kamleshjoshi8102** [comment]
Hi I am a LGM-SOC'21 Participant and want to provide C++ Solution.

**Comment by kamleshjoshi8102** [comment]
And I have one question since space is not limit here so Can I simply create 3 vectors for 0,1,2 and then print them .? 

Or 
I should do it with O(n) time complexity and O(1) Space Complexity ?

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java  as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!
