### ISSUE TITLE
Next permutation of a number

### ISSUE THREAD

**Issue by ritik-vashist** [Ayush7614/Daily-Coding-DS-ALGO-Practice#249]
Here a user enters a number and with the help of logic next possible permutation number is given as output. 

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by ritik-vashist** [comment]
@Ayush7614  sir, I would like to add the solution for this question. 
Could you please assign this task for me under LGMSOC?

**Comment by Amit366** [comment]
@ritik-vashist u can do it in one language

**Comment by Sriram-bb63** [comment]
I would like to solve this using python @Amit366 

In which folder should I create the python file?

**Comment by ritik-vashist** [comment]
@Ayush7614 @Amit366  sir, 
I request you to tell me the final decision on this. As it's showing as LGM-SOC'21 label removed even cpp label removed. 
Should I proceed with PR Or not?

**Comment by ritik-vashist** [comment]
@Ayush7614 , @Amit366 Sir,
I request you to review my PR and give your valuable feedback.

**Comment by Sriram-bb63** [comment]
Can I get assigned to this issue please. I have commented 2 days ago but I got no response. I would like to solve it using python :)
