### ISSUE TITLE
Given a number n .Find	the	number of occurrences	of n	in the array.(C LANGUAGE)

### ISSUE THREAD

**Issue by PalakDua-work** [Ayush7614/Daily-Coding-DS-ALGO-Practice#251]
Sample Input:  2
                        5
                      1 2 2 2 4
                     
Sample Output: 3
Here	n	=	2	in	the	sample	input	,	5	is	size	of	array	and	occurrence	of	2	is	3	times	in	the	given	array

Language Used: C

@Ayush7614  Please assign me this task under LGM-SOC'21
I am selected as a participant

**Comment by TasnimAnas** [comment]
I can solve it in C++

assign me to this.
LGM_SOC
