### ISSUE TITLE
Trapping rain water problem

### ISSUE THREAD

**Issue by nisha331** [Ayush7614/Daily-Coding-DS-ALGO-Practice#255]
**Trapping water problem is a leetcode hard leveled problem .**

**would try giving a easy and beginner friendly approch**

### Programming language

- C++

**Comment by nisha331** [comment]
Hey project  admins and mentors, I have created this issue and would like to work on this as a LGMSOC participant.

**Comment by Jagannath8** [comment]
Can I solve this problem in Java. I'm a participant of LGM-SOC'21

**Comment by Ayush7614** [comment]
Issue was already opened so I will close this issue
