### ISSUE TITLE
Maximize the sum of selected numbers from an array to make it empty 

### ISSUE THREAD

**Issue by PriyankaHotchandani** [Ayush7614/Daily-Coding-DS-ALGO-Practice#257]
As a participant of LGM-SOC'21, I want to provide the solution to this medium-level competitive programming problem in C++.

Maximize the sum of selected numbers from an array to make it empty.
Input : arr[ ] = {1, 2, 2, 2, 3, 4}
Output : 10

**Comment by Jagannath8** [comment]
Can I solve this problem in Java. I'm a participant of LGM-SOC'21
