### ISSUE TITLE
Union of two sorted array 

### ISSUE THREAD

**Issue by Amit-45** [Ayush7614/Daily-Coding-DS-ALGO-Practice#268]
@Ayush7614 @Amit366 Please assign me this issue I would like to solve this question as a part of the LGM-SOC'21 contest.

Given two sorted arrays, find their union .
Example:

Input : arr1[] = {1, 2, 4, 5}
        arr2[] = {2, 3, 5, 6} 
Output : Union : {1, 2, 3, 4, 5, 6,} 

I will be using CPP.

**Comment by suy1968** [comment]
Problem statement:-
Given 2 sorted arrays, find all the elements which occur in both the arrays.
Input :
arr1 = [1, 2, 4, 5, 6] 
arr2 = [2, 3, 5, 7] 

Output : [1,2,3,4,5,6,7]
I am using Python3
I would like to solve this question as a part of the LGM-SOC'21 participants.
