### ISSUE TITLE
Intersection of two sorted arrays 

### ISSUE THREAD

**Issue by Amit-45** [Ayush7614/Daily-Coding-DS-ALGO-Practice#269]
@Ayush7614 @Amit366 Please assign me this issue I would like to solve this question as a part of the LGM-SOC'21 contest.

Given two sorted arrays, find their intersection .
Example:

Input : arr1[] = {1, 2, 4, 5}
arr2[] = {2, 3, 5}
Output : Intersection : {2, 5}

I will be using CPP.

**Comment by suy1968** [comment]
Problem Statement:- 
Given two integer arrays nums1 and nums2, return an array of their intersection. Each element in the result must be unique and you may return the result in any order
Input: nums1 = [4,9,5], nums2 = [9,4,9,8,4]
Output: [9,4]
Explanation: [4,9] is also accepted.
I would like to solve this question as a part of the LGM-SOC'21 participant

**Comment by suy1968** [comment]
Problem statement:-
Given 2 sorted arrays, find all the elements which occur in both the arrays.
Input : 
    A : [1 2 3 3 4 5 6]
    B : [3 3 5]

Output : [3 3 5]
I would like to solve this question as a part of the LGM-SOC'21 participants.

**Comment by Amit366** [comment]
@suy1968 mention the language

**Comment by suy1968** [comment]
> @suy1968 mention the language

Mentioned

**Comment by mayankmohak** [comment]
@Ayush7614 @Amit366 Please assign me this issue I would like to solve this question as a part of the LGM-SOC'21 contest.

Given two sorted arrays, find their intersection .
Example:

Input : arr1[] = {1, 2, 4, 5}
arr2[] = {2, 3, 5}
Output : Intersection : {2, 5}

I will be providing the solution in JAVA.
