### ISSUE TITLE
SUMMER HEAT QUESTION ON CODECHEF(June Challenge 2021 Division 3)

### ISSUE THREAD

**Issue by arpitgoyal27** [Ayush7614/Daily-Coding-DS-ALGO-Practice#274]
Chefland has 2 different types of coconut, type A and type B. Type AA contains only xa milliliters of coconut water and type B contains only xb grams of coconut pulp. Chef's nutritionist has advised him to consume Xa milliliters of coconut water and Xb grams of coconut pulp every week in the summer. Find the total number of coconuts (type A + type B) that Chef should buy each week to keep himself active in the hot weather.

Input
The first line contains an integer T, the number of test cases. Then the test cases follow.
Each test case contains a single line of input, four integers xa, xb, Xa,  Xb

Output
For each test case, output in a single line the answer to the problem.

I will use c++ as a part of LGMSOC.

Probelm Link- https://www.codechef.com/JUNE21C/problems/COCONUT

**Comment by AKSHATNEMA** [comment]
@arpitgoyal27 please don't submit the solutions to those questions which are part of ongoing contests. CodeChef considers it illegal and against its Code of Conduct. If you want to submit it, do it after the contest ends.
