### ISSUE TITLE
Pattern23  (codechef)

### ISSUE THREAD

**Issue by arpitgoyal27** [Ayush7614/Daily-Coding-DS-ALGO-Practice#278]
The chef is trying to solve some pattern problems, Chef wants your help to code it. Chef has one number K to form a new pattern. Help the chef to code this pattern problem

Input:
First-line will contain T, the number of test cases. Then the test cases follow.
Each test case contains a single line of input, one integer K.
Output:
For each test case, output as the pattern.

I will use c++.

Problem link: https://www.codechef.com/problems/ITGUY95

**Comment by suy1968** [comment]
Problem statement:-
The chef is trying to solve some pattern problems, Chef wants your help to code it. Chef has one number K to form a new pattern. Help the chef to code this pattern problem.

Input:
First-line will contain T, the number of test cases. Then the test cases follow.
Each test case contains a single line of input, one integer K.

Output:
For each test case, output as the pattern.
Sample Input:
2
5
6
Sample Output:
    (*)    
   ((*))   
  (((*)))  
 ((((*)))) 
(((((*)))))
     (*)     
    ((*))    
   (((*)))   
  ((((*))))  
 (((((*))))) 
((((((*))))))

I will use python3 

problem link:- https://www.codechef.com/problems/ITGUY95

**Comment by arpitgoyal27** [comment]
@suy1968  create a new issue because I don't think that we can add c++ and python labels in the same issue.
