### ISSUE TITLE
Covid Analyzer (codechef)

### ISSUE THREAD

**Issue by arpitgoyal27** [Ayush7614/Daily-Coding-DS-ALGO-Practice#280]
As the COVID-19 Pandemic is on it's Peak in India. The total number of Covid cases are increasing day by day. The Following series shows the number of cases on a particular day.
1,2,3,5,8,13,21,34,55,89,144,….
On the 1st Day the total cases where 1, on second day total cases where 2 , on third day 3 and so on.
You have to write a program which will calculate the total number of cases on the Nth day. According to the above series.

**Input:**
First line will contain T, number of testcases. Then the testcases follow.
Each testcase contains of a single integer as input, N i.e Nth day.
**Output:**
For each testcase, output in a single line answer with total number of cases on Nth day.

**Sample Input:**
1
12
**Sample Output:**
233

I will use c++.
Problem Link: https://www.codechef.com/SHAK2021/problems/COVIN/

**Comment by Debargha-arch** [comment]
@Amit366 can you assign this same problem to me in Java? LGM-SOC'21

**Comment by ShivanshuVishnoi** [comment]
@Amit366 can you assign me this problem to solve in c++. 
LGM SOC'21

**Comment by ShivanshuVishnoi** [comment]
I created  a pull request. Please review the solution
Thank you

**Comment by Amit366** [comment]
@ShivanshuVishnoi u aren't assigned then how can u send the PR

**Comment by Debargha-arch** [comment]
@Amit366 why is my PR closed?

**Comment by Amit366** [comment]
@Debargha-arch it is not closed

**Comment by Debargha-arch** [comment]
Please merge my PR
