### ISSUE TITLE
Adjacent Difference Algorithm

### ISSUE THREAD

**Issue by agamgupta2015** [Ayush7614/Daily-Coding-DS-ALGO-Practice#286]
**Describe the solution you'd like**
The adjacent_difference algo produces a new sequence in which each element is difference between adjacent elements in original sequence.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by agamgupta2015** [comment]
Please assign this issue to me

**Comment by mdinesh124** [comment]
I want to add solution to this in Java under LGMSOC.
@Ayush7614 @Amit366 please assign me this.

**Comment by Yakshit310** [comment]
Hi I'm an LGM SOC participant and would like to work on this in C++ language. It would be great if this could be assigned to me.

**Comment by Amit366** [comment]
@Yakshit310 it's already assigned . U can choose other language

**Comment by Yakshit310** [comment]
@Amit366 can I try JavaScript?

**Comment by Amit366** [comment]
@Yakshit310 no JS

**Comment by Yakshit310** [comment]
@Amit366 Python ?
