### ISSUE TITLE
Add Sieve of Eratosthenes

### ISSUE THREAD

**Issue by sonalsingh25** [Ayush7614/Daily-Coding-DS-ALGO-Practice#309]
**Is your feature request related to a problem? Please describe.**
Add Sieve of Eratosthenes program in java language in Data Structures folder.

**Describe the solution you'd like**
Problem Statement : 
Given a number n, print all primes smaller than or equal to n. It is also given that n is a small number. 

Example: 

Input : n =10
Output : 2 3 5 7 

Input : n = 20 
Output: 2 3 5 7 11 13 17 19
**Describe alternatives you've considered**

**Additional context**
Hi I'm an LGM SOC participant and would like to work on this in Java language. It would be great if this could be assigned to me.
### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by jayant766** [comment]
Please, assign me this.

**Comment by kamleshjoshi8102** [comment]
Please Assign me this.

**Comment by kamleshjoshi8102** [comment]
Hi I'm an LGM SOC participant and would like to work on this in C++ language. It would be great if this could be assigned to me.

**Comment by Yakshit310** [comment]
I want to add a solution to this in Python under LGMSOC.
