### ISSUE TITLE
Diameter of a tree in C++

### ISSUE THREAD

**Issue by Debashish-hub** [Ayush7614/Daily-Coding-DS-ALGO-Practice#315]
**Is your feature request related to a problem? Please describe.**

Given a Binary Tree, find diameter of it.
The diameter of a tree is the number of nodes on the longest path between two end nodes in the tree. 

**Describe the solution you'd like**
I will solve it in C++

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Amit366** [comment]
@Debashish-hub This issue already exists
