### ISSUE TITLE
WANT TO ADD CODECHEF INTERVIEW QUESTION

### ISSUE THREAD

**Issue by tech-rounak** [Ayush7614/Daily-Coding-DS-ALGO-Practice#317]
# Aim

- What is the objective of the Script

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by tech-rounak** [comment]
@Amit366  please assign me

**Comment by Amit366** [comment]
@tech-rounak bro u cannot ask for all the questions at a time. You need to add separate issues for each. Check out the instructions in slack
