### ISSUE TITLE
Buy and Sell stock Problem

### ISSUE THREAD

**Issue by harshpreet0508** [Ayush7614/Daily-Coding-DS-ALGO-Practice#318]
I am a LGM-SOC participant and I want to contribute the code of Buy and sell stock problem in C++.

Description: You are given an integer array prices where prices[i] is the price of a given stock on the ith day, and an integer k.
Find the maximum profit you can achieve. You may complete at most k transactions.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by suy1968** [comment]
Problem Description

Say we have an array, A, for which the ith element is the price of a given stock on day i.
If you were only permitted to complete at most one transaction (i.e, buy one and sell one share of the stock), design an algorithm to find the maximum profit.

Return the maximum possible profit.


Example Input
Input :

 A = [1, 2]

Example Output
Output :
 1

**Comment by Amit366** [comment]
@suy1968 u already have 5 assigned issues. So send the PRs and after that u can be assigned

**Comment by toth2000** [comment]
I would like to create a PR for the JAVA part.

**Comment by shruti29s** [comment]
I can do this in java. Please assign this to me.

**Comment by kumarshobhit** [comment]
I would like to contribute in java language
