### ISSUE TITLE
Good or Bad string in c++

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#323]
# Aim

- to add [Good or Bad String]() gfg problem in c++ language
 
# Details

- It tells whether a number is good or bad on some criteria:
If there are more than 3 consonants together or more than 5 vowels together, the String is considered to be "BAD". A String is considered "GOOD" only if it is not “BAD `?` is a wildcard character”

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Simar05519** [comment]
Please assign me this issue . I will work using C++

**Comment by UG-SEP** [comment]
> Please assign me this issue. I will work using C++

Well I have open the issue first but if you want to do it in c++ then ok
I will do it in c language

**Comment by Simar05519** [comment]
Ohh sorry I was not knowing. Well it would be mentor's decision. Wait for it

**Comment by Amit366** [comment]
@Simar05519 u can work in other language

**Comment by Rolly120** [comment]
Sir I would like to solve the issue using Python. Please assign it to me.

**Comment by Simar05519** [comment]
Till which date I have to submit this code?

**Comment by Simar05519** [comment]
@Amit366 should I have to do this in c++ or not?

**Comment by Amit366** [comment]
@Simar05519 it's done in cpp. If u want do in C

**Comment by TasnimAnas** [comment]
@Amit366 I want to solve this in JAVA. Assign me

**Comment by 7JKaushal** [comment]
I'd love to try this in C
