### ISSUE TITLE
Length Of Longest Substring

### ISSUE THREAD

**Issue by Drishty06** [Ayush7614/Daily-Coding-DS-ALGO-Practice#334]
1. Problem link: https://practice.geeksforgeeks.org/problems/length-of-the-longest-substring3036/1/?category[]=sliding-window&category[]=sliding-window&difficulty[]=1&page=1&sortBy=submissions&query=category[]sliding-windowdifficulty[]1page1sortBysubmissionscategory[]sliding-window
2. Problem: Given a string S, find the length of the longest substring without repeating characters
3. Platform: Gfg
4. language: C++

**Comment by Drishty06** [comment]
Mentors, can you please assign this to me?

**Comment by Amit366** [comment]
@Drishty06 this issue is already taken up by others

**Comment by Drishty06** [comment]
ok sir
