### ISSUE TITLE
Merge two arrays without Any Extra Space

### ISSUE THREAD

**Issue by Drishty06** [Ayush7614/Daily-Coding-DS-ALGO-Practice#336]
1. Problem link: https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1#
2.  Problem: Given two sorted arrays arr1[] of size N and arr2[] of size M. Each array is sorted in non-decreasing order. Merge the two arrays into one sorted array in non-decreasing order without using any extra space.
3. Platform: gfg
4. Language: C++

**Comment by Drishty06** [comment]
Can You please assign this to me?

**Comment by Drishty06** [comment]
I have generated PR for the same, kindly review it

**Comment by jatinjain001** [comment]
I want to take this issue , if its available
