### ISSUE TITLE
Binary_Tree_Symmetric_or_not

### ISSUE THREAD

**Issue by muthuannamalai12** [Ayush7614/Daily-Coding-DS-ALGO-Practice#341]
To check whether a binary tree is symmetric or not in C++. I would love to work on this issue. Kindly assign it to me as a part of LGMSOC

**Comment by AtrikGit6174** [comment]
I would like to add a recursive solution for this problem in the LeetCode folder. Can I be assigned please?

@Amit366 @ravikr126 @Ayush7614
