### ISSUE TITLE
Implement the basic functionality of stack using Array Data structure

### ISSUE THREAD

**Issue by muthuannamalai12** [Ayush7614/Daily-Coding-DS-ALGO-Practice#343]
I would love to Implement the basic functionality of the stack using Array Data structure in C++. I would love to work on this issue as a part of LGMSOC

**Comment by mdinesh124** [comment]
I want to implement the basic functionality of the stack in Java under LGMSOC
@Ayush7614 please assign me this.

**Comment by Amit366** [comment]
@muthuannamalai12 this issue is already taken up up others
