### ISSUE TITLE
Isomorphic Strings in C++

### ISSUE THREAD

**Issue by Debashish-hub** [Ayush7614/Daily-Coding-DS-ALGO-Practice#353]
**Is your feature request related to a problem? Please describe.**

 Given two strings 'str1' and 'str2', check if these two strings are isomorphic to each other.
 Two strings str1 and str2 are called isomorphic if there is a one to one mapping possible for  every character of str1 to every character of str2 while preserving the order.

**Describe the solution you'd like**
I will solve it in C++

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by AliHaider20** [comment]
I would like to solve this in C and Python.

**Comment by Ayush7614** [comment]
We will close this issue

**Comment by Ayush7614** [comment]
We will close this issue
