### ISSUE TITLE
Longest Common Subsequence - Leetcode(Medium)

### ISSUE THREAD

**Issue by Anshika-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#358]
### I would like to provide my C++ code for this question:
Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.

A subsequence of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.

For example, "ace" is a subsequence of "abcde".
A common subsequence of two strings is a subsequence that is common to both strings.

**Please assign me this under LGMSOC'21
Thank You**

**Comment by jayant766** [comment]
Please assign it to me.

**Comment by TasnimAnas** [comment]
@Amit366 I want to solve this in C language. Assign me

**Comment by kumarshobhit** [comment]
I would like to contribute in java language

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in python as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!
