### ISSUE TITLE
Max Area of Land - Leetcode(Medium)

### ISSUE THREAD

**Issue by Anshika-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#359]
### I would like to provide my C++ code for this question:
You are given an m x n binary matrix grid. An island is a group of 1's (representing land) connected 4-directionally (horizontal or vertical.) You may assume all four edges of the grid are surrounded by water.

The area of an island is the number of cells with a value 1 in the island.

Return the maximum area of an island in grid. If there is no island, return 0.

**Please assign me this issue under LGMSOC'21
Thank You**

**Comment by kumarshobhit** [comment]
I would like to contribute in java language

**Comment by kamleshjoshi8102** [comment]
@Amit366 I would Like to contribute in python language under LGMSOC
