### ISSUE TITLE
Counting Comparisons in Bubble Sort

### ISSUE THREAD

**Issue by shreyansh30saxena** [Ayush7614/Daily-Coding-DS-ALGO-Practice#367]
Counting number of comaprisons and swaps that occur in bubble sort.
Program will run at different intervals of size with input examples of best, worst and average case.

**Comment by agamgupta2015** [comment]
@Amit366 please assign this issue to me I will do it C++ language

**Comment by shreyansh30saxena** [comment]
@Amit366 this issue has already been assigned to me.
I also made PR but I made a combined PR, so that's why I raised it again so that I can have separate PRs.

**Comment by agamgupta2015** [comment]
Ok i will do it Java Language
