### ISSUE TITLE
Next Permutation

### ISSUE THREAD

**Issue by pritmanvar** [Ayush7614/Daily-Coding-DS-ALGO-Practice#372]
* Problem Link : https://leetcode.com/problems/next-permutation/
* Problem : Implement next permutation, which rearranges numbers into the lexicographically next greater permutation of numbers.
If such an arrangement is not possible, it must rearrange it as the lowest possible order (i.e., sorted in ascending order).
The replacement must be in place and use only constant extra memory.
* Platform : LeetCode
* Language : C++

**Comment by pritmanvar** [comment]
Please assign this to me

**Comment by Amit366** [comment]
@pritmanvar this is already been assigned to other
