### ISSUE TITLE
Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by pritmanvar** [Ayush7614/Daily-Coding-DS-ALGO-Practice#376]
* Problem : There is an integer array nums sorted in ascending order (with distinct values).

 Prior to being passed to your function, nums is rotated at an unknown pivot index k (0 <= k < nums.length) such that the 
 resulting array is [nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]] (0-indexed). For example, 
 [0,1,2,4,5,6,7] might be rotated at pivot index 3 and become [4,5,6,7,0,1,2].

 Given the array nums after the rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in 
 nums.
 
You must write an algorithm with O(log n) runtime complexity.
* Problem Link : https://leetcode.com/problems/search-in-rotated-sorted-array/
* Platform : LeetCode
* Language : C++

**Comment by pritmanvar** [comment]
Please assign this to me

**Comment by siddhi-244** [comment]
Can I do this in c++?

**Comment by kumarshobhit** [comment]
I would like to contribute in java language

**Comment by siddhi-244** [comment]
@Amit366  can I try this in python ?
