### ISSUE TITLE
n-Queen Backtracking Problem can be done in c++ with all the permutation possible can also be printed

### ISSUE THREAD

**Issue by Kabirdutt** [Ayush7614/Daily-Coding-DS-ALGO-Practice#382]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Amit366** [comment]
@Kabirdutt this issue is already solved
