### ISSUE TITLE
counting sundays

### ISSUE THREAD

**Issue by pooja906** [Ayush7614/Daily-Coding-DS-ALGO-Practice#388]
# Aim

https://www.hackerrank.com/contests/projecteuler/challenges/euler019/problem
-How many Sundays fell on the first of the month between two dates(both inclusive)?

# Details

I want to solve this in the java language. Kindly assign me this.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Amit366** [comment]
@pooja906 this algo is already in the repo
