### ISSUE TITLE
Added questions in Java Language

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Daily-Coding-DS-ALGO-Practice#4]

**Comment by Amrutha1101** [comment]
Hey @Ayush7614, I'm a LGM-SOC'21 participant. I write logic for DSA problems in Java. 
So I would like to contribute here from June 10th. Can you assign me this task?

**Comment by Sakalya100** [comment]
Hello @Ayush7614 . Please assign this to me under the programme of LGMSoc. I want to contribute to this .

**Comment by Amrutha1101** [comment]
Hey!
I'm switching over development. So I have deleted the comment I posted.

**Comment by tannu945** [comment]
Hey @Ayush7614 , I want to contribute in this issue. Please assign me this.

**Comment by Ayush7614** [comment]
Go Ahead @tannu945 @Sakalya100
