### ISSUE TITLE
Insertion Sort using Call By Reference method

### ISSUE THREAD

**Issue by TasnimAnas** [Ayush7614/Daily-Coding-DS-ALGO-Practice#400]
**Problem**
write a code to sort an array using the Insertion Sort algorithm by Call By Reference method. (LGM SOC)

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by TasnimAnas** [comment]
Please assign me on this (LGM SOC)

**Comment by mitali-1703** [comment]
I want to add Java solution to this problem. Please assign me this under LGM-SOC'21 @Amit366 .

**Comment by jayant766** [comment]
I can do this in python.

Assign me plz.
LGM_SOC
