### ISSUE TITLE
Concatenated Words

### ISSUE THREAD

**Issue by shantamsultania** [Ayush7614/Daily-Coding-DS-ALGO-Practice#404]
# Aim

Find all words that are concatenations of a list.

Input:
["tech", "lead", "techlead", "cat", "cats", "dog", "catsdog"]

Output:
['techlead', 'catsdog']

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by shantamsultania** [comment]
if possible Please assign me on this (LGM SOC) @Amit366

**Comment by Ayan-thecodeking** [comment]
I want to add code for concatenated words in C++ language 
please assign me this @amit366

**Comment by mdinesh124** [comment]
@Amit366  Please assign me this issue under LGMSOC. I will code it in python.
