### ISSUE TITLE
I want to add solution to Codeforces Problem

### ISSUE THREAD

**Issue by kamleshjoshi8102** [Ayush7614/Daily-Coding-DS-ALGO-Practice#405]
# Aim

Want to add solution to a Codeforces Problem 
https://codeforces.com/contest/977/problem/C

# Details

Efficient And beginner Friendly Solution to this problem

You are given a sequence of integers of length n and integer number k. You should print any integer number x in the range of [1;109] (i.e. 1≤x≤109) such that exactly k elements of given sequence are less than or equal to x.

Note that the sequence can contain equal elements.

If there is no such x, print "-1" (without quotes).

Tag: Sorting , 1200

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by girija0707** [comment]
will you please assign this to me in c++

**Comment by kamleshjoshi8102** [comment]
hi @girija0707 I have asked admin to assign this issue to me you are doing it in wrong way just try to create your own issue and then ask permission from admin to add

**Comment by Yakshit310** [comment]
@Amit366 can I do this in Python ?
