### ISSUE TITLE
I would Love to Provide Solution to this Question 

### ISSUE THREAD

**Issue by kamleshjoshi8102** [Ayush7614/Daily-Coding-DS-ALGO-Practice#408]
# Aim

I would Love to Provide Solution of this Problem Under LGMSOC in C++

# Details

Pashmak decided to give Parmida a pair of flowers from the garden. There are n flowers in the garden and the i-th of them has a beauty number bi. Parmida is a very strange girl so she doesn't want to have the two most beautiful flowers necessarily. She wants to have those pairs of flowers that their beauty difference is maximal possible!

Your task is to write a program which calculates two things:

1. The maximum beauty difference of flowers that Pashmak can give to Parmida.
2. The number of ways that Pashmak can pick the flowers. Two ways are considered different if and only if there is at least one flower that is chosen in the first way and not chosen in the second way.

Problem Link : https://codeforces.com/contest/459/problem/B

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
Sorry we have closed this issue first you have to work on one issue

**Comment by kamleshjoshi8102** [comment]
> Sorry we have closed this issue first you have to work on one issue

I have Merged it sir can I Work on this Issue now ?
