### ISSUE TITLE
I would Love to Provide Solution to this Interesting Codeforces Problem under LGMSoc 

### ISSUE THREAD

**Issue by kamleshjoshi8102** [Ayush7614/Daily-Coding-DS-ALGO-Practice#411]
# Aim

Efficient And Beginner Friendly Solution to this Problem in C++ 
https://codeforces.com/contest/570/problem/B

# Details

One day Misha and Andrew were playing a very simple game. First, each player chooses an integer in the range from 1 to n. Let's assume that Misha chose number m, and Andrew chose number a.

Then, by using a random generator they choose a random integer c in the range between 1 and n (any integer from 1 to n is chosen with the same probability), after which the winner is the player, whose number was closer to c. The boys agreed that if m and a are located on the same distance from c, Misha wins.

Andrew wants to win very much, so he asks you to help him. You know the number selected by Misha, and number n. You need to determine which value of a Andrew must choose, so that the probability of his victory is the highest possible.

More formally, you need to find such integer a (1 ≤ a ≤ n), that the probability that  is maximal, where c is the equiprobably chosen integer from 1 to n (inclusive).

Tags:  constructive algorithms , games  ,  greedy  ,  implementation  ,  math  ,  *1300

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by girija0707** [comment]
will you assign this to me in c++

**Comment by kamleshjoshi8102** [comment]
@Ayush7614 sir Can you review the labels : )

**Comment by Yakshit310** [comment]
@Amit366 Hi I'm an LGM SOC participant and would like to work on this in python language. It would be great if this could be assigned to me.
