### ISSUE TITLE
I would Love to Add Solution to this Codeforces Problem

### ISSUE THREAD

**Issue by kamleshjoshi8102** [Ayush7614/Daily-Coding-DS-ALGO-Practice#414]
# Aim

Beginner Friendly and Efficient Solution in C++

Link : https://codeforces.com/contest/454/problem/B

# Details

One day, Twilight Sparkle is interested in how to sort a sequence of integers a1, a2, ..., an in non-decreasing order. Being a young unicorn, the only operation she can perform is a unit shift. That is, she can move the last element of the sequence to its beginning:

a1, a2, ..., an → an, a1, a2, ..., an - 1.
Help Twilight Sparkle to calculate: what is the minimum number of operations that she needs to sort the sequence?

Tags:   implementation , *1200

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by siddhi-244** [comment]
can i do it in c++?

**Comment by girija0707** [comment]
will you please this to me

**Comment by girija0707** [comment]
will you please assign this to me

**Comment by Ayush7614** [comment]
First all of you complete your previous issue then we will assign you

**Comment by siddhi-244** [comment]
I have completed all issues assigned ! @Ayush7614

**Comment by Amit366** [comment]
@siddhi-244 choose different language

**Comment by siddhi-244** [comment]
Can I try in python?

**Comment by siddhi-244** [comment]
@Amit366 python ?

**Comment by AnkitaKataria22** [comment]
assign me this issue

**Comment by Yakshit310** [comment]
@Amit366  Hi I'm an LGM SOC participant and would like to work on this in C language. It would be great if this could be assigned to me.
