### ISSUE TITLE
Interpolation search

### ISSUE THREAD

**Issue by rakesh419s** [Ayush7614/Daily-Coding-DS-ALGO-Practice#422]
# Aim

- searching an element in an array very efficiently than the binary search

# Details

- in very less number of comparisons we can get the element index 

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- . Python

**Comment by vijay-pro-hash** [comment]
can you assign this to me in python #422

**Comment by rakesh419s** [comment]
could you assign this to me in python #422

**Comment by Kartikey0205** [comment]
Hey @Ayush7614  would you please assign me this in C++ Language 

> # Aim
> * searching an element in an array very efficiently than the binary search
> 
> # Details
> * in very less number of comparisons we can get the element index
> 
> ### Programming language
> * [ ]  C
> * [x]  C++
> * [ ]  Java
> * [ ] Python

**Comment by mitali-1703** [comment]
@Amit366 can you assign me this in C language under LGM-SOC'21?

**Comment by rakesh419s** [comment]
could you assign me the above statement in java under LGM-SOC'21
