### ISSUE TITLE
Rat In Maze Java

### ISSUE THREAD

**Issue by surajm-333** [Ayush7614/Daily-Coding-DS-ALGO-Practice#423]
For a 3x3 matrix, if the rat is initially at (0,0) position and it wants to reach at position (2,2) then print all the ways in which the rat can reach the endpoint of the maze. The rat can move only in horizontal or vertical directions.

For example:
Input: 
Starting row: 0
Starting col: 0
Ending row: 2
Ending col: 2

Output:
HHVV
HVHV
HVVH
VHHV
VHVH
VVHH

Please assign this issue to me under LGM SOC21

**Comment by surajm-333** [comment]
Please assign this issue to me @Amit366 @Ayush7614

**Comment by Amit366** [comment]
@surajm-333 u can use other languages except for cpp

**Comment by Kartikey0205** [comment]
Hey @Ayush7614 would you assign me this under Lgm-soc'21 in Python language
