### ISSUE TITLE
Bubble Sort in Java

### ISSUE THREAD

**Issue by sonalsingh25** [Ayush7614/Daily-Coding-DS-ALGO-Practice#427]
**Is your feature request related to a problem? Please describe.**
Bubble Sort is the simplest sorting algorithm that works by repeatedly swapping the adjacent elements if they are in wrong order.

**Describe the solution you'd like**
I want to add the code for bubble Sort in Data Structures Folder
**Describe alternatives you've considered**

**Additional context**
Input : 64, 34, 25, 12, 22, 11, 90
Output :
 Sorted array:
11 12 22 25 34 64 90
I'm an LGM SOC participant, I would like to work on this . Please assign it to me.
### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by siddhi-244** [comment]
can i do in c++

**Comment by TasnimAnas** [comment]
I can do it in C and C++
Assign me, I'm LGMSOC participant

**Comment by agamgupta2015** [comment]
I want to work in python in this issue

**Comment by Jagannath8** [comment]
I can do it in Java
I'm LGM-SoC participant

**Comment by Kartikey0205** [comment]
@Amit366 please assign me this!

**Comment by Amit366** [comment]
@TasnimAnas do in C

**Comment by TasnimAnas** [comment]
> @TasnimAnas do in C

Check PR #621

**Comment by geekySapien** [comment]
I can do this in C++, sir could you please assign this issue
