### ISSUE TITLE
Armstrong Number

### ISSUE THREAD

**Issue by sonalsingh25** [Ayush7614/Daily-Coding-DS-ALGO-Practice#430]
**Is your feature request related to a problem? Please describe.**
To write a program to check if a number is armstrong or not

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I'm an LGM SOC participant, I would like to work on this . Please assign it to me.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ritikkumar992** [comment]
Assign me this task

**Comment by TasnimAnas** [comment]
I can do it in C and C++
Assign me, I'm LGMSOC participant

**Comment by Jagannath8** [comment]
I can do it in Java
I'm LGM-SoC participant

**Comment by Komal-99** [comment]
hi ,I am LGMSOC participant and would like to add armstrong number in python kindly assign it to me.

**Comment by RHEA211** [comment]
This can be done by me in C++
Kindly assign this to me

**Comment by Kartikey0205** [comment]
Assign me this task with python @Amit366

**Comment by Amit366** [comment]
@sonalsingh25 u already have 5 assigned issues

**Comment by Amit366** [comment]
@Ritikkumar992 mention the language

**Comment by Amit366** [comment]
@TasnimAnas do in C

**Comment by Amit366** [comment]
@Ritikkumar992 do in Cpp

**Comment by TasnimAnas** [comment]
> @TasnimAnas do in C

Check PR #618

**Comment by Komal-99** [comment]
I am doing it in python

**Comment by Komal-99** [comment]
In which folder I have to add the code for this?

**Comment by TasnimAnas** [comment]
> In which folder I have to add the code for this? @Amit-45

GFG has this problem listed on their site. I've added it in gfg folder. ( https://practice.geeksforgeeks.org/problems/armstrong-numbers2727/1 )

**Comment by Komal-99** [comment]
> In which folder I have to add the code for this? @Amit-45

@Amit-45 ?
