### ISSUE TITLE
can i implement reverse the link list in c++?

### ISSUE THREAD

**Issue by richabh456** [Ayush7614/Daily-Coding-DS-ALGO-Practice#432]
# Aim

- What is the objective of the Script

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Jagannath8** [comment]
Can I implement it in Java. 
I'm a participant of LGM-SOC'21

**Comment by Kashish05** [comment]
I want to contribute solution for it in C++. Pls assign it to me.
