### ISSUE TITLE
5 different types of sort 

### ISSUE THREAD

**Issue by simarjeet30** [Ayush7614/Daily-Coding-DS-ALGO-Practice#436]
# Aim: I would add 5 types of sort with complete documentation and examples.

- My 5 types of sort would be 
- Bubble sort
- Merge sort
- Quick sort
- Insertion sort
- Selection sort

# This would give a choice to everyone to choose from 5 different types of sort to implement in their code.

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by rakesh419s** [comment]
assign me i can do it in python

**Comment by shrutigrover25** [comment]
I want to add contributor's to 5 different types of sort issue. Please assign me as a part of LGMSOC.

**Comment by Ayush7614** [comment]
Issues was already opened for every sort
