### ISSUE TITLE
Problems of Codechef DSA Learning Series 

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#438]
# Aim
I want to add the code for codechef DSA Learning Series 

# Details

Problem name : Coin Flip
Problem Code : CONFLIP
Problem link : https://www.codechef.com/LRNDSA01/problems/CONFLIP 

Please assign me this issue 
LGM-SOC Participant 

### Programming language
C++
Leave it unchecked Owner will mark it :)
-->
- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
Plss open particular question issues not full series so opened new issue
