### ISSUE TITLE
Snakes and Ladders

### ISSUE THREAD

**Issue by Shaishav0507** [Ayush7614/Daily-Coding-DS-ALGO-Practice#442]
# Aim

Hey @Ayush7614,
I want to add Snakes and Ladders problem, so please assign me to do it
Thanks...

# Details

- Proper Code with proper Explanation.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
Not accepting this type question
