### ISSUE TITLE
searching largest and smallest in array

### ISSUE THREAD

**Issue by girija0707** [Ayush7614/Daily-Coding-DS-ALGO-Practice#453]
# Aim

To find largest and smallest element in an array

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by girija0707** [comment]
please assign this to me in c++

**Comment by TasnimAnas** [comment]
assign me to do this in C and Java

LGMSOC

**Comment by pokwer** [comment]
assign me to do this in python

**Comment by saurabh-191** [comment]
assign me pls i will do this in python and c.

**Comment by Jagannath8** [comment]
I can do it in Java
I'm LGM-SoC participant

**Comment by Amit366** [comment]
@TasnimAnas do in C

**Comment by girija0707** [comment]
will you please reopen this issue
