### ISSUE TITLE
Patterns

### ISSUE THREAD

**Issue by div0510** [Ayush7614/Daily-Coding-DS-ALGO-Practice#457]
I would like to add some patterns

I will add some using c++;

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by div0510** [comment]
I will do this using C++

**Comment by shrutigrover25** [comment]
I want to add contributor's to the patterns issue. Kindly assign me as a part of LGMSOC.

**Comment by nidhi3108** [comment]
I want to solve this issue in c.please assign me this issue

**Comment by Ayush7614** [comment]
We doesnt accept this question
