### ISSUE TITLE
Count Sort Algorithm

### ISSUE THREAD

**Issue by apran-vs** [Ayush7614/Daily-Coding-DS-ALGO-Practice#464]
# Aim

- Using the Counting, Sorting the Data.

# Details

- In this Algorithm, Using Consept of frequency, sorting Data

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by apran-vs** [comment]
As A participant of LGMSoC'21, I want to work on this Problem.

**Comment by agamgupta2015** [comment]
I want work on this issue in java Language

**Comment by Ayush7614** [comment]
Problem was already done in repo and issue was already opened
