### ISSUE TITLE
Huffman Coding

### ISSUE THREAD

**Issue by akash435** [Ayush7614/Daily-Coding-DS-ALGO-Practice#477]
The Algorithm of huffman coding is used for assigning the variable-length codes to input characters. It is also considered as a lossless data compression algorithm.
In this algo, we are given a character array and a frequency array, and we need to find the huffman code for each character

### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by akash435** [comment]
@Ayush7614 , please assign this issue to me under LGMSOC. I would like to add this algo in Greedy Algorithm part section of Algorithm folder.

**Comment by Kartikey0205** [comment]
Hey @Ayush7614 please assign me this in C++ language using STL

**Comment by Ayush7614** [comment]
Question was already exist in the repo
