### ISSUE TITLE
Wants to add a Hackerrank problem named Digit frequency

### ISSUE THREAD

**Issue by Kartikey0205** [Ayush7614/Daily-Coding-DS-ALGO-Practice#479]
**Is your feature request related to a problem? Please describe.**
Wants to add a Hackerrank problem named Digit frequency

**Describe the solution you'd like**
I want to write a program for that in C -language

### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

@Ayush7614 PLEASE ASSIGN ME THIS under Lgm-soc'21

**Comment by rakesh419s** [comment]
@Ayush7614 I can do this in python assign me

**Comment by TasnimAnas** [comment]
I can do this in C++, Assign me
LGM_SOC

**Comment by Kartikey0205** [comment]
@Amit366  please mark the level in it !

**Comment by mitali-1703** [comment]
Hey @Amit366 I can add a java solution to this.Please assign me this under LGM-SOC'21
