### ISSUE TITLE
Regular Expression Matching with '*' and '.'

### ISSUE THREAD

**Issue by rakesh419s** [Ayush7614/Daily-Coding-DS-ALGO-Practice#484]
# Aim

- standard problem statement, which also appeared in the coding interviews at FAANG

# Details

- matching algorithm

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- .Python

**Comment by rakesh419s** [comment]
**could you please assign this to me in python**

**Comment by anshyyy** [comment]
hi @rakesh419s  i would like to work on this issue in C++. Could you please assign it to me?
