### ISSUE TITLE
Adding these 5 problems in Leetcode Set

### ISSUE THREAD

**Issue by predator-24** [Ayush7614/Daily-Coding-DS-ALGO-Practice#485]
# Aim

- Adding these few Leetcode Questions Solutions to the set, All of the solutions are in cpp

# Details

- Question 1 ->  Search in 2D Matrix
   Link https://leetcode.com/problems/search-a-2d-matrix/
- Question 2 ->  Count and Say
   Link https://leetcode.com/problems/count-and-say/
- Question 3 ->  Longest Common Prefix
   Link https://leetcode.com/problems/longest-common-prefix/
- Question 4 ->  Number of rectangles that can form the largest square
   Link  https://leetcode.com/problems/number-of-rectangles-that-can-form-the-largest-square/
- Question 5 ->  Search in a Rotated Sorted Array
   Link  https://leetcode.com/problems/search-in-rotated-sorted-array/

**Comment by toth2000** [comment]
## LGM-SOC'21 Contribution

I would like to create a PR for the java part of the following questions:
- Question 1
- Question 3
- Question 5

(I have already created PR for the assigned issues but it is yet to be merged, so will those issues also count as assigned for me?)

**Comment by Amit366** [comment]
@predator-24 add separately
