### ISSUE TITLE
Added Questions in Python

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Daily-Coding-DS-ALGO-Practice#5]

**Comment by pranita736** [comment]
Assign me.

**Comment by Sakalya100** [comment]
I am an experienced coder in Python. I can work on it and provide easy to understand solutions.
I am a 3star at Codechef and 5 star in Hackerrank
So Please Assign me

**Comment by Ayush7614** [comment]
Go Ahead @pranita736 @Sakalya100
