### ISSUE TITLE
1 question added in leetcode section

### ISSUE THREAD

**Issue by harsh6768-svg** [Ayush7614/Daily-Coding-DS-ALGO-Practice#505]
# Aim

This is the most important question of stack in leetcode and was asked a lot of time in coding interviews.
Help in improving problem solving skills

# Details

leetcode problem link->
https://leetcode.com/problems/largest-rectangle-in-histogram/

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
You are participant of LGM soc or not

**Comment by harsh6768-svg** [comment]
yes @Ayush7614

**Comment by harsh6768-svg** [comment]
Can i work on this??
