### ISSUE TITLE
Hollow Butterfly Pattern

### ISSUE THREAD

**Issue by nidhi3108** [Ayush7614/Daily-Coding-DS-ALGO-Practice#513]
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by nidhi3108** [comment]
I will do this using c++.please assign this to me.

**Comment by suy1968** [comment]
I will do using python , please assign me

**Comment by suy1968** [comment]
Sir, please check I already send PR

**Comment by Ayan-thecodeking** [comment]
hey :)
I want to add this program in c and java language
please assign this to me
