### ISSUE TITLE
Bellman Ford Algorithm

### ISSUE THREAD

**Issue by radhikaaojha** [Ayush7614/Daily-Coding-DS-ALGO-Practice#522]
**Is your feature request related to a problem? Please describe.**
Bellman ford algorithm in C

**Describe the solution you'd like**
Implementation using Graph

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by radhikaaojha** [comment]
Please assign this to me (LGM-SOC) @Amit366

**Comment by Ayush7614** [comment]
Go Ahead @radhikaaojha

**Comment by Ayan-thecodeking** [comment]
hey :)
I want to add this program in c and java language
please assign this to me
