### ISSUE TITLE
improvement Bug/ proper formatting needed 

### ISSUE THREAD

**Issue by shantamsultania** [Ayush7614/Daily-Coding-DS-ALGO-Practice#524]
Hey,
I would like to request it as an improvement Bug the thing is that many people are contributing to the Repo and its getting confusing which program is under which category so for this I would like to suggest some proper formatting of the report example 

Algoritms ->
                     Java  -> Programs in Java  
                       TestCases - > If anyone wants to add TestClass of the Question and all                       
                     CPP  - > programs in CPP 
                     Python -> Programs in python 
                     
and so on if it's ok can I can take it?

**Comment by Pratik57** [comment]
**Hey,
I have solved this issue and rearrange all the files without deleting any of them**
@Ayush7614 please check the pull request. https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/pull/579#issue-668271197

![Screenshot from 2021-06-11 20-20-29](https://user-images.githubusercontent.com/39158589/121706533-582add80-caf3-11eb-834c-26c797c4886b.png)



![Screenshot from 2021-06-11 20-20-48](https://user-images.githubusercontent.com/39158589/121707097-dd15f700-caf3-11eb-92fe-aa99e027a60e.png)
.

**Comment by Amit366** [comment]
@shantamsultania if u want u can go ahead
