### ISSUE TITLE
 Find the K-th Largest Number

### ISSUE THREAD

**Issue by shantamsultania** [Ayush7614/Daily-Coding-DS-ALGO-Practice#530]
# Aim

Find the k-th largest number in a sequence of unsorted numbers.

Example:

Input : [8, 7, 2, 3, 4, 1, 5, 6, 9, 0], K = 3 

OutPut: 7

### Programming language

- [x] Java

**Comment by TasnimAnas** [comment]
I can do this in C and C++
assign me.

LGMSOC'21

**Comment by siddhi-244** [comment]
I can do this in python ! Please assign me this! I am an lgmsoc participant

**Comment by ambalika24** [comment]
I can solve this in c and c++. Please assign me this issue under LGMSOC 21

**Comment by Ayush7614** [comment]
Already Exist

**Comment by siddhi-244** [comment]
@Amit366 plz reopen this issue !

**Comment by Amit366** [comment]
@shantamsultania @siddhi-244 implement in java and python

**Comment by siddhi-244** [comment]
@Amit366  sure I am doing it in python !

**Comment by siddhi-244** [comment]
@Amit366 check pr #660
