### ISSUE TITLE
Update the wrong name of the repo.

### ISSUE THREAD

**Issue by hr1shu** [Ayush7614/Daily-Coding-DS-ALGO-Practice#531]
**Describe the bug**
The repo name is wrong.

**To Reproduce**
1. Go to 'Readme.md file'
3. Scroll down to '.Contributing section, Line 15'
4. See an error

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Expected behavior**
I'll change the wrong name to the present name of the repo.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ windows]
 - Browser [Microsoft edge]
 - Version [91]

**Smartphone (please complete the following information):**
 - Device: [POCO X3]
 - OS: [MIUI 12]
 - Browser [Microsoft edge] 
 - Version [46]

**Additional context**

**Comment by AnkitaKataria22** [comment]
@Amit366 @Ayush7614 assign me this issue
