### ISSUE TITLE
"Smart Phone" Problem of Codechef

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#532]
# Aim

I want to add the code for "Smart Phone" problem in codechef (DSA Learning Series)

# Details

Problem name : Smart Phone
Problem Code : ZCO14003
Problem link : https://www.codechef.com/LRNDSA01/problems/ZCO14003

Please assign me this issue
LGM-SOC Participant

Programming language
C++

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Sriram-bb63** [comment]
I would like to solve this in python

**Comment by suy1968** [comment]
Problem name : Smart Phone
Problem Code : ZCO14003
Problem link : https://www.codechef.com/LRNDSA01/problems/ZCO14003

Please assign me this issue
LGM-SOC Participant

Programming language
Python3

**Comment by Ayush7614** [comment]
@manuvarghese0603 @suy1968 go ahead

**Comment by suy1968** [comment]
> @manuvarghese0603 @suy1968 go ahead

Sir, already send PR

**Comment by manuvarghese0603** [comment]
> @manuvarghese0603 @suy1968 go ahead

Sir,  C++ code also added
