### ISSUE TITLE
The TwoSum Problem

### ISSUE THREAD

**Issue by sameer2403** [Ayush7614/Daily-Coding-DS-ALGO-Practice#546]
# Aim

- This is a classic algorithmic interview question. 

# Details

leetcode problem link->
https://leetcode.com/problems/two-sum/

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by sameer2403** [comment]
i would like to add this problem in leetcode section under  LGM SOC.Please assign me this task

**Comment by siddhi-244** [comment]
Can I do it in c++ ?

**Comment by Jagannath8** [comment]
Can I do it in Java?
I'm a LGM-SoC'21 participant.

**Comment by PurviGoyal7** [comment]
-**I can do it in C language**
-Can you please assign this to me.
-I am a LGM-SOC'21 participant.

**Comment by Ayan-thecodeking** [comment]
I want to add this solution in **python** language 
- please assign me this task
