### ISSUE TITLE
Implement Bucket sort in C++

### ISSUE THREAD

**Issue by muthuannamalai12** [Ayush7614/Daily-Coding-DS-ALGO-Practice#549]
I would love to implement Bucket sort in C++. Kindly assign me this issue as a part of LGMSOC

**Comment by ishitakapoor26** [comment]
@Ayush7614 Pls assign this issue to me. I would like to implement Bucket Sort in C.

**Comment by mitali-1703** [comment]
@Ayush7614 Pls assign this issue to me. I would like to implement Bucket Sort in java under lgm-soc'21.
