### ISSUE TITLE
Implement Bead sort in C++

### ISSUE THREAD

**Issue by muthuannamalai12** [Ayush7614/Daily-Coding-DS-ALGO-Practice#550]
I would love to implement Bead sort in C++. Kindly assign it to me as a part of LGMSOC.

**Comment by ishitakapoor26** [comment]
@Ayush7614 pls assign this issue to me. I would like to do it in C.

**Comment by mitali-1703** [comment]
@Ayush7614 pls assign this issue to me. I would like to do it in java.
