### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by RiyaGupta89** [Ayush7614/Daily-Coding-DS-ALGO-Practice#558]
**Is your feature request related to a problem? Please describe.**
Maximum sum of sub array is one of the interesting problem also it is being asked by the top MNCs, I would like to add it to the list. Please assign me this issue sir.

**Describe alternatives you've considered**
Maximum sum of sub array, the most optimised way with the help of Kadane's Algorithm.

### Programming language

- [ ] C
- [ ✓] C++
- [ ] Java
- [ ] Python

**Comment by Jagannath8** [comment]
I can implement in Java
I'm a LGM-SoC'21 participant

**Comment by siddhi-244** [comment]
Can I try in python ? I am lgmsoc participant

**Comment by Ayush7614** [comment]
Issue was already opened
