### ISSUE TITLE
Dijsktra Algorithm Implementation

### ISSUE THREAD

**Issue by radhikaaojha** [Ayush7614/Daily-Coding-DS-ALGO-Practice#559]
**Is your feature request related to a problem? Please describe.**
Dijkstra's Algorithm Implementation in C

**Describe the solution you'd like**
Implementation using array

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by radhikaaojha** [comment]
@Amit366 @Ayush7614 Kindly assign this to me.

**Comment by Kartikey0205** [comment]
@Amit366 @Ayush7614 please assign me this in C++ Language under Lgm-soc'21

**Comment by kumarshobhit** [comment]
I would like to contribute in java language

**Comment by Ayush7614** [comment]
We have Already in repo

**Comment by Amit366** [comment]
@Kartikey0205 we have Cpp code

**Comment by mitali-1703** [comment]
@Amit366 can I implement this in python under lgm-soc'21??
