### ISSUE TITLE
Occurrence of an integer in a Linked List

### ISSUE THREAD

**Issue by anubhav201241** [Ayush7614/Daily-Coding-DS-ALGO-Practice#564]
**Is your feature request related to a problem? Please describe.**
I want to add my code to your repository using CPP

**Describe the solution you'd like**
Want to add an answer to GFG's Linked List question

**Describe alternatives you've considered**
I can modify it and can add more code 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
Already in project
