### ISSUE TITLE
Sliding Window Technique

### ISSUE THREAD

**Issue by PurviGoyal7** [Ayush7614/Daily-Coding-DS-ALGO-Practice#575]
# Aim

- To calculate maximum sum of 'k' consecutive elements in an array of size 'n' in C++.

# Details

- Above problem will be solved using O(n) time complexity.
- I am a participant in LGM-SOC'21.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Jagannath8** [comment]
I can implement in Java
I'm a LGM-SoC'21 participant

**Comment by Amit366** [comment]
@PurviGoyal7 this already exists
