### ISSUE TITLE
Hamming Distance (Leet code)

### ISSUE THREAD

**Issue by arpitgoyal27** [Ayush7614/Daily-Coding-DS-ALGO-Practice#581]
The Hamming distance between two integers is the number of positions at which the corresponding bits are different.

Given two integers x and y, return the Hamming distance between them.

I will use c++ in this question.

**_Porblem Link_**: https://leetcode.com/problems/hamming-distance/

**Comment by arpitgoyal27** [comment]
@Amit-45  assign it to me.

**Comment by mdinesh124** [comment]
@Ayush7614 Please assign it to me under LGMSOC. I will solve it in java.
