### ISSUE TITLE
LCS for 3 strings

### ISSUE THREAD

**Issue by Shaishav0507** [Ayush7614/Daily-Coding-DS-ALGO-Practice#584]
# Aim

Hey @Ayush7614 
I would like to add LCS 3 strings code.
Please assign me.
Thanks

# Details

It a very important from competitive point of view.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
Mention your language

**Comment by Shaishav0507** [comment]
In c++

**Comment by Shaishav0507** [comment]
Can I go ahead ?

**Comment by siddhi-244** [comment]
Shall I try in python ? @Amit366
