### ISSUE TITLE
Number of Islands

### ISSUE THREAD

**Issue by jahnvisrivastava100** [Ayush7614/Daily-Coding-DS-ALGO-Practice#585]
**Aim**

An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.

**Details**

```
Input: grid = [
  ["1","1","1","1","0"],
  ["1","1","0","1","0"],
  ["1","1","0","0","0"],
  ["0","0","0","0","0"]
]
Output: 1
```

Problem Link :https://leetcode.com/problems/number-of-islands/
I will be using C++.
Please assign me the problem under LGM_SOC'21
### **Programming language**

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by jahnvisrivastava100** [comment]
@Amit-45  @Ayush7614 Kindly assign this to me.

**Comment by kumarshobhit** [comment]
I would like to contribute in java languageage
