### ISSUE TITLE
Added Questions in Tress Graphs

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Daily-Coding-DS-ALGO-Practice#6]

**Comment by coding-geek21** [comment]
Can you assign me this issue I want to work on this under LGM-SOC

**Comment by Jaincode123** [comment]
I want to upload Kahn's and Tarjan's algorithms under this topic. Can you assign this to me?

**Comment by Nikitajain2606** [comment]
please assign this to me, i want work on Kosaraju's algorithm and BFS on 2D grid under this topic.

**Comment by Ayush7614** [comment]
@Nikitajain2606 @coding-geek21 Go Ahead

**Comment by mitali-1703** [comment]
Hey @Ayush7614 can I add basic to intermediate level questions on Tee and Graph in C++ under LGM-SOC'21?
