### ISSUE TITLE
Birthday paradox 

### ISSUE THREAD

**Issue by Amit-45** [Ayush7614/Daily-Coding-DS-ALGO-Practice#602]
Problem:  program to approximate number of people for a given probability.

**Comment by Amit-45** [comment]
@Ayush7614 @Amit366 Please assign me this issue I would like to solve this question as a part of the LGM-SOC'21 contest.

Language : C++

**Comment by Amit366** [comment]
@Amit-45 since u have closed this issue ur PR will not be reviewed

**Comment by Amit-45** [comment]
@Amit366  Sir I had more than 2 issues open and I have seen in the Slack channel that not more than 2 issues need to be open .So I have closed the extra ones . Can I reopen it or I have to create a new issue again ?

**Comment by Amit366** [comment]
@Amit-45 but u have sent the PR then how can u close the issue

**Comment by Amit-45** [comment]
@Amit366 Sir actually I am a newbie in open source . So I didn't have the idea that - When the pull request is already sent , we should not close the issue .I apologize for my mistake and this will not be repeated again from my side .

**Comment by Amit366** [comment]
Then reopen it @Amit-45

**Comment by Amit-45** [comment]
@Amit366 Reopened issue
