### ISSUE TITLE
Friends Pairing Problem

### ISSUE THREAD

**Issue by rajat1701** [Ayush7614/Daily-Coding-DS-ALGO-Practice#604]
**Is your feature request related to a problem? Please describe.**
      Friends Pairing Problem (Using Dynamic Programming)
**Describe the solution you'd like**
      Implementation using array in language C++ 
      The problem is simplified version of how many ways we can divide n elements into multiple groups.

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by rajat1701** [comment]
@Amit366 @Ayush7614 
Kindly assign me this issue

**Comment by KishkinJ10** [comment]
Can i also work on this issue?

**Comment by KishkinJ10** [comment]
@Ayush7614 Sir i have made PR on this friend pairing problem using DP please merge this.
