### ISSUE TITLE
Basics Operations in a Binary Tree

### ISSUE THREAD

**Issue by kamleshjoshi8102** [Ayush7614/Daily-Coding-DS-ALGO-Practice#607]
# Aim

Basic Tree  Implementation 
-> Traversals (In-order , Post-order , pre-order , level-order )
-> height of a Tree
-> Count of Nodes in a Tree 
-> Count of leaf Nodes in a Tree
-> Count of Nodes of Two Degree
-> Count of Nodes of One Degree

# Details

I will be adding a beginner friendly code  C++ Under LGMSOC

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Amit366** [comment]
@kamleshjoshi8102 WE ALREADY have it
