### ISSUE TITLE
Implementation of Fenwick Tree using C

### ISSUE THREAD

**Issue by radhikaaojha** [Ayush7614/Daily-Coding-DS-ALGO-Practice#610]
**Is your feature request related to a problem? Please describe.**
Implementation of Fenwick Tree using C

**Describe the solution you'd like**
Using C language through array

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by radhikaaojha** [comment]
@Ayush7614 @Amit366 Kindly,Assign me this issue.

**Comment by AnkitaKataria22** [comment]
@Ayush7614 and @Amit366 assign me this issue

**Comment by Amit366** [comment]
@AnkitaKataria22 mention the language
