### ISSUE TITLE
Gold Mine

### ISSUE THREAD

**Issue by Priya23Singh** [Ayush7614/Daily-Coding-DS-ALGO-Practice#611]
**Is your feature request related to a problem? Please describe.**
Gold Mine Problem

**Describe the solution you'd like**
Implementation of gold mine problem and find out the maximum amount of gold that can be collected. 

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Priya23Singh** [comment]
@Ayush7614 @Amit366 Please assign me this problem.

**Comment by kamleshjoshi8102** [comment]
Please Assign me this Problem in C++ under LGMSOC

**Comment by Amit366** [comment]
@kamleshjoshi8102 first finish other issues

**Comment by akshita2903** [comment]
@Amit366  please assign me this problem.I will do this in Java.
