### ISSUE TITLE
Bubble sort in python

### ISSUE THREAD

**Issue by Komal-99** [Ayush7614/Daily-Coding-DS-ALGO-Practice#630]
# Aim

- Add bubble Sorting method using Python

# Details

- Sorting Algorithm

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by jahnvisrivastava100** [comment]
@Ayush7614  I would like to add this in C

**Comment by nidhi3108** [comment]
I would like to add this in c++.Please assign me .

**Comment by apran-vs** [comment]
I would like to solve this issue with python.Please assign me.

**Comment by Komal-99** [comment]
@apran-vs  i already made the issue for doing it in  python

**Comment by Amit366** [comment]
Other languages are already done. But java and python are left.

**Comment by Komal-99** [comment]
Can you please tell folder to add code

**Comment by Komal-99** [comment]
@Amit-45 Kindly check my PR #943  as i by mistake made it in master and i have to now proceed with issue Armstrong issue in new PR

**Comment by kamakshi829** [comment]
> Other languages are already done. But java and python are left.



@Amit-45 I can do it in python. Please assign it to me.

**Comment by Komal-99** [comment]
> > Other languages are already done. But java and python are left.
> 
> @Amit-45 I can do it in python. Please assign it to me.

@kamakshi829  PR has been made #943
