### ISSUE TITLE
Added Adjacency list Graph representation

### ISSUE THREAD

**Issue by Anupam-Panwar** [Ayush7614/Daily-Coding-DS-ALGO-Practice#634]
# Aim

- To demonstrate how Graph can be presented in Adjacency List form

# Details

- Program will take edges and vertices as an input from the user
- Output of the program will be Adjacency list representation

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Anupam-Panwar** [comment]
I would like to add this in C++ language

**Comment by Ayush7614** [comment]
first work on 2 issues then reopen again this issues
