### ISSUE TITLE
Implement two stacks in an array

### ISSUE THREAD

**Issue by Kashish05** [Ayush7614/Daily-Coding-DS-ALGO-Practice#638]
It is one of the important question of stack data structure and I want to add it to this repo.

I can provide its C++ solution. Pls assign it to me.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Ayan-thecodeking** [comment]
hey :)
I want to add this program in c and java language 
please assign this to me

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 @Kashish05 Please Assign me this Issue. I will solve this question in c++.

Thank You

**Comment by Kashish05** [comment]
Only admin can assign ig.

**Comment by Kashish05** [comment]
@Ayush7614 can u pls assign me this issue?

**Comment by Amit366** [comment]
This issue is already done.
