### ISSUE TITLE
swap numbers using bit manipulation

### ISSUE THREAD

**Issue by Amit-45** [Ayush7614/Daily-Coding-DS-ALGO-Practice#642]
If we use bit manipulation to swap the numbers the execution time will be much lower.

@Ayush7614 @Amit366 Please assign me this issue I would like to solve this question as a part of the LGM-SOC'21 contest.

Language : C++

**Comment by Ayan-thecodeking** [comment]
hey :)
I want to add this program in c and java language
please assign this to me

**Comment by Ayush7614** [comment]
> hey :)
> I want to add this program in c and java language
> please assign this to me

tell me only one language
