### ISSUE TITLE
Two Sum Leetcode

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [Ayush7614/Daily-Coding-DS-ALGO-Practice#650]
# Aim

To add the solution to beginner friendly Two Sum question under in Leetcode folder

# Details

I can provide solution in c++.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Sukhseerat-Kaur** [comment]
@Ayush7614 Please assign me this under LGMSOC'21

**Comment by siddhi-244** [comment]
Can I try this in python ?

**Comment by Jagannath8** [comment]
I can do this in Java. I'm LGM-SoC'21 participant.

**Comment by Ayush7614** [comment]
we have already this problem in repo
