### ISSUE TITLE
Bellman Ford Algorithm

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [Ayush7614/Daily-Coding-DS-ALGO-Practice#652]
# Aim

I would like to add Bellman Ford Algorithm under algorithms.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sukhseerat-Kaur** [comment]
@Ayush7614 Please assign me this under LGMSOC'21

**Comment by Jagannath8** [comment]
I can do this in Java. I'm a participant of LGM Soc21.

**Comment by Amit366** [comment]
@Sukhseerat-Kaur mention the language

**Comment by Sukhseerat-Kaur** [comment]
@Amit366 C++
