### ISSUE TITLE
Way Too Long Words

### ISSUE THREAD

**Issue by nisha331** [Ayush7614/Daily-Coding-DS-ALGO-Practice#653]
Sometimes some words like "localization" or "internationalization" are so long that writing them many times in one text is quite tiresome.

Let's consider a word too long, if its length is strictly more than 10 characters. All too long words should be replaced with a special abbreviation.

This abbreviation is made like this: we write down the first and the last letter of a word and between them we write the number of letters between the first and the last letters. That number is in decimal system and doesn't contain any leading zeroes.

Thus, "localization" will be spelt as "l10n", and "internationalization» will be spelt as "i18n".

You are suggested to automatize the process of changing the words with abbreviations. At that all too long words should be replaced by the abbreviation and the words that are not too long should not undergo any changes.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

I as a participant at LGMSOC'21 would like to work on this issue . Project admins and mentors kindly assign it to me

**Comment by TasnimAnas** [comment]
I can do this in C language.
Assign me.

LGM_SOC'21

**Comment by chandu6111** [comment]
@Ayush7614 could you please assign this issue to me, I would like to contribute to it in "Python 3"

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 Please assign me this issue. I will solve this question in c++.
LGM SOC'21
