### ISSUE TITLE
balanced-brackets

### ISSUE THREAD

**Issue by apran-vs** [Ayush7614/Daily-Coding-DS-ALGO-Practice#665]
# Problem

- https://www.hackerrank.com/challenges/balanced-brackets/problem

# Details

- Using Stack, we are going to check that brackets are balanced or not
- Ex.

1
Input :  {[()]}
Output : Balanced

2
Input : {[(])}
Output : Unbalanced

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by apran-vs** [comment]
Please this issue to me.

**Comment by siddhi-244** [comment]
Can I do it in python or c?

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 @apran-vs Please assign me this issue. I will solve this question in c++.
Thank You

**Comment by Jagannath8** [comment]
I can do this in Java. I'm a participant of LGM Soc21.

**Comment by Kashish05** [comment]
I want to try it in c++. Pls assign me.

**Comment by ShivanshuVishnoi** [comment]
@Amit-45 @Saurabh4626 @Ayush7614 @ravikr126 Please assign me. I will solve it in C++.
LGM-SOC'21

Thank You

**Comment by Amit366** [comment]
@ShivanshuVishnoi someone else is working on it

**Comment by apran-vs** [comment]
I will have to make new pull request or old pull request will be counted

**Comment by Amit366** [comment]
I didn't get u.

**Comment by apran-vs** [comment]
I already made pull request for issue.

**Comment by Amit366** [comment]
Yeah so it will be counted if it is in correct format
