### ISSUE TITLE
Minimum Window Substring (Leetcode Hard) Question

### ISSUE THREAD

**Issue by Aiswarika** [Ayush7614/Daily-Coding-DS-ALGO-Practice#669]
@Amit366 @Ayush7614 I would like to work on this issue as a part of the LGM SOC contest. Kindly assign me this issue.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by PriyankaHotchandani** [comment]
I would like to work on this issue as a participant of LGM-SOC'21, and implement this in Python programming language.

**Comment by Pratik57** [comment]
Assign me in c under LGMSOC21 @Ayush7614 @Amit366

**Comment by siddhi-244** [comment]
Can I try in python ?

**Comment by rakesh419s** [comment]
Assign me in Java LGMSOC21

**Comment by siddhi-244** [comment]
Plzz assign me in python

**Comment by Amit366** [comment]
@siddhi-244 its done in python

**Comment by siddhi-244** [comment]
C ?
