### ISSUE TITLE
Josephus Problem 

### ISSUE THREAD

**Issue by ArshWalker** [Ayush7614/Daily-Coding-DS-ALGO-Practice#674]
@Ayush7614 

AIM :

Josephus Problem using recursion in c++.

please assign me this...

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ArshWalker** [comment]
@Ayush7614 please assign me this!

**Comment by Ayan-thecodeking** [comment]
hey @Ayush12062000 please assign me for this issue
I'll do it using java language
thanks :)

**Comment by ravikr126** [comment]
Sure @Ayan-thecodeking you can create a new issue I will assign you .And add questions and test cases also in pr

**Comment by Ayan-thecodeking** [comment]
> Sure @Ayan-thecodeking you can create a new issue I will assign you .And add questions and test cases also in pr

@ravikr126 questions for Josephus ??

**Comment by ravikr126** [comment]
Yes @Ayan-thecodeking
