### ISSUE TITLE
Kruskal's Algorithm

### ISSUE THREAD

**Issue by agamgupta2015** [Ayush7614/Daily-Coding-DS-ALGO-Practice#681]
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Atif0604** [comment]
i want to do this in C @Ayush7614

**Comment by Ayan-thecodeking** [comment]
hey @Ayush12062000 please assign me for this issue
I'll do it using java language
thanks :)
