### ISSUE TITLE
Kahn's Algorithm

### ISSUE THREAD

**Issue by agamgupta2015** [Ayush7614/Daily-Coding-DS-ALGO-Practice#682]
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by mitali-1703** [comment]
@Ayush7614 I want to add a C solution to this under lgm-soc'21...please assign me

**Comment by agamgupta2015** [comment]
@Amit366 i have open this pr and I want to work on it

**Comment by agamgupta2015** [comment]
in c++

**Comment by Ayan-thecodeking** [comment]
hey @Ayush12062000 please assign me for this issue
I'll do it using java language
thanks :)
