### ISSUE TITLE
Reorder List in cpp 

### ISSUE THREAD

**Issue by UG-SEP** [Ayush7614/Daily-Coding-DS-ALGO-Practice#685]
# Aim

Add a program that reorders the LinkedList as the order given below
For example: Given 1->2->3->4->5 its reorder is 1->5->2->4->3.
It is the GFG problem
[Problem link](https://practice.geeksforgeeks.org/problems/reorder-list/1/?category[]=Linked%20List&category[]=Linked%20List&problemStatus=solved&difficulty[]=2&page=1&query=category[]Linked%20ListproblemStatussolveddifficulty[]2page1category[]Linked%20List)

- What features will your script have
It has the basic LinkedList template and reorders function which returns the head of the new LinkedList.
Time complexity: O(N)& Space complexity O(1)
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Atif0604** [comment]
I want to do this in java
