### ISSUE TITLE
Left Rotation of Array

### ISSUE THREAD

**Issue by Suryadipsinh** [Ayush7614/Daily-Coding-DS-ALGO-Practice#688]
Problem Statement: A left rotation operation on an array of size n shifts each of the array's elements 1 unit to the left. Given an integer, d, rotate the array that many steps left and return the result.

Language:- C/C++

I want to add solution for this problem.

**Comment by TasnimAnas** [comment]
I want to solve this in Java
LGM_SOC'21

**Comment by siddhi-244** [comment]
Can I try in python ?
