### ISSUE TITLE
add Sieve of Eratosthenes algorithm

### ISSUE THREAD

**Issue by sambit221** [Ayush7614/Daily-Coding-DS-ALGO-Practice#694]
# Aim

- Want to add Sieve of Eratosthenes algorithm

# Details

- The sieve of Eratosthenes is one of the most efficient ways to find all primes smaller than n when n is smaller than 10 million

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by mitali-1703** [comment]
@Ayush7614 @Amit366 I want to add a C solution to this please assign me this under LGM-SOC'21

**Comment by Amit366** [comment]
this is already done
