### ISSUE TITLE
Balanced Array of Codeforces

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#706]
# Aim

- I want to add a question in Codeforces Folder

# Details

- Balanced Array Question of Codeforces 
- Problem 1343B
- https://codeforces.com/problemset/problem/1343/B

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 Please Assign me to solve this question in c++.
LGM-SOC'21
Thank You

**Comment by kamleshjoshi8102** [comment]
Can I implement it's Solution under LGM'SOC'21 in python
@Amit366 @Ayush7614
