### ISSUE TITLE
"Lapindromes" Problem of Codechef

### ISSUE THREAD

**Issue by manuvarghese0603** [Ayush7614/Daily-Coding-DS-ALGO-Practice#707]
# Aim

I want to add the code for "Lapindromes" problem in codechef (DSA Learning Series)

# Details

Problem name : Lapindromes
Problem Code : LAPIN
Problem link : https://www.codechef.com/LRNDSA01/problems/LAPIN

Please assign me this issue
LGM-SOC Participant

### Programming language

C++

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by suy1968** [comment]
Please assign me as I am part of LGM-SOC_21

I am using python3

**Comment by manuvarghese0603** [comment]
> Please assign me as I am part of LGM-SOC_21
> 
> I am using python3

You were supposed to add python file
I asked for the c++ version
The file which you added above is a cpp file

**Comment by Yakshit310** [comment]
Hi, I'm an LGM SOC participant and would like to work on this in C language. It would be great if this could be assigned to me.

**Comment by manuvarghese0603** [comment]
@arnab8335 
This issue was created by me and I asked for the cpp version of this question, kindly close the PR which you created using this issue as reference.

**Comment by viki4545** [comment]
Hey @Amit366 can i work on this using java

**Comment by viki4545** [comment]
Lapindromes problems of codechef in java added #1446
