### ISSUE TITLE
Prime Dates Of Hackerrank

### ISSUE THREAD

**Issue by rajeshkumar2024** [Ayush7614/Daily-Coding-DS-ALGO-Practice#715]
# Aim

- Want to add solution of Prime Dates in Java.

# Details

- Problem Link - https://www.hackerrank.com/challenges/prime-date/problem
- Want to solve under LGMSOC'21
- @Ayush7614 @Amit366 please assign me this.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by TasnimAnas** [comment]
I want to solve this in C++.
Plz assign me

**Comment by Amit366** [comment]
@rajeshkumar2024 mention the language

**Comment by rajeshkumar2024** [comment]
@Amit366 sir i will solve this in Java.

**Comment by Amit366** [comment]
@TasnimAnas and @rajeshkumar2024 I am closing this issue as almost everyone's code will be almost same as there is nothing much to add. So due to plagiarism I am closing this issue.
