### ISSUE TITLE
The Time in Words in Hackerrank

### ISSUE THREAD

**Issue by rajeshkumar2024** [Ayush7614/Daily-Coding-DS-ALGO-Practice#716]
# Aim

- Want to add solution of The Time in Words of Hackerrank under LGMSOC'21

# Details

- Problem link - https://www.hackerrank.com/challenges/the-time-in-words/problem
- Language used - Java
- @Ayush7614 @Amit366 please assign me this.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by TasnimAnas** [comment]
I want to solve this in C++

LGM_SOC'21
