### ISSUE TITLE
Indian Coin Change Problem

### ISSUE THREAD

**Issue by Shaishav0507** [Ayush7614/Daily-Coding-DS-ALGO-Practice#730]
Hey @Ayush7614 
I would like to add Indian Coin Change Problem in C++.
Please assign me.

# Details
It is based on Greedy Approach, where user enter certain numbers and the limit and gets the output of the coins.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in C language as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by Shaishav0507** [comment]
@Ayush7614 Can I go ahead ?

**Comment by 1218muskan** [comment]
Kindly assign me this issue under LGM SOC'21. I want to implement it in python.
