### ISSUE TITLE
Summer Heat-JUNE LONG CHALLENGE-DIV 3-CODECHEF

### ISSUE THREAD

**Issue by codeaholic-shub** [Ayush7614/Daily-Coding-DS-ALGO-Practice#734]
# Aim

Hey @Ayush7614 ,
I want to add Summer Heat Problem Solution in CPP,
Kindly assign this issue to me !

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

![Summer Heat _ CodeChef - Google Chrome 13-06-2021 10_11_58 (2)](https://user-images.githubusercontent.com/65807708/121795639-3edb7b80-cc30-11eb-8668-2c3c9cd515f0.png)

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in C language  as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by Anuradha0501** [comment]
I would like to add java solution for this problem @Ayush7614 please assign me this issue under LGMSOC 21 .
