### ISSUE TITLE
KMP Algorithm for Pattern Searching

### ISSUE THREAD

**Issue by Palak2801** [Ayush7614/Daily-Coding-DS-ALGO-Practice#740]
**Is your feature request related to a problem? Please describe.**
KMP Algorithm 

**Describe the solution you'd like**
Implementation using C++

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Palak2801** [comment]
@Amit366 @Ayush7614, Kindly assign me this issue under LGMSOC

**Comment by Jagannath8** [comment]
Can I implement in Java? I'm a participant of LGM Soc21.

**Comment by kamleshjoshi8102** [comment]
Can I Implement this Algorithm in python Under LGM"SOC"21
