### ISSUE TITLE
Power of 2

### ISSUE THREAD

**Issue by Amit-45** [Ayush7614/Daily-Coding-DS-ALGO-Practice#743]
Link for the question [here](https://practice.geeksforgeeks.org/problems/power-of-2-1587115620/1)

Problem statement : Given a non-negative integer N. The task is to check if N is a power of 2. More formally, check if N can be expressed as 2x for some x.

Please assign this task under the LGMSOC'21 .

Language : C++

**Comment by Aj7t** [comment]
hello, I am ajit part of  LetsGrowMore's Summer Of Code, plz assign me this issue !!!

**Comment by Atif0604** [comment]
i want to do this in java @Amit366
