### ISSUE TITLE
Twins question on Codeforces

### ISSUE THREAD

**Issue by Khushi-agarwal** [Ayush7614/Daily-Coding-DS-ALGO-Practice#747]
**Is your feature request related to a problem? Please describe.**
I want to implement the twins question which is given on codeforces which is 160A question number.

**Describe the solution you'd like**
I want to implement it in C++ language.
Problem link- https://codeforces.com/problemset/problem/160/A

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Khushi-agarwal** [comment]
@Amit366 Kindly assign me this issue under lgm-soc.

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by kamleshjoshi8102** [comment]
Can I implement  this Problem in Python under LGM'SOC'21
@Amit366 @Ayush7614
