### ISSUE TITLE
Taxi program from code forces

### ISSUE THREAD

**Issue by Khushi-agarwal** [Ayush7614/Daily-Coding-DS-ALGO-Practice#751]
# Aim

I want to add the solution of taxi problem from code forces.
Problem link-https://codeforces.com/problemset/problem/158/B

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 Please Assign me this issue. I will Solve this problem in C++.
LGM-SOC'21

Thank You
