### ISSUE TITLE
Leetcode: 871. Minimum No. of Refueling Stops (Hard-DP)

### ISSUE THREAD

**Issue by sejal1430** [Ayush7614/Daily-Coding-DS-ALGO-Practice#757]
A car travels from a starting position to a destination which is target miles east of the starting position.
Along the way, there are gas stations.  Each station[i] represents a gas station that is station[i][0] miles east of the starting position, and has station[i][1] liters of gas.
The car starts with an infinite tank of gas, which initially has startFuel liters of fuel in it.  It uses 1 liter of gas per 1 mile that it drives.
When the car reaches a gas station, it may stop and refuel, transferring all the gas from the station into the car.
What is the least number of refueling stops the car must make in order to reach its destination?  If it cannot reach the destination, return -1.
Note that if the car reaches a gas station with 0 fuel left, the car can still refuel there.  If the car reaches the destination with 0 fuel left, it is still considered to have arrived.

Input: target = 1, startFuel = 1, stations = []
Output: 0

Problem link: https://leetcode.com/problems/minimum-number-of-refueling-stops/

### Programming language
Java

As a participant of LGMSOC I have created this issue and would like to work on it.
@Ayush7614 Kindly assign me this issue.

**Comment by Anuradha0501** [comment]
I would like to add  C++ solution to this problem as a participant of LGM SOC 21. @Ayush7614  please assign me this issue.

**Comment by Amit366** [comment]
@Anuradha0501 please complete ur assigned issues

**Comment by Pratik57** [comment]
@Amit366  @Ayush7614 Atleast assign me in any one issue under LGMSOC21
I want to do this in c or cpp

**Comment by rakesh419s** [comment]
please assign me the above problem statement in Python
