### ISSUE TITLE
Convert the prefix expression to infix expression

### ISSUE THREAD

**Issue by Palak2801** [Ayush7614/Daily-Coding-DS-ALGO-Practice#758]
**Is your feature request related to a problem? Please describe.**
Convert the prefix expression to infix expression using stack data structure

**Describe the solution you'd like**
Implementation using c++

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Palak2801** [comment]
@Amit366 @Ayush7614, Kindly assign me this issue under LGMSOC

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in python as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by ShivanshuVishnoi** [comment]
@Amit366 @Ayush7614 Please Assign me this Issue. I will Solve this Problem in C++.
LGM-SOC'21

Thank You

**Comment by mitali-1703** [comment]
@Amit366 @Ayush7614 I want to do this in C under lgm-soc'21

**Comment by mitali-1703** [comment]
@ravikr126 sorry to say but i was assigned this issue in C then why did you close this PR??
