### ISSUE TITLE
GFG-Find the Kth maximum and minimum element of an array.

### ISSUE THREAD

**Issue by anishsingh42** [Ayush7614/Daily-Coding-DS-ALGO-Practice#765]
**Is your feature request related to a problem? Please describe.**
Given an array arr[] and a number K where K is smaller than size of array, the task is to find the Kth smallest element in the given array. It is given that all array elements are distinct.
Problem level : Medium (as per GFG)

**Describe the solution you'd like**
I am going to add this problem under GFG folder.
Algorithm:-
1) Initializing an array,
2) taking input from the user regarding the kth maximum or minimum element,
3) Sorting the array (given that all the elements are distinct.),
4) Finding the kth element in the sorted array.

**Additional context**
Problem link for reference: https://practice.geeksforgeeks.org/problems/kth-smallest-element5635/1

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by siddhi-244** [comment]
Can I try in python ?

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by 19bce502** [comment]
Hi,
I want to implement this in c++ as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!
