### ISSUE TITLE
Codechef  Bitwise tuples(BITTUP).cpp solution

### ISSUE THREAD

**Issue by vanishasamriddhi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#768]
I want to add the solution of a great question on CODECHEF i.e. Bitwise Tuples.
https://www.codechef.com/JUNE21C/problems/BITTUP
I want to work on this issue.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Shreya-Sharma8** [comment]
I want to work on this issue using C++, Kindly assign this issue to me.
