### ISSUE TITLE
Codechef LKDNGOLF

### ISSUE THREAD

**Issue by vanishasamriddhi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#769]
A great Question from Codechef May long Challenge, 2021.
I'm also from LGM-Soc
I would like to work on this Question with C++:
https://www.codechef.com/MAY21C/problems/LKDNGOLF/

**Comment by puneetkaur2929** [comment]
hey @Ayush7614 @Amit366 
I wish to work on this issue.
**language**: I am interested to use C++ .

Kindly assign this issue to me under LGM SOC'21.
