### ISSUE TITLE
Third Largest Element in C++

### ISSUE THREAD

**Issue by RoliGautam** [Ayush7614/Daily-Coding-DS-ALGO-Practice#779]
**Is your feature request related to a problem? Please describe.**
I want to add this question in GFG section. This question is about to finding third largest element in the given array. Please assign me . 
Thank you :)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by TasnimAnas** [comment]
I want to solve this in C

LGM_SOC'21

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by Jagannath8** [comment]
Can I implement in Java? I'm a participant of LGM Soc21.

**Comment by RoliGautam** [comment]
Thanks for assigning . I will make a PR soon!
