### ISSUE TITLE
Code for Equal Sum Partition using Dynamic Programming in C++. 

### ISSUE THREAD

**Issue by nandinit02** [Ayush7614/Daily-Coding-DS-ALGO-Practice#782]
**Is your feature request related to a problem? Please describe.**
Equal Sum Partition using Dynamic Programming.

**Describe the solution you'd like**
I want to add code for Equal Sum partition problem in which we have been given a set of positive numbers,  and we have to find if we can equally divide the set into two subsets such that the sum of elements in both the  subsets is equal.

**Describe alternatives you've considered**
I will implement this using Dynamic Programming.

**Additional context**
I request the project admin to assign me this issue under LGMSOC21.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by kumarshobhit** [comment]
I would like to contribute in java
