### ISSUE TITLE
find Largest sum contiguous Subarray

### ISSUE THREAD

**Issue by Surajvatsya** [Ayush7614/Daily-Coding-DS-ALGO-Practice#783]
# Aim

-find Largest sum contiguous Subarray 

# Details

- Given an array arr of N integers. Find the contiguous sub-array with maximum sum.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

@Ayush7614 I would like to work on this issue in C++. Kindly assign it to me

**Comment by siddhi-244** [comment]
Can I try in python ?

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in java as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by Muskanagrawa** [comment]
I want to implement it in c++ as a part of LGM- SOC . 

@Amit366 @ Ayush7614. Please assign it to me .

Thank you!

**Comment by Kashish05** [comment]
@Amit366 I can provide soln in c++. Kindly assign me this question.
