### ISSUE TITLE
Coins And Triangle | Codechef

### ISSUE THREAD

**Issue by drishika2002** [Ayush7614/Daily-Coding-DS-ALGO-Practice#792]
**Describe the solution you'd like**
Problem Code: TRICOIN
Problem Link: https://www.codechef.com/problems/TRICOIN

### Programming language: C++

Please assign this issue to me under LGM SOC'21.

**Comment by manuvarghese0603** [comment]
I would like to add python3 code for this problem.

Problem name : Coins And Triangle
Problem Code : TRICOIN
Problem link :  https://www.codechef.com/problems/TRICOIN

Please assign me this issue
LGM-SOC Participant

Programming language
Python

**Comment by TasnimAnas** [comment]
I want to solve this in Java. Assign me plz

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in C++ as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by manuvarghese0603** [comment]
Hey @Sathwika-02,
@drishika2002 has asked to solve it in c++ and it has been assigned to her by mentors.

**Comment by Sathwika-02** [comment]
I want to implement this in C language  as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in C language  as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by TasnimAnas** [comment]
@Amit366 assign me plz. for Java

**Comment by Amit366** [comment]
@Sathwika-02 first finish the assigned issues
