### ISSUE TITLE
String to Integer (atoi) - Leetcode(Medium)

### ISSUE THREAD

**Issue by Anshika-Srivastava** [Ayush7614/Daily-Coding-DS-ALGO-Practice#798]
Question:
Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer (similar to C/C++'s atoi function).
**I would like to provide my C++ code for this.
Thank You!**

**Comment by agamgupta2015** [comment]
@Ayush7614 may I doit in Java

**Comment by Sathwika-02** [comment]
Hi,
I want to implement this in python  as apart of LGM-SOC'21.
@Amit366 @Ayush7614 Please assign it to me. Thankyou!!

**Comment by kamleshjoshi8102** [comment]
I Would like to provide my code For this problem in C language under LGMSOC
