### ISSUE TITLE
TSORT problem of Codechef

### ISSUE THREAD

**Issue by Obito2002** [Ayush7614/Daily-Coding-DS-ALGO-Practice#821]
Question:
t – the number of numbers in list, then t lines follow [t <= 10^6].
Each line contains one integer: N [0 <= N <= 10^6]

I  would like to provide the solution in C++.

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Obito2002** [comment]
This is my first issue. Please tell me if its correct and if its correct please assign it to me.

**Comment by TasnimAnas** [comment]
I can do this in C language. Assign me.

LGM_SOC

**Comment by suy1968** [comment]
Problem statement :- 
Given the list of numbers, you are to sort them in non decreasing order.

Input

t – the number of numbers in list, then t lines follow [t <= 10^6]. Each line contains one integer: N [0 <= N <= 10^6] Output

Output given numbers in non decreasing order.
Example

Input:
5
5
3
6
7
1
Output:
1
3
5
6
7

Please assign me 
I amusing python3

**Comment by viki4545** [comment]
Hey @Amit366 i m a LGM-Soc Participant, i would like to work on this issue using java, would you like to assign me

**Comment by Amit366** [comment]
@viki4545 add test case
