### ISSUE TITLE
Add Adjacency list Graph representation

### ISSUE THREAD

**Issue by Anupam-Panwar** [Ayush7614/Daily-Coding-DS-ALGO-Practice#835]
# Aim

- To demonstrate how Graph can be presented in Adjacency List form

# Details

- Program will take edges and vertices as an input from the user
- Output of the program will be Adjacency list representation

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Anupam-Panwar** [comment]
I would like to add this in C++ language

**Comment by 19bce502** [comment]
Hi,
I want to implement this in c++ as apart of LGM-SOC'21.
Please assign it to me. Thankyou!!

**Comment by SrihariTadala** [comment]
Im preparing for my  coding interviews and it would really help me if you assign this question to me 
Kindly assign me this issue under LGMSOC using pyhton or C++
