### ISSUE TITLE
Check whether BST contains Dead End or not

### ISSUE THREAD

**Issue by SNEHAL311998** [Ayush7614/Daily-Coding-DS-ALGO-Practice#873]
# Aim

- To Check whether BST contains Dead End or not. 
- Given a Binary Search Tree that contains positive integer values greater than 0. The task is to check whether the BST contains a dead end or not.

# Details

- This code checks whether a given BST has a dead-end or not. Here Dead End means, we are not able to insert any element after that node.
![check_dead](https://user-images.githubusercontent.com/61999845/121894091-59028000-cd3c-11eb-9295-74e360a5e118.JPG)

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python
 
Link for the problem statement - https://practice.geeksforgeeks.org/problems/check-whether-bst-contains-deadend/1]

**Comment by SNEHAL311998** [comment]
Please assign me for this problem I would like to solve it

**Comment by Ayush7614** [comment]
Already we have
