### ISSUE TITLE
Remove duplicates from an unsorted linked list

### ISSUE THREAD

**Issue by Palak2801** [Ayush7614/Daily-Coding-DS-ALGO-Practice#892]
**Is your feature request related to a problem? Please describe.**
Remove duplicates from an unsorted linked list

**Describe the solution you'd like**
Implementation of program using C

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Palak2801** [comment]
@Amit366 @Ayush7614 Kindly assign me this issue using C under LGMSOC.

**Comment by Jagannath8** [comment]
Can I implement in Java? I'm a participant of LGM Soc21.

**Comment by mitali-1703** [comment]
@Ayush7614 @Amit366 Kindly assign me this issue using C under LGMSOC.
