### ISSUE TITLE
Transitive closure of a graph

### ISSUE THREAD

**Issue by ayshi028** [Ayush7614/Daily-Coding-DS-ALGO-Practice#918]
Given a directed graph, find out if a vertex j is reachable from another vertex i for all vertex pairs (i, j) in the given graph. Here reachable mean that there is a path from vertex i to j. The reach-ability matrix is called the transitive closure of a graph.

Graph is given in the form of adjacency matrix say ‘graph[V][V]’ where graph[i][j] is 1 if there is an edge from vertex i to vertex j or i is equal to j, otherwise graph[i][j] is 0

Please assign me this question as a part of LGMSOC 21.
Question Link : https://www.geeksforgeeks.org/transitive-closure-of-a-graph/

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Pratik57** [comment]
@Saurabh4626  Assign me in cpp OR python under LGMSOC21

**Comment by kamleshjoshi8102** [comment]
@Saurabh4626 @ravikr126 @Ayush7614 Please Assign me this issue. I will solve it in java Or C++ or C
LGM-SOC'21
