### ISSUE TITLE
Remove Duplicates from sorted array

### ISSUE THREAD

**Issue by rajat1701** [Ayush7614/Daily-Coding-DS-ALGO-Practice#923]
**Is your feature request related to a problem? Please describe.**
Given a sorted array, the task is to remove the duplicate elements from the array

**Describe the solution you'd like**
Removing duplicates from an array using an auxillary array in C++

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by rajat1701** [comment]
@Ayush7614 @Amit366 Kindly assign me this issue.

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 @Amit366  Please Assign me this Question. I will Solve it in C++.
LGM-SOC'21

Thank You

**Comment by mitali-1703** [comment]
Please Assign me this issue. I will solve this problem in java
LGM-SOC'21

**Comment by anshyyy** [comment]
hi @Ayush7614 @Amit366 i would like to work on this issue in C++.

**Comment by 19bce502** [comment]
Hi please assign me this issue .I will do in c++ with many methods.
