### ISSUE TITLE
Minimum No Of Jump Needed To Reach End Of Array

### ISSUE THREAD

**Issue by harsh6768-svg** [Ayush7614/Daily-Coding-DS-ALGO-Practice#924]
# Aim

-This is the program which will calculate the minimum no jumps to need the end of array  very famous question both for Leetcode and also GFG  

# Details

Help to find the minimum no of jumps to reach the end of array .

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Jagannath8** [comment]
Can I implement in Java? I'm a participant of LGM Soc21.

**Comment by Saurabh4626** [comment]
@harsh6768-svg  try for iterative solution

**Comment by harsh6768-svg** [comment]
@Saurabh4626 yaaa sure

**Comment by TasnimAnas** [comment]
I want to solve this in C language. Assign me plz.

@Saurabh4626 
Lgmsoc'21
