### ISSUE TITLE
Sorting singly Linked List using Insertion sort

### ISSUE THREAD

**Issue by rajat1701** [Ayush7614/Daily-Coding-DS-ALGO-Practice#928]
**Is your feature request related to a problem? Please describe.**
Sorting singly Linked List using Insertion sort

**Describe the solution you'd like**
Using Insertion Sort Algorithm ,we sort a singly Linked List in C++

**Describe alternatives you've considered**

**Additional context**

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by rajat1701** [comment]
@Ayush7614 @Amit366 Kindly assign me this issue

**Comment by 19bce502** [comment]
@Ayush7614 @Amit366 Kindly assign me this issue I will do in C++ language
