### ISSUE TITLE
Aggressive cows Problem

### ISSUE THREAD

**Issue by Rutikab12** [Ayush7614/Daily-Coding-DS-ALGO-Practice#930]
**Aggressive Cows Problem**
This will gives the largest minimum distance between two barn layouts for the cows using binary search.

Please Assign me if possible. @ayush7614

**Comment by suy1968** [comment]
Problem statement :- 

Farmer John has built a new long barn, with N (2 <= N <= 100,000) stalls. The stalls are located along a straight line at positions x1,...,xN (0 <= xi <= 1,000,000,000).

His C (2 <= C <= N) cows don't like this barn layout and become aggressive towards each other once put into a stall. To prevent the cows from hurting each other, FJ wants to assign the cows to the stalls, such that the minimum distance between any two of them is as large as possible. What is the largest minimum distance?
Input
t – the number of test cases, then t test cases follows.
* Line 1: Two space-separated integers: N and C
* Lines 2..N+1: Line i+1 contains an integer stall location, xi
Output
For each test case output one integer: the largest minimum distance.
Example
Input:

1
5 3
1
2
8
4
9
Output:

3
please assign me

**Comment by Rutikab12** [comment]
Hey @Ayush7614  , I Haven't got any reply since 18 days. Can I work on this issue ?
