### ISSUE TITLE
Graph Coloring Problem

### ISSUE THREAD

**Issue by Karnika06** [Ayush7614/Daily-Coding-DS-ALGO-Practice#932]
# Aim

- To determine all the different ways in which graph can be colored using at most _m_ colors.

# Details

- Graph represented by its adjacency matrix.
- Colors are represented by the integers 1,2,...,m.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Karnika06** [comment]
I wish to work on this issue please assign this to me under LGM-SoC'21.

**Comment by 19bce502** [comment]
I want to work in this problem in c++ please assign me under LGM-SoC'21

**Comment by Pratik57** [comment]
@Saurabh4626  @Amit366 @Ayush7614  Assign me in c under LGMSOC21

**Comment by rakesh419s** [comment]
Assign me in Python under LGMSOC'21
