### ISSUE TITLE
Prefix Evaluation using Stack Data Structure

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#939]
# Aim

- I would like to add a code in Data Structure Folder.

# Details

- Prefix Evaluation Calculator Code using C++.
- LGM-SOC'21.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Ayush7614 @Amit366  Please Assign me this issue. I will solve this problem in C++.
LGM-SOC'21

Thank You

**Comment by mitali-1703** [comment]
@Ayush7614 @Amit366 Please Assign me this issue. I will solve this problem in C.
LGM-SOC'21

**Comment by 19bce502** [comment]
@Ayush7614 @Amit366 Please Assign me this issue. I will solve this problem in C++.
LGM-SOC'21
