### ISSUE TITLE
Codechef May Lunchtime 2021 Division 3 : Birthday Gifts (Problem Code: TWINGFT)

### ISSUE THREAD

**Issue by its-me-debk007** [Ayush7614/Daily-Coding-DS-ALGO-Practice#941]
**A question in which, basically two persons take K turns alternately to choose gifts. In a turn, a person may choose one gift. The only exception is the last turn, in which whoever moves second, he gets to choose two gifts instead of one.  We need to find the maximum total cost of the gifts that a person can keep.**

For more info, here is the link to the question: https://www.codechef.com/LTIME96C/problems/TWINGFT

Can you please assign me this task, as it is a good level problem from the perspective of a newbie to CP, and will help him/her to approach to this type of questions. Please assign me this under LGMSOC'21. I would like to share my C++ code.
THANK YOU

**Comment by Ayush7614** [comment]
Already we have
