### ISSUE TITLE
Valid Pair of Socks In Python

### ISSUE THREAD

**Issue by Kritika-2000** [Ayush7614/Daily-Coding-DS-ALGO-Practice#964]
# Aim

- This is Codeshef Contest Question named Valid Pair (Problem Code: SOCKS1)

# Problem Statement
Chef has three socks in his drawer. Each sock has one of 10 possible colours, which are represented by integers between 1 and 10. Specifically, the colours of the socks are A, B, and C.

Chef has to wear two socks which have the same colour. Help Chef find out if that is possible or not.

Example Input - 5 5 5
Output - yes

### Additional Context
Please assign this issue to me . I want to contribute in this project under LGMSOC21.

### Programming language
- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

**Comment by manuvarghese0603** [comment]
@Ayush7614 @Amit366 @ravikr126  @Saurabh4626 I would like to solve this problem in C++, please assign it to me under LGM-SOC'21

**Comment by ravikr126** [comment]
only ds algo question will prefer for pr @Kritika-2000 , not competitive coding problems
