### ISSUE TITLE
Honest Coach Problem of Codeforces

### ISSUE THREAD

**Issue by ShivanshuVishnoi** [Ayush7614/Daily-Coding-DS-ALGO-Practice#989]
# Aim
I want to add a question in Codeforces Folder.

# Details

- Honest Coach Problem.
- Problem 1360B
- https://codeforces.com/problemset/problem/1360/B
- LGM-SOC'21

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by ShivanshuVishnoi** [comment]
@Amit366 @Ayush7614 @Saurabh4626 @ravikr126 Please Assign me this issue. I will Solve it in C++.
LGM-SOC'21

Thank You

**Comment by ravikr126** [comment]
no competitive programming questions @ShivanshuVishnoi .Only ds Algo questions will prefer @ShivanshuVishnoi
