### ISSUE TITLE
Leetcode locked problems

### ISSUE THREAD

**Issue by richadubey338** [Ayush7614/Daily-Coding-DS-ALGO-Practice#99]
# Aim

locked problems on leetcode
# Details

problems and solutions of locked problems on leetcode

**Comment by Ayush7614** [comment]
@richadubey338 go Ahead

**Comment by richadubey338** [comment]
Hi Ayush!
My name is Richa Dubey. I am a 2nd-year undergraduate from NIT Bhopal. I
wanted to participate in let's grow more summer of code.  I have been
practicing coding since 2nd semester but I am new to open source Could you
please guide me to some extent on how to proceed with this.
I would be very grateful to you for this.

**Comment by Ayush7614** [comment]
Hi Richa you can join discord server for that
