### ISSUE TITLE
Bucket Sort using Python

### ISSUE THREAD

**Issue by ArshWalker** [Ayush7614/Daily-Coding-DS-ALGO-Practice#991]
# Aim

Bucket sort, or bin sort, is a sorting algorithm that works by distributing the elements of an array into a number of buckets. 

@Ayush7614 @Saurabh4626 Please Assign me under LGMSOC21

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

**Comment by ravikr126** [comment]
ok YOU CAN WORK ON IT ABD ALSO ADD 2-3 TESTCASES WITH EDGES CASES ALGO FOR BETTER UNDERSTANDING @ArshWalker

**Comment by tirth5828** [comment]
@ravikr126 @Ayush7614 @Saurabh4626  I would love to do this issue with JAVA and C++ . Please assign me under this languages under LGM-SOC'21

**Comment by puneetkaur2929** [comment]
@Ayush7614 @ravikr126 @Amit366 
I am interested to work on this issue in **C++.**
Kindly assign this issue to me under LGM SOC 21

**Comment by Amit366** [comment]
@tirth5828 do in java
